guardian/manage-frontend

- frontend/package.json
- frontend/typescript/colours.ts
- frontend/typescript/components/grid.tsx
- frontend/typescript/components/main.tsx
- frontend/typescript/styles/breakpoints.ts
- frontend/typescript/styles/grid.ts
- frontend/yarn.lock
This gives a nice API we should be able to use to use the gs-grid.
> First attempt at grid system.

- app/client/components/asyncLoader.tsx
- app/client/components/csr.tsx
- app/client/components/footer.tsx
- app/client/components/grid.tsx
- app/client/components/header.tsx
- app/client/components/main.tsx
- app/client/components/roundel.tsx
- app/client/components/spinner.tsx
- app/client/components/user.tsx
- app/package.json
- app/server/identity/identityMiddleware.ts
- app/server/server.ts
- app/tslint.json
- app/yarn.lock
This just makes some fixes to get this closer to passing type checking and linting. 
A lot of the lint rules seem not-useful. But this is probably worth thinking about. 
I've asked on the emotion slack about the css={} error we're getting from typescript.
> Type fixes

- app/server/server.ts
This was preventing us from running locally without the server DSN set.
> Make remaining sentry calls conditional

- README.md
- app/package.json
- app/server/log.ts
- app/webpack.dev.client.js
- cfn.yaml
- nginx/manage-frontend.conf
- nginx/setup.sh
- riff-raff.yaml
> rename account.theguardian.com to manage.theguardian.com

- app/client/components/callCentreNumbers.tsx
> correct "outside Australia" number

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/components/accordion.tsx
- app/client/components/cancel/cancellationSummary.tsx
- app/client/components/cancel/paidMembershipFlow.tsx
- app/client/components/cancel/stages/genericSaveAttempt.tsx
- app/client/components/cancellationFlowWrapper.tsx
- app/client/components/genericErrorScreen.tsx
- app/client/components/main.tsx
- app/client/components/membership.tsx
- app/client/components/page.tsx
- app/client/components/progressCounter.tsx
- app/client/components/wizardRouterAdapter.tsx
- app/package.json
Visually, it wasn't look very different (Some spacing has been shifted around), but this will go a long was to helping with responsiveness
> Rearrange structure and make consistent containers

- app/client/analytics.ts
- app/client/components/main.tsx
- app/server/html.ts
This adds GA tracking and a couple of helpers. The pages are currently tracked, but there are currently no events. We should decide what we want to track further.
> GA tracking

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/analytics.ts
- app/client/components/cancel/paidMembership/cancellationReasons.tsx
- app/client/components/cancel/stages/genericSaveAttempt.tsx
- app/client/components/footer.tsx
- corrected one 'reasonId'
- slight sizing tweak of 'backToTop'
- added GA event for feedback submitted
- updated mma_ 'reasonId' for _"taking a break from the news"_ reason
> small tweaks prior to prod rollout

- app/webpack.common.js
Will fix Promises and the like in IE11
> Target last 2 browser versions in babel

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/components/cancel/contributionsFlow.tsx
- app/client/components/cancel/freeMembershipFlow.tsx
- app/client/components/cancel/paidMembership/paidMembershipFlow.tsx
- app/client/components/cancellationFlowWrapper.tsx
- app/client/components/nav.tsx
- app/client/styles/grid.ts
- app/server/server.ts
- app/shared/meResponse.ts
This adds a endpoint which fetches a user ID, creates the link to the user's profile and redirects them there.
This was needed to add a link to the user's profile.
> Add link to Comments and Replies

- app/.babelrc
- app/package.json
- app/webpack.common.js
- app/yarn.lock
Used https://www.npmjs.com/package/depcheck  but it doesn't recognise JSX in TS so this was quite manual.
Also moved babel conf over to `.babelrc` for a separation of concerns.
> Clean up unused dependencies

- app/server/log.ts
- cfn.yaml
Reverts guardian/manage-frontend#70 (whilst I work out why the automated CFN update didn't work...)
> Revert "Fix Cloudwatch logging"

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/components/cancel/paidMembership/cancellationReasons.tsx
- app/client/components/footer.tsx
- app/client/components/footer/footer.tsx
- app/client/components/footer/footerlinks.tsx
- app/client/components/main.tsx
- app/client/components/nav.tsx
- app/client/components/page.tsx
- app/client/components/userNav.tsx
As it says up there ^
Needs testing on CODE as the iframe doesn't load locally.
blocked by #76
> Add main site footer to manage

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/components/footer/footer.tsx
Brings the footer more inline with profile.theguardian.com
> Footer tweaks

- app/client/colours.ts
- app/client/components/cancel/cancellationSummary.tsx
- app/client/components/membership.tsx
Shows the cancellation info on the membership tab
> Cancellation banner

- app/package.json
babel 7 is now stable - https://babeljs.io/versions
> update babel to stable

- app/server/html.ts
This is the correct order, apparently.
> reorder resources in head

- app/client/components/footer/in_page/spreadTheWordFooter.tsx
> added URL for facebook and twitter share buttons

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/components/footer/footerlinks.tsx
all the dynamic footer links were missing the DOT before the domain
> FIX of the footer links

- app/client/components/cancel/membership/membershipCancellationFlow.tsx
- app/client/components/membership.tsx
- app/client/components/payment/update/updatePaymentFlow.tsx
- Made the action required banner within the membership tab yellow
- Moved overall headings in the two flows to align vertically with everything else
> Tweaks for Gus

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/colours.ts
- app/client/components/footer/footer.tsx
- app/client/components/header.tsx
This just removes the blue from the nav, bringing us closer to  https://github.com/guardian/frontend/pull/20352
> remove blue from nav

- app/client/components/membership.tsx
- app/client/components/payment/directDebitDisplay.tsx
- app/client/components/payment/update/currentPaymentDetails.tsx
- app/client/components/payment/update/updatePaymentFlow.tsx
- app/client/components/user.tsx
Pre-work for direct debit support: some minor tweaks to improve the display of direct debit memberships and free memberships
> improved the display of direct debit and free products

- app/yarn.lock
follows on from the auto-generated https://github.com/guardian/manage-frontend/pull/134 (by @snyk-bot) to update the yarn.lock
> fixed snyk issue with react-dom

- app/server/identity/identityMiddleware.ts
added a new `profileReferrer` url param added during the signin/reauthenticate step so we can better track pageviews as to how/when they were authenticated 
for example:
1. if the incoming request is for `https://manage.theguardian.com/foo/bar?baz=test&INTCMP=test`
2. and signin is required, the profile signin url would be `https://profile.theguardian.com/signin?INTCMP=test&returnUrl=https%3A%2F%2Fmanage.thegulocal.com%2Ffoo%2Fbar%3FprofileReferrer%3Dsignin%26baz%3Dtest%26INTCMP%3Dtest`
3. after successfully signing in the user ends up on `https://manage.theguardian.com/foo/bar?`**`profileReferrer=signin`**`&baz=test&INTCMP=test`
also refactored the construction of the redirects to be cleaner
NOTE: this change was suggested by @jfsoul as part of a review of tracking
> added a new profileReferrer url param used in the signin/reauthenticate step

- app/yarn.lock
just adding the yarn.lock that was missing from https://github.com/guardian/manage-frontend/pull/145 - this is just to get master into a nicer state
> forgot to commit the yarn.lock

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/colours.ts
- app/client/components/header.tsx
- app/client/components/nav.tsx
- app/client/components/page.tsx
- app/client/components/productPage.tsx
- app/client/components/roundel.tsx
- app/client/components/userNav.tsx
precedes https://github.com/guardian/manage-frontend/pull/149
> various layout/colour tweaks (header)

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/colours.ts
- app/client/components/footer/footer.tsx
- app/client/components/footer/footerlinks.tsx
- app/client/components/header.tsx
- app/client/components/nav.tsx
- app/client/components/page.tsx
- app/client/components/productPage.tsx
- app/client/components/roundel.tsx
- app/client/components/userNav.tsx
follows on from https://github.com/guardian/manage-frontend/pull/147
> various layout/colour tweaks (footer)

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/components/buttons.tsx
- app/client/components/cancel/cancellationFlow.tsx
- app/client/components/cancel/cancellationSummary.tsx
- app/client/components/cancel/stages/executeCancellation.tsx
- app/client/components/cancel/stages/genericSaveAttempt.tsx
- app/client/components/noProduct.tsx
- app/client/components/payment/update/paymentUpdated.tsx
- app/client/components/productPage.tsx
- app/client/components/updatableAmount.tsx
- app/client/components/user.tsx
- app/client/components/wizardRouterAdapter.tsx
- app/package.json
- app/server/server.ts
- app/shared/productTypes.tsx
- app/yarn.lock
refactor/restructure to make 'cancellation flow' and 'product page' optional parts of a 'ProductType' to prepare for print being just payment update for now
> refactor/restructure to make 'cancellation flow' and 'product page' optional parts of a 'ProductType'

- app/client/components/payment/directDebitDisplay.tsx
as per comments in https://github.com/guardian/manage-frontend/pull/158
> swapped the 'sort code' and 'account number' on the DirectDebitDisplay

- README.md
Added in extra steps to make README clearer for new starters.
> improve installation instructions README

- app/package.json
- app/yarn.lock
Co-authored-by: Tom Richards <thomas.w.richards@gmail.com>
> only run client-side bundle check on commits where yarn.lock is changed

- .gitignore
- app/package.json
- app/yarn.lock
- sonar-project.properties
This PR concerns the implementation of Sonar analysis, but below is a screenshot of how the results would display in SonarQube.
> Add and configure Sonar analysis

- app/package.json
Quick modification following https://github.com/guardian/manage-frontend/pull/191
> Tweak Sonar scanner Yarn script 

- app/shared/productTypes.tsx
Small task to remove a switch statement that was no longer required.
> Sonar results remediation

- app/client/components/membershipFAQs.tsx
- Updated questions
- Tidied up CSS
- Made link text more accessible
- Consolidated 3 separate accordions into one
> Update membership FAQ

- app/server/identity/identityMiddleware.ts
When a user gets re-directed to profile to sign-in, we don't need to include query parameters in the manage return url that are only there to facilitate sign-in on profile. Therefore, remove them.
> Remove profile specific query parameters from return url

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/components/footer/footer.tsx
... so they can be tracked in acquisitions table
> Add 'mma_' to 'Contribute' and 'Subscribe' buttons in footer 

- app/package.json
the current version is reported as high severity by snyk
> Bump browserslist-useragent

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/components/footer/footer.tsx
@shtukas noticed copyright year was wrong in the footer on manage 😱 - so I've made it dynamic
> dynamic copyright date in footer

- app/package.json
- app/yarn.lock
Fixing manually in favour of auto-fix PR https://github.com/guardian/manage-frontend/pull/231 which seemed to change a lot!
> fixed 'Prototype Pollution' vuln in lodash (transitive via emotion and winston)

- app/client/__tests__/components/identity/__snapshots__/MarketingPreference.tsx.snap
- app/client/components/identity/EmailSettingsSection.tsx
- app/client/components/identity/MarketingPreference.tsx
Fixes a couple of typos and a slight alignment issue with the checkboxes on the Email and Marketing tab
> Fix email and marketing typos

- app/client/components/identity/EmailAndMarketing.tsx
- app/client/components/identity/useConsentOptions.ts
Adds missing error handling routines for caught exceptions
> Fix Caught Exception Handling on Email Preferences

- app/client/components/consent/PrivacySettings.tsx
Just an update to copy for the CMP UI, nothing more.
> Update CMP UI copy

- app/client/components/consent/PrivacySettings.tsx
Just some copy changes to help us pass the IAB validator.
> CMP UI copy changes

- app/client/components/consent/PrivacySettings.tsx
Currently when we load the CMP UI in an iframe from frontend we see the first re-render that's triggered after we've fetched the vendor list and updated the state accordingly. This PR now fires a `postMessage` to the window.parent notifying it that the vendor list has been fetched and the state updated  and the UI is ready to show. 
The related PR on frontend to listen for this and only show the UI once it's been received is here: https://github.com/guardian/frontend/pull/21764
> Post CMP ready message to parent of CMP UI

- app/client/components/consent/PrivacySettings.tsx
- app/types/consent.d.ts
Quick refactor of the CMP UI code. Mostly just shifting code from one place to another.
> CMP UI code refactor

- app/client/components/consent/PrivacySettings.tsx
- app/client/components/consent/cookie.ts
- app/types/consent.d.ts
This PR adds the 3 PECR purposes (Essential, Functional and Performance) to the CMP.
This version doesn't use the final version of designs (yet to be created) for the UI so it's not visually polished. It only aims at adding the underlying logic so the designs are easily added when they become available.
> Add PECR purposes

- app/client/components/consent/PrivacySettings.tsx
...so we can share this version (which was previously shown to the IAB) in frontend when the IAB officially reviews it on September 3rd.
> Comment out PECR related logic

- app/client/components/consent/PrivacySettings.tsx
...to the correct Frontend endpoint, that updates automatically.
> Update IAB Vendor List link

- app/client/components/consent/CollapseItemButton.tsx
- app/client/components/consent/ConsentMangementPortal.tsx
- app/client/components/consent/PrivacySettings.tsx
This PR introduces new styles for the button containers, making their background semi-opaque so when they're sticky you can see the scrollable content beneath the containers. We've also introduced smallSpace/mediumSpace variables to manage margins/padding.
> New button container styles

- app/client/components/consent/ConsentMangementPortal.tsx
- app/client/components/consent/PrivacySettings.tsx
- app/server/server.ts
This PR fixes layout bugs on the CMP UI by moving the "header" element into the "container".
> Fix layout bugs on CMP UI

- app/client/components/consent/CmpCollapsible.tsx
- app/client/components/consent/CmpItem.tsx
- app/client/components/consent/OnOffRadio.tsx
- app/client/components/consent/PrivacySettings.tsx
This PR introduces validation error messaging to the CMP UI. The `PrivacySettings` components now has an optional property on it's state `iabNullResponses`, this is an array  which holds the ID of all IAB purposes which have not been completed by the user when they've attempted to click the "save and continue" button.
**Mobile screenshot...**
>  CMP UI - Validation error messaging

- app/client/components/consent/PrivacySettings.tsx
> Minor copy update to CMP UI

- README.md
- cfn.yaml
https://trello.com/c/2lA8pxcz/1501-enable-ssh-access-to-all-our-servers
> Enable ssh tunnelling from bastion, Remove unused ingress

- app/client/components/consent/PrivacySettings.tsx
Fixes a layout issue with the topButtonContainer
> fix top button container padding

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/components/holiday/summaryTable.tsx
- app/client/components/userNav.tsx
- app/client/expanderButton.tsx
moving/reusing some of the CSS from `UserNav` and made use of it in the holiday stops `SummaryTable`
> added new ExpanderButton component - and used to make the holiday stops publication list expandable

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/components/nav.tsx
- app/client/components/user.tsx
- app/client/components/userNav.tsx
Changes the navigation links to point to the new account tab. This essentially releases the feature on manage frontend.
* #276
> Activate new account tab

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/components/header.tsx
- app/client/components/userNav.tsx
This PR is to refactor the userNav component to replace lifecycle methods with hooks so that the component is functional instead of class based.
> User nav hooks refactor

- app/client/components/consent/PrivacySettings.tsx
Removes `CmpUiNonDismissable` related code from the CMP UI.
> Remove CmpUiNonDismissable related code

- app/client/components/holiday/holidayDateChooser.tsx
…either because [the limit was wrong for a while](https://github.com/guardian/support-service-lambdas/pull/493) or because CSRs have done it intentionally.
**It's worth pointing out that if/when we do issue limits feature for CSRs, all this limits logic will move out of the client into the `holiday-stop-api` for re-use/consistency.**
The annual issue limit is displayed in numerous places and most of them automatically show the _now correct_ limit. Therefore if the user has gone over (see above) it is displayed as follows on the Holiday Overview screen as desired...
However we don't want to see negatives on the amend screens and ideally we want people to be able to amend holiday stops **within** their _increased_ limit, so this PR adjusts those calculations my taking the `Math.max` of the …
> allow amending of holiday stops where user is already over the annual issue/voucher limit

- app/client/components/delivery/address/formValidation.tsx
Fix issue where people without home delivery subscriptions were seeing the M25 area postcode validation error message.
> BUG - fix home delivery postcode validation

- app/client/components/delivery/address/deliveryAddressForm.tsx
> [RB] - increase the size of the postcode input to accommodate large postcodes

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/components/userNav.tsx
> [RB] - add the help tab into the 'my account' menu drop down on mobile breakpoints

- app/client/components/help.tsx
- app/client/components/svgs/helpSectionIcon.tsx
Before iphone 5            |  After iphone 5
Before desktop             |  After desktop
> Help section title and cta copy changes

- app/client/__tests__/components/delivery/records/deliveryRecords/step1.tsx
- app/client/components/delivery/records/deliveryRecords.tsx
- app/client/components/productPage.tsx
- app/shared/productTypes.tsx
following successful testing when limited just to me, this PR should open up delivery problem reporting to all GW users
> release delivery problem reporting to all GW customers

- app/client/components/help.tsx
> [RB] - fix 'report technical issue' link href in help section

- app/client/components/delivery/records/deliveryRecords.tsx
- app/client/components/svgs/giftIcon.tsx
**After clicking on the 'Report a problem' button**,  if none of their delivery records can be reported, show info message and stop people from continuing down the problem reporting journey.
This may be because they have reported problems on all of the delivery records they have, or the records are too old.
> [RB] - problem reporting bug when reporting where no valid records to report

- app/client/components/delivery/address/deliveryAddressForm.tsx
> [RB] - restrict resizing of the instructions textarea to the vertical axis

- app/client/components/delivery/records/deliveryRecords.tsx
…until call-centre has capacity to investigate.
> temporarily stop escalation of HD delivery problems based on repeat problem detection

- app/client/components/payment/update/card/cardInputForm.tsx
> tweak & linkify reCaptcha prefix text in the payment update flow

- app/client/components/delivery/records/deliveryRecordStatus.tsx
> [RB] - remove uneeded 'to' from delivery suspension message

- app/client/accountOverviewRelease.ts
- app/client/components/analytics.tsx
- app/server/accountOverviewRelease.ts
- app/server/apiProxy.ts
- app/server/stripeSetupIntentsHandler.ts
- app/shared/accountOverviewRelease.ts
…with integration/tracking in GA, Ophan and our server-side logging.
> add mechanism for putting 50% users into the 'Account Overview' test

- app/client/components/payment/update/updatePaymentFlow.tsx
revert 'PaymentUpdaterStep' back to class based component so state can be passed through correctly (as DD update was broken following #406 )
> FIX direct debit update flow

- app/client/components/accountoverview/product.tsx
- app/client/components/svgs/giftIcon.tsx
On smaller breakpoints allow the display of the gift type subscription and it's cancelled status
> Cancelled gift mobile

- app/shared/accountOverviewRelease.ts
Force every user into the AccountOverview test (without yet removing any of the tracking or old code - this will come in subsequent PRs)
> AccountOverview to 💯%

- app/client/components/accountoverview/manageProduct.tsx
- app/client/components/delivery/address/deliveryAddressDisplay.tsx
- app/client/components/delivery/address/deliveryAddressEditConfirmation.tsx
- app/client/components/delivery/address/deliveryAddressForm.tsx
- app/client/components/delivery/address/deliveryAddressFormContext.tsx
- app/client/components/delivery/address/deliveryAddressReview.tsx
- app/client/components/delivery/records/deliveryAddressStep.tsx
- app/client/components/delivery/records/deliveryRecordsProblemConfirmation.tsx
- app/client/components/productDescriptionListTable.tsx
- app/client/components/productPage.tsx
- Removed unnecessary duplicate calls to members data API for delivery address update journeys
- Update delivery problem reporting and delivery address update confirmation return buttons
fewer loads innit!
NO!
> [RB TR] - remove unnecessary duplicate membersDataAPI calls. Button fixes.

- app/client/components/productDetailProvider.tsx
This came about in #425 where we converted a class based component to a functional one, accidentally losing the componentDidMount benefits that were important in the below:
- https://github.com/guardian/manage-frontend/commit/5cb8c7a84399185339a057d0961b09b5123a3d1e#diff-80c45e47af81baf4ac77ffcff3aed2ab
- https://github.com/guardian/manage-frontend/pull/247
Stops server render from making parts of the page spin around the loading spinner :trollface: 
No more silliness
> [RB TR] - fix funky SSR problem with productDetailProvider

- app/shared/productTypes.tsx
> [RB TR] - fix typos

- app/client/__tests__/components/delivery/address/formValidation.ts
- app/client/components/delivery/address/deliveryAddressForm.tsx
- app/client/components/delivery/records/deliveryRecords.tsx
- app/shared/productTypes.tsx
> Last product types tidyup

- app/client/components/accountoverview/accountOverview.tsx
Add key prop to repeated fragment to suppress warning
> [RB TR] - add key prop to fragment list items

- app/client/components/nav/leftSideNav.tsx
- app/client/components/page.tsx
- app/client/components/payment/directDebitLogo.tsx
> Ie11 fixes

- app/client/components/callCenterEmailAndNumbers.tsx
> [RB] - fix typo

- app/client/components/accountoverview/newsletterOptinSection.tsx
Minor copy change to the title of the Front page newsletter subsection title within the manage subscription page.
> [RB] - Front page newsletter title copy change

- app/client/components/billing/billing.tsx
- app/client/components/billing/invoiceTableYearSelect.tsx
- app/client/components/billing/invoicesTable.tsx
- app/client/components/pagination.tsx
- app/client/components/payment/directDebitDisplay.tsx
- app/client/components/payment/paypalDisplay.tsx
- app/client/components/productDescriptionListTable.tsx
- app/client/components/svgs/downloadIcon.tsx
- app/server/apiGatewayDiscovery.ts
- app/server/apiProxy.ts
- app/server/routes/api.ts
- app/server/routes/products.ts
- app/shared/productResponse.ts
Reverts guardian/manage-frontend#481
Reverts the revert so that users can see the invoices again. No Changes were required to the original pr hence the revert revert!
> Revert "Revert "Billing invoices""

- cfn.yaml
Add LIST_INVOICES and GET_INVOICE_PDF metrics to the cloudwatch dashboard
(nicer screenshot to come ...)
> [LIST_INVOICES and GET_INVOICE_PDF dashboard metrics

- app/package.json
- app/yarn.lock
Updates `aws-sdk` library from **v2.383.0** to **v2.746.0**.
Updates `aws4` library from **v1.10.0** to **v1.10.1**.
Just making sure we're up to date. No code changes necessary.
Tested on CODE.
> Update aws libraries

- app/.snyk
Apply `snyk wizard` to ignore vulnerabilities where there is no dependency update available.
This fixes the main branch.
> snyk wizard

- app/client/__tests__/__snapshots__/main.tsx.snap
- app/client/components/footer/footer.tsx
Change the min height of the iframe element used for newsletter signup in the footer. Needed because the iframe content has changed and now takes up more space.
Run locally.
> Update iframe min-height for new sign up content.

- docs/05-form-submission-via-server-side.md
Adds an architecture decision made by the team regarding form submissions in this project.
> Form submission architecture decision

- app/client/components/contactUs/contactUs.tsx
- app/client/components/contactUs/contactUsForm.tsx
- app/server/contactUsApi.ts
- app/server/recaptchaConfig.ts
- app/server/routes/frontend.ts
- app/server/stripeSetupIntentConfig.ts
- app/server/stripeSetupIntentsHandler.ts
Adds a re-captcha gate to the contact us form.
> Contact us form captcha

- app/shared/contactUsConfig.ts
Small copy update for the Contact Us config.
> Update Contact Us config

- app/client/components/contactUs/contactUs.tsx
- app/client/components/contactUs/subTopicForm.tsx
- app/client/components/contactUs/topicForm.tsx
- app/client/components/scrollToTop.tsx
- app/client/components/user.tsx
This PR makes changes to the `ContactUs` component such that it uses the URL parameters instead of an internal state. This causes the URL to update as the uses chooses their topic/subtopic/subsubtopic and allows passing that URL to users to link them directly to a specific choice.
> Contact Us form deeplinking

- app/client/components/contactUs/contactUs.tsx
- app/client/components/contactUs/contactUsForm.tsx
- app/client/components/contactUs/uploadFileInput.tsx
- app/server/contactUsApi.ts
- app/server/server.ts
- app/shared/fileUploadUtils.ts
add the ability to attach an image to the contact us form submission
> Contact us form attachment

- app/client/components/contactUs/contactUsHeader.tsx
Add the link to the help centre in the contact us header
> [RB] - link to the help centre from the contact us form

- app/client/components/contactUs/contactUsForm.tsx
- app/server/contactUsApi.ts
This allows our users to send us larger messages in the Contact Us form. No service layer changes needed.
> Contact Us form: Allow larger messages

- app/client/components/helpCentre/HelpTopicBox.tsx
- app/client/components/helpCentre/helpCentre.tsx
- app/client/components/helpCentre/helpCentreConfig.ts
Add tracking for the help centre most popular topic questions
> [RB] - help centre questions tracking

- app/client/components/helpCentre/helpCentreConfig.ts
minor copy change to one of the subscription topic questions.
> [RB] - minor copy amend

- app/client/components/callCenterEmailAndNumbers.tsx
Update to the UK call centre opening times
> [RB] - update to uk call centre opening times

- app/.snyk
Update to snyk config via snyk wizard
> [RB] - update to snyk config via snyk wizard

- app/.snyk
> [RB] - update to snyk wizard config

- app/.snyk
> [RB MO] - update snyk wizard

- docs/05-form-submission-via-server-side.md
Changes the wording of the form submission architecture decision following @kelvin-chappell 's suggestions on #508 (which I only recently noticed)
> Better wording for the form submission architecture decision

- app/.snyk
> Update snyk policy

- app/client/components/helpCentre/helpCentre.tsx
- app/client/components/helpCentre/helpCentreMoreTopics.tsx
This PR modifies the naming of a component and updates web text content.
> Change helpCentreFaq to helpCentreMoreTopics

- .github/workflows/snyk.monitor.yml
- .github/workflows/snyk.test.yml
Small PR to improve the names of the Snyk GitHub Actions introduced by #596
> Better names for Snyk GitHub actions

- app/client/components/helpCentre/helpCentreConfig.ts
So that they go to internal articles.
> Update journalism links on landing page

- app/server/routes/core.ts
Ssh! This is secret until we set up the redirects.
So in draft state until then.
> Tell robots where to find the Help Centre sitemap

- app/client/components/helpCentre/helpCentre.tsx
- app/client/components/liveChat/liveChat.tsx
- app/client/components/liveChat/liveChatFeatureSwitch.ts
Consolidate the feature switch functionality for live chat into a url param / session storage solution.
Previously the url param and a seperate variable were being used for the instantiation of live chat and the display of the "Start live chat" button.
> [RB] - consolidate the feature switch functionality for live chat

- app/client/components/helpCentre/helpCentreEmailAndLiveChat.tsx
Adds custom css styling to the queue position state of live chat.
- visit https://manage.thegulocal.com/help-centre/?liveChat=1
- click on Start live chat button
- simulate the loading error of the salesforce script (`esw.min.js`). One way of doing this is to reject instead of resolve the promise in the `initLiveChat` function in liveChat.tsx
> [RB] - copy update and minor adjustment to warning icon position

- app/client/components/helpCentre/helpCentreEmailAndLiveChat.tsx
Changed from 9am - 6pm every day to: 9am - 10pm, Monday - Friday, and 9am - 6pm, Saturday - Sunday (GMT/BST)</p>
> Updated opening hours for Live Chat

- app/client/components/MMAPage.tsx
- app/client/components/maintenance.tsx
- app/server/middleware/identityMiddleware.ts
- app/shared/requiresSignin.ts
This adds a minimal 'down for maintenance' page and route to the app. This is primarily in support of the upcoming Identity outage, but can also be used for any other planned maintenance or system outages.
> Add minimal maintenance page

- cypress/integration/parallel-2/cancelContribution.spec.ts
Updates spec to match new copy in cancellation flow.
> Fix contribution cancellation spec

- client/components/helpCentre/HelpCentrePage.tsx
Add known issue banner for [IT Incident](https://www.theguardian.com/media/2022/dec/21/guardian-hit-by-serious-it-incident-believed-to-be-ransomware-attack)
> Add known issue for today's paper

- client/__tests__/components/helpCentre/__snapshots__/helpCentreContactOptions.test.tsx.snap
- client/components/helpCentre/HelpCentrePage.tsx
- client/components/shared/CallCenterEmailAndNumbers.tsx
Update to Christmas opening hours in the known issues banner and opening times component.
> [RB] - update xmas opening hours 🎄🎁☃️

- client/components/mma/switch/SwitchReview.tsx
Updates to the dynamic Terms and Conditions copy.
Go to `/switch/review`.
> Update Ts and Cs copy

- client/components/mma/switch/SwitchComplete.tsx
Fixes a couple of minor issues noticed during end-to-end testing of the switching journey.
> Post end-to-end testing minor spacing fixes

- client/components/mma/switch/SwitchReview.tsx
Updates product switching terms and conditions with latest copy from legal.
> Update terms and conditions copy

- client/components/mma/accountoverview/AccountOverview.tsx
Refactors the Account Overview page away from the AsyncLoader pattern.
> Refactor Account Overview to useAsyncLoader hook

- README.md
[Identity frontend](https://github.com/guardian/identity-frontend) has been archived, remove reference to it.
> Update README - remove reference to identity-frontend (archived)

- client/components/mma/dataPrivacy/CookiesOnTheBrowserSection.tsx
- client/components/mma/dataPrivacy/YourDataSection.tsx
Text only. DPO requested some very minor changes
Wait for CI checks to run. Check it in CODE.
> Update text at request of DPO

- package.json
- yarn.lock
Upgrade webpack-dev-server to upgrade node-forge. To fix [alert](https://github.com/guardian/manage-frontend/security/dependabot/62) 
> Fix dependabot alerts - Upgrade node-forge

- package.json
- yarn.lock
> feat: upgrade cmp

- client/components/mma/accountoverview/AccountOverview.tsx
- shared/featureSwitches.ts
Have also moved SC's to be displayed under 'Subscriptions' instead of 'Recurring Support'.
> Enable display of single contributions on Account Overview

- client/components/mma/upgrade/ConfirmForm.tsx
- client/components/mma/upgrade/UpgradeSupportSwitchThankYou.tsx
- client/components/mma/upgrade/UpgradeSupportThankYou.tsx
Updated switch thank you page as per the designs on figma.
Storybook or head to upgrade-support/switch-thank-you
> Switch thank you (V3)

- .github/workflows/ci.yml
This PR configures the `assets-static` Riff-Raff deployment.
> configure `assets-static` Riff-Raff deployment

- .github/workflows/cypress.yml
- .gitignore
- riff-raff.yaml
- webpack.common.js
- webpack.dev.client.js
- webpack.dev.server.js
- webpack.prod.client.bundle-check.js
- webpack.production.js
This PR is a follow-up from the Teamcity to Github Actions migration. It removes the final reference to Teamcity from the repo.
> replace reference to `TEAMCITY_BUILD` with `GITHUB_RUN_NUMBER`

- client/components/mma/upgrade/UpgradeSupportThankYou.tsx
- client/utilities/supportPricing/contributionsAmount.ts
- client/utilities/supportPricing/suggestedAmounts.ts
Fixes 3 things spotted in end to end testing:
1.  "Your billing date" on RC thank you page
2.  Minimum contribution amounts (now using same prices as support frontend [ref](https://github.com/guardian/support-frontend/blob/ceb09f6d6af15cbf047013ad3c5bd10846c86543/support-frontend/assets/helpers/contributions.ts#L203))
3. Adjust suggested amounts as per [spreadsheet](https://docs.google.com/spreadsheets/d/1lxnOJhSPrddZmdjNe85sbTCtprqQlSy6_QcwY_n7AFk/edit#gid=0)
1. Upgrade RC to RC, don't see "Your billing date has changed"
2. Can lower monthly amount to 2 in CAD
3. Suggested annual amounts include threshold …
> Update Support - fixes from end to end testing

- client/components/helpCentre/HelpCentrePage.tsx
Reverts guardian/manage-frontend#1219
> Revert "Help centre banner: phone lines being unavailable in Canada and the US"

- client/utilities/hooks/useAnalytics.ts
Quantum Metric (QM) have requested we update the script
There isn't a way of testing this on our side without deploying the tag to production, the plan is for QM to monitor the change on their side and flag to us are any issues.
I don't think there any major risks but I will be communication with QM to make sure that sessions are captured and everything continues to work as expected.
-   [ ] …
> Update Quantum Metrics Script

- client/components/mma/cancel/cancellationSaves/CancellationLanding.tsx
- client/components/shared/CallCenterEmailAndNumbers.tsx
- client/components/shared/CallCentreAccordion.stories.tsx
- client/components/shared/CallCentreAccordion.tsx
- client/components/shared/callCentreData.ts
- shared/productResponse.ts
Create a new call centre numbers component using Source's `Accordion`. This is closer to the design in the figma 
and has better accessibility than the existing component but has some drawbacks - we cannot open a section by default and we have to use a cssOverride to style the label.
New component:
Old component:  …
> Create call centre numbers accordion component

- package.json
- yarn.lock
Bump the aws-sdk version to try remove [dependabot alert](https://github.com/guardian/manage-frontend/security/dependabot/89)
AWS functionality still works - S3, api-gateway
> bump aws-sdk (v2)

- package.json
- yarn.lock
Bumps nodemon to fix [dependabot alert](https://github.com/guardian/manage-frontend/security/dependabot/66)
`scripts": {
"start": "nodemon --inspect ./dist/server"`
`yarn start` (see above) should still work as before
> Bump nodemon

- package.json
- yarn.lock
#1260 fixed one dependabot alert but created [another](https://github.com/guardian/manage-frontend/security/dependabot/100), so bumping to latest version. Can't see any breaking changes in [release notes](https://github.com/remy/nodemon/releases/tag/v3.0.1)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-v …
> bump nodemon to latest

- client/components/helpCentre/HelpCentrePage.tsx
Reverts guardian/manage-frontend#1278
> Revert "Add xmas opening times help centre message"

- shared/featureSwitches.ts
Reverts guardian/manage-frontend#1287
> Revert "Revert "Digisub saves - turn on feature switch""

- README.md
We discovered that social sign in doesn't play nicely with the local nginx proxy, so add a note to the README to make this clearer.
> Update README with note about local proxy and social sign-in

- yarn.lock
This picks up the yarn lock dependency that seems to somehow have been missed during the last yarn install.
> Ran yarn install to update yarn lock

- yarn.lock
Ran `corepack yarn cache clean` and then `corepack yarn@1.22.5 install` and it managed to find the weirdly missing dependency.  Let's see what Snyk can find that we can't next...
> Running corepack yarn@1.22.5 install came up with the other missing dependency

- package.json
- yarn.lock
Updated @guardian/consent-management-platform to 13.1.1 `and @guardian/commercial to the latest version
Deployed to CODE and tested CMP functions.
> Updated @guardian/consent-management-platform and commercial

- .github/CODEOWNERS
Add the SR Value team as code owners of this repo.
> Add Value as CODEOWNERS

- client/utilities/hooks/useAnalytics.ts
> update quantum metric script

- package.json
- yarn.lock
Update dependencies that use braces and fix braces vulnerability manually (where a dependency update was not good enough)
> fix braces vulnerability

- client/components/helpCentre/HelpCentrePage.tsx
The banner added in #1367 is no longer needed.
Revert "Add help centre banner message (#1367)"
This reverts commit b9d41ef93327bbeb724b087746e2626e970c0905.
> Remove help centre banner

- .storybook/viewport.ts
- client/components/mma/cancel/cancellationSaves/supporterplus/SupporterPlusOffer.tsx
Add specific view for the tablet breakpoint for the cancellation offer journey. The tablet view changes from a stacked view to a column one.
> Cancellation offer journey Tablet breakpoint

- package.json
- yarn.lock
fix njwt (peer) vulnerability
https://app.snyk.io/vuln/SNYK-JS-NJWT-6861582
> fix njwt (peer) vulnerability

- client/components/mma/cancel/Cancellation.stories.tsx
Fix cancellation confirmation story missing function parameter
> fix cancellation confirmation story missing function parameter

- package.json
- yarn.lock
Fix vulnerability in dset peer dependency by updating guardian/commercial (primary dependency) to its latest version
> dset v3.1.2 vulnerability fix

- client/components/helpCentre/HelpCentrePage.tsx
New help centre banner copy requested by customer operations due to ongoing US Phone line issues.
Added new banner as shown below.
> Add new banner to help centre for US Phone line outage

- client/components/helpCentre/HelpCentrePage.tsx
> add a message about xmas opening times to the the help centre 🎄 

- client/components/mma/holiday/HolidaysOverview.tsx
- client/components/mma/holiday/SummaryTable.tsx
- client/components/mma/identity/form/FormField.tsx
- client/components/mma/identity/publicProfile/AvatarSection.tsx
- client/components/mma/identity/publicProfile/ProfileFormSection.tsx
- client/components/mma/identity/settings/SettingsFormSection.tsx
- client/components/mma/identity/sharedStyles.ts
- yarn.lock
Fixes a few visual bugs that were introduced as part of the broader work to update the version of source library that MMA uses.
> fix source update design bugs

- client/components/helpCentre/HelpCentrePage.tsx
Reverts the change in #1444 , removing the banner from the Help Centre again.
> Revert Help Centre banner added in #1444

- cypress/lib/signInOkta.ts
Identity have changed the way that password sign in works in https://github.com/guardian/gateway/pull/3058, so update the  test behaviour to reflect that.
> fix(cypress): fix sign in okta test

- client/utilities/hooks/useConsent.ts
- package.json
- yarn.lock
This work is happening in relation to Consent or Pay
- Bumps @guardian/libs to the latest version.
- Using non advertising vendor list.
> Update @guardian/libs to latest

- package.json
- yarn.lock
Bumping @guardian/libs to latest version.
For Consent or Pay release
> Bump guardian/libs to 22.0.0

- client/components/helpCentre/HelpCentrePage.tsx
There is currently a telephony issue in our contact centre. This PR adds a banner to direct our customers to email us or use live chat to contact us with their queries to offset this issue.
Add a new Banner to help centre - image to follow.
> Add Banner to Help Centre due to Telephony issues

- client/components/mma/identity/emailAndMarketing/NewsletterSection.tsx
- client/components/mma/identity/emailAndMarketing/ObserverNewsletterLink.tsx
- cypress/tests/e2e/e2e.cy.ts
Adds a link to the observer newsletter
> Create ObserverNewsletterLink and add to newsletter section
