build-tc

re-export TEAMCITY_BRANCH which removes / before 'node-riffraff-artefact' can split on / and conflate PRs into 'merge'
see https://github.com/guardian/node-riffraff-artefact/issues/30 for more info

workaround for the split("/") in 'node-riffraff-artefact' 

---

cloud-formation/account-frontend-cf.yaml

It's already public everywhere, however it's better using a variable too.

Parameterise the office CIDR

---

app/package.json
app/webpack.common.js

Restores the publicPath property so webpack dev server doesn't proxy the client bundle. I thought that it was working without this, but I must have been mistaken. @twrichards

set publicpath for webpack

---

cloud-formation/account-frontend-cf.yaml

There is a list of fastly ips, but it's too big to cloudform. 
This will make CODE publicly accessible, like the rest of code. 
This will make the PROD ELB publicly accessible, but impossible to authenticate against. It will allow fastly to connect to the ELB. Presently this doesn't have a CNAME pointing at fastly so won't be accessible until we're happy with the IP restriction.

Open load balancers to allow fastly access.

---

cloud-formation/account-frontend-cf.yaml
riff-raff.yaml

Applies the cloudformation template updates before updating the ami parameter. 
This might also be soluble by removing the default ami parameter.

Make riffraff update amis

---

app/server/server.ts

since api requests are proxied via Node, Fastly was caching api endpoint responses and thus serving up users data to other users 😱

added "Cache-Control: private" header to every response to prevent Fastly issues

---

app/client/components/cancel/stages/genericSaveAttempt.tsx
app/client/components/wizardRouterAdapter.tsx

Had nasty feeling that users were entering feedback but not clicking submit before confirming cancellation and thus some feedback may have been lost. Now if the user has entered feedback then it will now be submitted silently in the background if they click Confirm Cancellation (without having hit Submit Feedback).

'Confirm Cancellation' also now submits feedback if entered

---

app/client/components/cancel/cancellationSummary.tsx
app/client/components/cancel/paidMembership/paidMembershipFlow.tsx
app/client/components/cancel/stages/executeCancellation.tsx
app/client/components/membership.tsx
app/server/server.ts

Because free memberships (e.g. Staff, Friend) cancel immediately and the `members-data-api` response is `{}` it used think that was an error (because no `subscription` property in the response) now it handles and shows an appropriate message.

Handle free memberships (e.g. Staff, Friend)

---

app/client/components/main.tsx
app/package.json
app/webpack.common.js

This will fix some sentry bugs we've been getting, by allowing babel to polyfill things per use
Fixes https://sentry.io/the-guardian/manage-frontend-client/issues/614206024/

switch on per-usage polyfills for older browsers

---

app/server/log.ts
cfn.yaml

I noticed that this wasn't working, after some digging it turned out:
1. The log file was not being created on the EC2 instance due to filesystem permissions.
2. There were no IAM permissions for pushing logs to Cloudwatch.
This PR fixes those issues and removes a couple of redundant pieces of config/code.

Fix Cloudwatch logging

---

riff-raff.yaml

Prior to this we were attempting to update the launch config with an old AMI id (i.e. the one specified in the CFN template) during the first CFN update, and then updating the launch config again to use the correct (latest) AMI. 
As well as being inefficient, this method completely stopped working this morning as the AMI referenced in CFN no longer exists (presumably due to https://github.com/guardian/amigo/pull/196).

Update the AMI as part of the CFN update

---

app/client/components/main.tsx
app/package.json
app/webpack.common.js

https://babeljs.io/docs/en/next/babel-preset-env.html#usebuiltins - Allows babel to replace old usages via babel-polyfill at compile-time.
[`whatwg-fetch`](https://github.com/github/fetch) is included as fetch is not considered to be a part of core JS, and is therefore not available to babel-polyfill

Polyfill more browsers and add fetch

---

cfn.yaml

the `latest` folder was changed, I've now referred to the specific version we were using before.

fix node version in cfn

---

app/client/components/caseCreationWrapper.tsx

…this fix makes it return "undefined" string in this case, so that 'gaData' key is ALWAYS present in post body to avoid 400 errors

FIX: gaData was being omitted from the post body if the user had GA blocked

---

app/client/components/cancel/paidMembership/cancellationReasons.tsx
app/client/components/cancel/paidMembership/paidMembershipFlow.tsx
app/client/components/cancel/paidMembership/switchToContributionPlaceholder.tsx
app/client/components/cancel/stages/genericSaveAttempt.tsx
app/client/components/page.tsx
app/client/components/user.tsx
app/globals.ts

For more complicated experiments (more than just text, minor css changes) we don't want to rely on Google Optimize (generally to minimise dependency on vendor tools but also not version controlled) so introduced experimentFlags (set on window.guardian) which can be set in Google Optimize to trigger the 'advanced' changes which are actually part of the deployed codebase.

 Added notion of experimentFlags (set on window.guardian)

---

app/client/components/cancel/stages/executeCancellation.tsx
app/client/components/caseCreationWrapper.tsx
app/client/components/caseUpdate.tsx
app/client/components/membership.tsx

As all our client calls are to same origin, this explicitly marks them as such.
May help with the "Access-Control-Allow-Origin" issues we're seeing on Mobile safari

explicitly mark proxy calls as same-origin

---

app/client/components/GoogleOptimiseAwaitFlagWrapper.tsx
app/client/components/analytics.tsx
app/client/components/cancel/paidMembership/paidMembershipFlow.tsx
app/client/components/cancel/stages/genericSaveAttempt.tsx
app/client/components/payment/paypalDisplay.tsx
app/client/components/user.tsx
app/client/components/wizardRouterAdapter.tsx
app/globals.ts
app/server/html.ts

Previously Google Optimize only worked on the first page load and only for flag based experiments, which were still 'racey' even then.
Now it uses MutationObserver to push `"optimize.activate"` `dataLayer` event on DOM changes to apply an _applicable_ experiments (typically to catch the non-engineer created experiments).
Also includes a neat `GoogleOptimiseAwaitFlagWrapper` component which eliminates the race condition by awaiting the outcome of the "optimize.activate" in the render. It uses ‘named slots projection’ pattern (children as an object map) for React children - which leads to really readable and typesafe code :)

Single Page App support for Google Optimise

---

app/package.json

https://github.com/guardian/support-frontend/wiki/Supported-Browsers - Matches the syntax Support frontend uses and commits to a hybrid coverage of that and the coverage frontend provides.

Update Browser list

---

app/webpack.common.js

Should allow Browserlist-useragent to find it and display errors correctly.

move package.json to static on build

---

app/client/components/payment/update/stripeCardInputForm.tsx

(which was displaying for a split second while stripe lib loads async) - now just part of the `isLoaded` which mainly awaits the the three inputs being _ready_

fixed spurious warning about stripe not loading 

---

app/server/__tests__/identity/identity.ts
app/server/identity/identity.ts
app/server/identity/identityMiddleware.ts
app/server/server.ts

The MMA pages of profile.theguardian.com have a one hour re-authenticate requirement. This PR adds the same to all of manage.theguardian.com (before we release the payment update functionality).
For profile behaviour, see...
https://github.com/guardian/frontend/blob/f033cc8dc41ebbc96be63425a0a14cd734647443/identity/app/services/AuthenticationService.scala#L49-L55

Added one hour re-authenticate requirement to the whole of manage.theguardian.com (to match profile)

---

app/client/components/payment/update/cardInputForm.tsx
app/client/components/payment/update/stripeCardInputForm.tsx
app/client/components/payment/update/updatePaymentFlow.tsx
app/client/components/user.tsx

(for parity with current payment update mechanism).
This doesn't appear to be essential for the transaction to be successful, however for consistency and if anyone is using it in reports or indeed if the card becomes detached it could be useful.
This allows for the value to come from members-data-api (PR to follow) but falls back to value of GU_SIGNIN_EMAIL cookie.

added email address (under Name field) when creating Stripe token 

---

app/client/components/buttons.tsx
app/client/components/cancel/cancellationSummary.tsx
app/client/components/cancel/stages/genericSaveAttempt.tsx
app/client/components/footer/in_page/questionsFooter.tsx
app/client/components/membership.tsx
app/client/components/payment/update/confirmCardUpdate.tsx
app/client/components/payment/update/paymentUpdated.tsx
app/client/components/payment/update/stripeCardInputForm.tsx
app/client/components/payment/update/updatePaymentFlow.tsx
app/client/components/wizardRouterAdapter.tsx

1. Changing "contact us" copy 
2. Confirmation page
- If not in payment failure- then shows next payment date etc. (as before)
- If in payment failure- We will take the payment in the next 24 hours.  ( in place of next payment date etc.) 
3. Yellow forward buttons 
4. Hollowed out "return to your account" button
5.  Manage + explore guardian buttons on confirmation as forward

Post demo tweaks

---

app/client/components/cancel/cancellationSummary.tsx
app/client/components/cancel/membership/cancellationReasons.tsx
app/client/components/cancel/membership/switchToContributionPlaceholder.tsx

tweaked the wording of the 'switch to contribution' placeholder and added an event should they then go on click the "Support The Guardian" button. Once deployed its ready to start the experiment.

tweaked the wording of the 'switch to contribution' placeholder

---

app/client/components/faqs.tsx

Also reduced complexity by always using theguardian.com rather than environment specific domain

fixed broken membership FAQ links 

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/cancel/cancellationSummary.tsx
app/client/components/cancel/membership/membershipCancellationFlow.tsx
app/client/components/cancel/membership/noMembership.tsx
app/client/components/cancellationFlowWrapper.tsx
app/client/components/membership.tsx
app/client/components/notFound.tsx
app/client/components/payment/update/updatePaymentFlow.tsx
app/client/components/redirectOnMeResponse.tsx
app/client/components/supportTheGuardianButton.tsx
app/client/components/userNav.tsx
app/client/components/wizardRouterAdapter.tsx
app/shared/productTypes.tsx

Previously if uses clicked external links directly into membership cancellation flow (e.g. membership help, delete you account instructions etc.) they would see a misleading generic error screen. Now they see a nice clear message and button to 'Support The Guardian'...
Similarly, visitors to the membership tab (who didn't have a membership) used to see basic 'No Membership' heading, whereas the component is now nicely reused...

Add a proper 'No Membership' screen

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/main.tsx
app/client/components/nav.tsx
app/client/components/roundel.tsx

fixed the outrageous placement of the footer, roundel and tabs (caused by IE11's numerous flexbox implementation bugs)
**Before**
**After**

IE11: fixed the outrageous placement of the footer, roundel and tabs

---

app/server/server.ts

This change is to add a little brokering point for the CTA on the DOTCOM banner so we don't need to expose the purpose of the 'action required' in the URL.
See also...
https://github.com/guardian/frontend/pull/20430

redirect for use with the dotcom banner so we don't need to expose 'payment' in the URL

---

app/client/components/user.tsx

just temporarily hardcoded the route for the contributions tab to ensure all flows lead back there (as per TODO will remove once we fully migrate contributions tab)

temporarily hardcoded the route for the contributions tab

---

app/client/components/analytics.tsx
app/client/components/progressBreadcrumb.tsx

Whilst trying to replicate the TypeError on iOS I noticed the progress breadcrumb was a bit squashed so fixed. 
Also made all page navigations scroll to the top (as they would if it wasn't a single page app) as it improves the usability.

Mobile tweaks/fixes

---

app/server/server.ts

since Fastly doesn't respect no-cache (https://docs.fastly.com/guides/tutorials/cache-control-tutorial#do-not-cache)

set Cache-Control back to private (to get master back to a safe state)

---

app/server/identity/identityMiddleware.ts

there was a missing return statement in https://github.com/guardian/manage-frontend/pull/139 which caused a NodeError where it was continuing to try send the normal response after already redirecting (fortunately didn't make it to PROD).

added missing return statement (corrects PR139)

---

cfn.yaml
riff-raff.yaml

Following https://github.com/guardian/amigo/pull/221, this PR now changes to use a dedicated 'manage-frontend' recipe in AMIgo, which specifies the exact Node version, which is now baked into the AMI. This allows us to remove the Node download/unpack step from instance start-up, which will **improve startup time** AND **improve stability**.

Use improved amigo node role (node baked into the AMI)

---

cfn.yaml

changed to new cert (which is referenced in Fastly) which follows the naming convention for PROD (and other apps CODE certs)

changed to new cert for CODE (which is referenced by new Fastly CODE configuration)

---

app/server/server.ts

https://docs.fastly.com/guides/tutorials/cache-control-tutorial#do-not-cache
> Fastly does not currently respect no-store or no-cache directives. Including either or both of these in a Cache-Control header has no effect on Fastly's caching decision, unless you alter this behaviour using custom VCL.
...and...
> The private directive does not prevent content from being cached in the browser. If you need to prevent caching by both Fastly and web browsers, we recommend combining the private directive with max-age=0 or no-store.
Given the above we need to set `Cache-Control` header to both `private` and `no-store` to prevent caching in BOTH the browser and on the CDN. The header value in this change covers all bases 😉

turned off all caching (for both Fastly CDN AND browsers)

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/__tests__/components/updatableAmount.ts
app/client/colours.ts
app/client/components/nav.tsx
app/client/components/payment/update/stripeCardInputForm.tsx
app/client/components/payment/update/updatePaymentFlow.tsx
app/client/components/productPage.tsx
app/client/components/redirectOnMeResponse.tsx
app/client/components/updatableAmount.tsx
app/client/components/userNav.tsx
app/client/styles/fonts.ts
app/server/server.ts
app/shared/productResponse.ts
app/shared/productTypes.tsx

Replicates and improves upon the contributions tab from profile.
NOW uses the bounds from https://github.com/guardian/support-frontend/blob/5aa237d/assets/helpers/contributions.js which differ based on currency and  frequency (monthly vs annual) and also has an improved 'sense check' where you are asked to double check if you increase your contribution by x10 (indicative of an accidental extra key press).
...or, if it fails...

Contributions Tab (parity with profile)

---

app/client/components/analytics.tsx
app/client/user.ts
app/globals.ts
app/package.json
app/types/ophan-tracker-js.d.ts
app/yarn.lock

adding ophan tracking using the dedicated `ophan.manage-my-account` tracking script (which now has support for client side routing - see https://github.com/guardian/ophan/pull/2979)

add ophan tracker js

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/buttons.tsx

Buttons used to have the focus highlight wrapping them once clicked, which was ugly/distracting for a short period of time until the desired action happened. Now only shows for actual focus (for keyboard navigation accessibility).
for example...

fixed annoying outline around buttons when clicked

---

app/package.json
app/yarn.lock

makes use of https://github.com/guardian/ophan/pull/3076

upgrade to latest ophan tracker-js (where ophan pageViewId issue is fixed)

---

app/client/components/analytics.tsx
app/globals.ts

When checking the 5XX alert email (not related, and resolved itself) I noticed the first page was being double counted after my hasty change last Friday (https://github.com/guardian/manage-frontend/pull/165)
The double counting is because an initial event is sent when the Ophan tracking script loads the page and then again with the usual 'page change'

prevented double-counting of initial page view in Ophan

---

app/server/__tests__/identity/identityMiddleware.ts
app/server/identity/identityMiddleware.ts

Introduced slight flaw in https://github.com/guardian/manage-frontend/pull/167, which this PR resolves.
Previously the /api/ url would be used for `?returnUrl=` rather than the page that was making the AJAX request, so now it uses the `referer` header for the `?returnUrl=` for /api/ endpoints. 
NOTE identity will not redirect to an unsafe `?returnUrl=` so no security alarm here.

fixed returnUrl issue in redirects for /api/

---

nginx/manage-frontend.conf

Much like https://github.com/guardian/members-data-api/pull/360
1. If you haven't already fetch the certs, download them (see hangouts chat message from Rupert on how/where to fetch).
2. Navigate to `./nginx` and run `./setup.sh`
3. `sudo nginx -s reload`

update gulocal cert reference for new 2020 cert

---

.prout.json
app/package.json
app/server/server.ts
app/webpack.common.js
app/yarn.lock

Adding [PROUT](https://github.com/guardian/prout) for this repo, so we can turn on continuous deployment.
- added prout configuration file (including CODE, to highlight changes which haven't been deployed to CODE first) 
- new `/_prout` endpoint which serves up the git commit hash of the build
- Gave @prout-bot write access to this repo... ![image](https://user-images.githubusercontent.com/19289579/51054383-99da9580-15d4-11e9-90d4-cdc34f3b88f6.png)
- Added webhooks... ![image](https://user-images.githubusercontent.com/19289579/51054319-6e57ab00-15d4-11e9-9924-189a592ddd96.png)
- Added post-deploy hooks... ![image](https://user-images.githubusercontent.com/19289579/51054801-d2c73a00-15d5-11e9-94c6-dbf2ad284e31.png)
- Turned on riff-raff continuous deployment... …

add prout 

---

.prout.json

...therefore isn't much use (may reinstate in future if there is another way to trigger PROUT on pushes prior to PR merge)
**_Follows closely on from https://github.com/guardian/manage-frontend/pull/172_**

PROUT: removed CODE checkpoint since it only fires after the PR is merged

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/nav.tsx
app/client/components/productPage.tsx
app/client/components/userNav.tsx
app/shared/productResponse.ts
app/shared/productTypes.tsx

Replicated the digipack tab from profile.theguardian.com. This required adding the following additional rows to the existing productPage implementation in `manage-frontend`:
- subscriber ID
- trial remaining
- subscription product
Global navigation and tabs within `manage-frontend` now point to the new tab.
_Changes to `frontend` to redirect traffic will follow soon._

Digipack tab parity

---

app/client/components/flowStartMultipleProductDetailHandler.tsx
app/client/components/productPage.tsx
app/client/components/updatableAmount.tsx
app/shared/productResponse.ts
app/shared/productTypes.tsx

Added configuration to enable payment update flow for Guardian Weekly and correctly handled the fact that the start date, next payment date and next payment price can be null.

Guardian weekly payment flow

---

app/server/server.ts

FIX: the redirect for sending the user to their comments management was behaving like an API endpoint and returning 401 when sign-in/reauth was required (poor user experience) - it now actually redirects them to sign-in/reauth first if needs be

FIX signin/reauth redirect when sending the user to their comments management section

---

app/server/server.ts

**will re-base once https://github.com/guardian/manage-frontend/pull/182 is merged** 
_Following some inspection of the client-side bundle (kicked off in https://github.com/guardian/manage-frontend/pull/182) noticed that we were NOT gzipping the client-side JS bundle._
Since its possible to configure Fastly to gzip JS assets (and others), this PR is just to make all `/static` assets cacheable (which includes the client-side JS bundle - `user.js`) which is a prerequisite for the following Fastly config changes...
...this leads to the following size/speed improvements for the client-side JS bundle download ( `user.js`)...
- 524KB ➡️148KB 🎉 
- 1330ms ➡️341ms ⏱ 
**This has lead to a significant improvement to the Lighthouse stats (audit tab in Chrome dev tools).** It's worth stating these are …

cache /static assets PLUS Fastly gzip assets

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/callCentreNumbers.tsx
app/client/components/cancel/caseCreationWrapper.tsx
app/client/components/cancel/stages/executeCancellation.tsx
app/client/components/flowStartMultipleProductDetailHandler.tsx
app/client/components/footer/in_page/questionsFooter.tsx
app/client/components/inlineContactUs.tsx
app/client/components/nav.tsx
app/client/components/noProduct.tsx
app/client/components/payment/update/confirmPaymentUpdate.tsx
app/client/components/payment/update/paymentUpdated.tsx
app/client/components/productPage.tsx
app/client/components/redirectOnMeResponse.tsx
app/client/components/updatableAmount.tsx
app/client/components/user.tsx
app/client/components/userNav.tsx
app/client/components/wizardRouterAdapter.tsx
app/package.json
app/server/server.ts
app/shared/__tests__/productTypes.ts
app/shared/meResponse.ts
app/shared/productResponse.ts
app/shared/productTypes.tsx
app/webpack.common.js

Created a grouped product type ('ContentSubscription' - see https://github.com/guardian/members-data-api/pull/366) which allows paper, weekly and digipack subscriptions to be displayed together in one tab.
Also relies on https://github.com/guardian/members-data-api/pull/367
Corresponding tab labels and global nav changes on the main website : https://github.com/guardian/frontend/pull/20991 (which should be deployed after this change)
- Mapped grouped product types back to the specific product where appropriate
- Disabled payment update flow for the grouped subscriptions
- Ensured that payment flows, etc for ContentSubscriptions always return back to /subscriptions
- Added functionality to display 'contact us' link when more than one subscription of paper or weekly is held, otherwise added …

combined 'Subscriptions' tab (Paper, Weekly & Digipack - not Membership or Contributions)

---

app/client/components/GoogleOptimiseAwaitFlagWrapper.tsx
app/client/components/analytics.tsx
app/client/components/payment/update/confirmPaymentUpdate.tsx
app/globals.ts
app/package.json
app/server/html.ts
app/server/server.ts
app/shared/globals.ts
app/shared/ophanTypes.ts
app/shared/productTypes.tsx
app/yarn.lock

To help D&I correlate payment update success/failure events (and theoretically other things) back to email campaigns (`CCX`, `PF1`, `PF2` etc. - denoted in the **`INTCMP`** query parameter) the initial  INTCMP value is now exposed as both...
- a GA dimension (already a defined dimension in GA - with index 12)
- in the `campaignCode` of the Ophan component event (which required refactoring in order to send these events with the correct structure)

expose initial INTCMP query arg as GA dimension and in Ophan component event action

---

app/server/identity/identityMiddleware.ts

Follows on from #177.
The work identity have been doing recently means that am auto sign-in token will soon be included in payment failure links in emails.
For payment failure links that send the user to the manage website, include the auto sign-in token in redirects to identity frontend so that the data can be utilised to facilitate user sign-in.
I've tested this locally by entering into the browser the url:
```
https://manage.thegulocal.com/payment/contributions?autoSignInToken=<auto-sign-in-token>
```

Include autoSignInToken query parameter in identity redirects

---

app/client/components/payment/update/confirmPaymentUpdate.tsx
app/client/components/payment/update/currentPaymentDetails.tsx
app/client/components/payment/update/updatePaymentFlow.tsx
app/client/components/productPage.tsx
app/shared/productResponse.ts

When a payment method is not correctly linked to a Zuora account _and_ the prerequisites for auto-cancellation are not met, it's possible for users to build up 'debts' whilst continuing to receive their subscription benefits. Currently many users in this bad state are unable to add a new payment method to fix the situation (which means that we cannot recover them easily). For other users, it _is_ possible to add a new payment method, but if they choose to do so this will inadvertently cause the payment for several invoices to be collected at once.
This PR allows us to use the updated response added by https://github.com/guardian/members-data-api/pull/370 to prevent unsafe payment method updates.
It also allows users without a correctly linked payment method to add a new payment card in …

Prevent payment method update in unsafe scenarios and allow users with no payment method to add card

---

app/client/colours.ts
app/client/components/cancel/cancellationFlow.tsx
app/client/components/checkbox.tsx
app/client/components/radioButton.tsx
app/client/components/updatableAmount.tsx

... to use new radioButton component in place of `<select>` for better UX on iOS.
| | Before `<select>` | After |
| --- | --- | --- |
| **iOS** |  😱 😱 😱 😱 😱 😱😱 😱  ![image](https://user-images.githubusercontent.com/15648334/53035598-bd172100-346d-11e9-98d5-c2fd8f3c4a31.png)  | ![image](https://user-images.githubusercontent.com/15648334/53035693-eafc6580-346d-11e9-9b8f-c5c0b1ec306c.png) |
| **Desktop** | ![image](https://user-images.githubusercontent.com/15648334/53035545-9bb63500-346d-11e9-911b-60301ad6988b.png) | ![image](https://user-images.githubusercontent.com/15648334/53035780-1ed78b00-346e-11e9-8222-9a85ef3a8be5.png) |

Change cancellation reason picker

---

app/client/components/analytics.tsx
app/server/identity/identityMiddleware.ts
app/shared/globals.ts
app/shared/ophanTypes.ts

When a user lands on manage from an external link, store the information of the ab test they were in (if applicable) so that it can be included on all component events sent by manage. Additionally, include the ab test data as query parameters if the user if kicked to manage (so that sign-in success can be measured across test variants).
With this PR, there are now 5 query parameters that are getting included (if present) if the user gets redirected to profile. So additionally this PR handles the inclusion of those query parameters in a more general manner.

Add functionality to AB test user journeys on manage.

---

app/package.json
sonar-project.properties

- Disable code coverage - since it can't read coverage correctly and it was failing default 'Quality Gate'
- Use git commit hash as project version - for better traceability, rather than default/fixed `1.0`
_Co-authored-by: Tom Richards <tom.richards@guardian.co.uk>_

Update Sonar config

---

app/client/components/flowStartMultipleProductDetailHandler.tsx
app/client/components/payment/update/paymentUpdated.tsx
app/client/components/productPage.tsx
app/client/components/updatableAmount.tsx
app/shared/productResponse.ts
app/shared/productTypes.tsx

Various improvements with the main underlying goal of ensuring is price rise is displayed correctly (once the API says it can be displayed, see https://github.com/guardian/members-data-api/pull/371).
_(rather than using join date as potentially misleading fallback or indeed showing both)_
_(i.e. if `shouldBeVisible` is true - see https://github.com/guardian/members-data-api/pull/371)_
Including in the "Six for Six" scenario...

improve display of physical subs

---

app/server/identity/identityMiddleware.ts

#199 removed sign-in query parameters from manage urls on the event of the user getting redirected to profile to sign-in (they were removed from the return url).
This PR builds on that work: if the user isn't redirected to profile because they are already signed in, they are redirected to the same manage url modulo the sign-in query parameters being removed.
There is a comment in the code explaining the motivation behind this, but to re-iterate: we want to remove sign-in query parameters since we don't want them to be captured by Google Analytics or Ophan, since the data they hold is sensitive.

Remove sign-in query parameters from manage url

---

app/shared/productResponse.ts

following https://github.com/guardian/members-data-api/pull/374 'currentPlans' and 'futurePlans' can both be empty (which will be resolved in future) this change just uses the old 'plan' field as a fallback

TEMP FIX - stop client-side crash for friends following members-data-api/pull/374

---

app/client/components/productPage.tsx
app/shared/productResponse.ts

The rate plan on Friend memberships ends the day after start date and thus `currentPlans` AND `futurePlans` arrays are empty, which needs to be handled.
The temporary FIX https://github.com/guardian/manage-frontend/pull/202 simply fell back to the old `plan` field in this scenario, however we want to remove that field soon and so this PR is a proper fix which builds a basic plan object to return so all the rendering works.

refactored out the fallback to old 'plan' field in the event of no plans (e.g. Friends)

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/roundel.tsx
app/client/components/userNav.tsx

The 'My account' button was not accessible by keyboard, so users of keyboard navigation and/or screen readers were unable to access the menu. 
The 'My Account button' and dropdown menu now meet the following accessibility requirements:
- Button is accessible by Tab key
- Menu opens/closes with Enter/Space keys
- Menu closes when Escape key is pressed and focus returns to 'My Account' button
- Menu closes when user clicks outside the menu
A mixture of semantic HTML markup and ARIA roles were used to achieve this.
The roundel was also updated with a friendly text description to match Frontend and help screen reader users (previously the URL was read out).

Make 'My account' button keyboard and screen-reader accessible

---

app/client/components/payment/update/updatePaymentFlow.tsx
app/shared/productResponse.ts

_Missing_ payment details were being treated as 'free' in the payment update flow and the user was therefore presented with a 'Support The Guardian' messaging accordingly, which is wrong. Missing payment details are now handled correctly with a new Sentry error if this ever occurs (which it shouldn't happen anymore based on below).
However due to the internals of `members-data-api` (fixed in https://github.com/guardian/membership-common/pull/593 and https://github.com/guardian/members-data-api/pull/378) previously the payment details weren't being exposed at all and thus `manage-frontend` didn't know what form to display.

correctly handle no payment method and alert if not a free sub

---

cfn.yaml

Migrate manage site to t3 instance types in preparation for AWS reservations.

Migrate manage site to t3 instance types

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/footer/footer.tsx
app/client/components/membershipFAQs.tsx
app/client/components/supportTheGuardianButton.tsx

This replaces the INTCMP as it can provide more granular information and ensures correct attribution (for example in the 'Acquisitions Slicer').
Also refactored everything that links to 'support' to use this class/function.
See the URL when hovering over the Contribute button for example...

now builds and sends 'acquisitionData' query param when linking to 'support'

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/cancel/cancellationSummary.tsx
app/client/components/checkFlowIsValid.tsx
app/client/components/flowStartMultipleProductDetailHandler.tsx
app/client/components/noProduct.tsx
app/client/components/productPage.tsx
app/client/components/resubscribeThrasher.tsx
app/client/components/supportTheGuardianButton.tsx
app/server/server.ts

Following the launch of https://github.com/guardian/support-frontend/pull/1673 it's now time to start sending some traffic there  🚀 
This change adds a bright yellow 'thrasher' in-place of the lightweight Support The Guardian messaging that is used in the cancellation summary and 'no product' page... to encourage re-subscribe, providing...
- The user has eligible payment methods (based on existing-payment-methods response from `members-data-api` - see https://github.com/guardian/members-data-api/pull/376)
- The user doesn't already have an active recurring contribution (inferred from the subscriptions listed in the existing-payment-methods response)
... otherwise it will fall back to using the lightweight Support The Guardian messaging.
_NOTE: the 'displayExistingPaymentOptions=true' …

resubscribe thrasher (aka existing payment methods)

---

app/client/components/resubscribeThrasher.tsx

As discussed with @jacobwinch, until reuse of direct debit is implemented in `support-workers` and then enabled via support-admin-console (and thus support-frontend), filter only on 'Card' when deciding whether to show the yellow  resubscribe thrasher (see https://github.com/guardian/manage-frontend/pull/210) - to avoid promising people that they can use existing payment method when in reality they could not.
_We expect to revert this in 3 or 4 weeks when we get round to implementing the underlying functionality._

temporarily disable DirectDebit payment methods alone from triggering the yellow resubscribe thrasher

---

app/server/identity/identityMiddleware.ts

Additional text is being added to sign in pages for the payment failure journey to ensure that a user retains context throughout the journey. [https://github.com/guardian/identity-frontend/pull/524](url)
The parameter than determines whether this text is shown or not will be passed to manage from the payment failure emails, this change ensures that it is carried over in the redirect to /signin.

Add "journey" to query parameters for identity redirects

---

app/server/identity/identityMiddleware.ts
app/server/server.ts
app/shared/identity.ts
app/shared/meResponse.ts
app/shared/productTypes.tsx

_Follows on from https://github.com/guardian/manage-frontend/pull/213 ✅_
Some tweaks following changes to https://github.com/guardian/identity/pull/1527 
ALSO in preparation for https://github.com/guardian/members-data-api/pull/384 ensure the new `X-GU-IDAPI-Redirect` header from members-data-api which now accompanies 401s, is used to build the `Location` header for the final 401 response which will trigger a client-side redirect to signin/reauth AND that `X_GU_ID_FORWARDED_SCOPE` header is passed on to `members-data-api` when used in a scoped context.

Tweaks to IDAPI integration ready for their PR.

---

app/package.json
app/shared/productResponse.ts
app/yarn.lock

snyk is complaining about 
>Arbitrary Code Execution
Vulnerable module: js-yaml
Introduced through: @emotion/core@10.0.7 and @emotion/styled@10.0.7
Detailed paths and remediation
Introduced through: manage-frontend@1.0.0 › @emotion/core@10.0.7 › @emotion/css@10.0.7 › babel-plugin-emotion@10.0.7 › babel-plugin-macros@2.4.5 › cosmiconfig@5.0.7 › js-yaml@3.12.1
Remediation: Your dependencies are out of date, otherwise you would be using a newer js-yaml than js-yaml@3.12.1. Try reinstalling your dependencies. If the problem persists, one of your dependencies may be bundling outdated modules.
Introduced through: manage-frontend@1.0.0 › @emotion/styled@10.0.7 › babel-plugin-emotion@10.0.7 › babel-plugin-macros@2.4.5 › cosmiconfig@5.0.7 › js-yaml@3.12.1
Remediation: Your dependencies are out of …

update package.json dependencies to remove synk error

---

app/client/components/payment/update/confirmPaymentUpdate.tsx
app/client/components/resubscribeThrasher.tsx
app/server/identity/identityMiddleware.ts

The 'X_GU_ID_FORWARDED_SCOPE' header is integral to the 'auto sign-in tokens' (aka magic links) for the payment update flow (following CC Expiry, Direct Debit Mandate Failure and Payment Failure emails), see...
- https://github.com/guardian/identity/pull/1527
- https://github.com/guardian/members-data-api/pull/384
- https://github.com/guardian/identity-processes/pull/23
While end-to-end testing there were a few outstanding cases uncovered, where this header wasn't being passed when it should.

cleaned up last few instances where 'X_GU_ID_FORWARDED_SCOPE' header wasn't being passed

---

cfn.yaml

As part of reconfiguring the Membership VPC to have public & private subnets, I'm going to placing load balancers in the public subnet and instances in the private subnet, as per best security practices. (The original motivation for this was to give [lambdas access to the internet as well as entities within the VPC](https://aws.amazon.com/premiumsupport/knowledge-center/internet-access-lambda-function/), but having a subnet which is unreachable from the internet has other security benefits too, and is in fact how the Subscriptions VPC is set up.)
As a first step for this, I need to separate out these params in CloudFormation for all of our apps. I'll need to manually upload the new CloudFormation in the console because I need to supply values for these params. When I do this, I'll leave …

Separate public/private subnets

---

app/client/components/resubscribeThrasher.tsx

Now that re-use of existing direct debit is implemented in `support-workers` (see https://github.com/guardian/support-frontend/pull/1772) we can now revert https://github.com/guardian/manage-frontend/pull/211, so the existing direct debit details will trigger the yellow re-subscribe thrasher on manage.theguardian.com.

Revert "temporarily disable DirectDebit payment methods alone from triggering the yellow resubscribe thrasher"

---

app/client/colours.ts
app/client/components/analytics.tsx
app/client/components/buttons.tsx
app/client/components/consent/consentsBanner.tsx
app/client/components/user.tsx

- Displays only if **`GU_TK`** cookie is NOT present
- The `I'm OK with that` button writes the cookie on the parent domain, i.e. not `manage` sub-domain
- Fairly similar to https://github.com/guardian/support-frontend/pull/1677
- Uses another top-level `<Router>` instance in `user.tsx` to cleanly prevent the banner on the payment flow.
_Also required additions to `<Button>` component (to display the ✔️) plus some tweaks/corrections to the shared colour palette (although this file should be refactored in a future PR to exactly match https://design.theguardian.com/#colour-palette)._

consent banner

---

app/server/awsIntegration.ts
app/server/holidayStopApiConfig.ts
app/server/holidayStopApiHandlers.ts
app/server/idapiConfig.ts
app/server/middleware/identityMiddleware.ts
app/server/routes/products.ts
app/server/routes/profile.ts
app/server/server.ts
app/shared/productTypes.tsx
app/types/express-with-identity.d.ts

The API sits behind an API Gateway, which requires...
- an `x-api-key` header, the value for which is fetched from a new config file along with the `host` (this differs obviously for each stage). Loading another config file from S3 warranted some refactoring/abstraction of this mechanism, so it's now much cleaner (and along the way found a way to use the `AWS.CredentialProviderChain` rather than overriding `AWS_PROFILE` environment variable, which is lovely - see https://github.com/guardian/dotcom-rendering/issues/575 for more info).
- and an `x-identity-id` header, the value for which was already coming back from the IDAPI call it makes before every request (due to `withIdentity()`) but this needed exposing to subsequent request handler, which is now achieved via …

holiday-stop-api integration

---

app/client/components/buttons.tsx

On IE 11 the accept cookies button is unusually large:  
By setting the height to a fixed value it prevents the bug:
* Give tick svg a fixed height in `leftTick` `Button` variant.

Fix huge consent button on IE11

---

cfn.yaml

These are in the private subnet now so a public IP address is useless

No public IP address for instances

---

app/client/components/payment/update/updatePaymentFlow.tsx
app/package.json
app/server/routes/frontend.ts
app/shared/globals.ts
app/types/express-with-identity.d.ts
app/yarn.lock

(as this being deprecated/decommed and was a nasty long-standing TODO) 
instead using the `email` provided by the IDAPI `/redirect` endpoint response (`email` field added in https://github.com/guardian/identity/pull/1579)

eliminated reliance on GU_SIGNIN_EMAIL cookie 

---

app/client/components/identity/idapi/user.ts

It is possible for a user to have no consent information, we suspect these are users using a legacy setup. IDAPI will return no consent information. The moment they submit a consent option, their consent information will be created for them and they will be able to carry on as usual.

Fix missing consents bug on Email and Marketing tab

---

app/client/components/payment/update/card/cardInputForm.tsx
app/server/html.ts

If the user had navigated from one of the product pages into the respective payment update flow (i.e. it was instantly passing the productDetail via the browser history state rather than loading again from members-data-api) then if the user reloaded that page it wouldn't have loaded Stripe.js in time and would throw a `window.Stripe is not a function` error.
Fairly rare in production but happened occasionally...
**Now**, it no longer loads the Stripe.js as `async` in the main html template, and instead only loads it dynamically when the card input form is added (which reduces unnecessary downloads for many user journeys 🎉), **the card input form now shows as loading until it has both loaded and initialised Stripe.**
_NOTE: this was extracted from …

FIX undefined window.Stripe for certain reloads of page 1 of payment update flow

---

app/client/components/flowStartMultipleProductDetailHandler.tsx

The `FlowStartMultipleProductDetailHandler` component wraps all multi-step flows (e.g. payment update flow, cancellation flow, holiday-stops flow), it's purpose is to handle scenarios where people have multiple subscriptions of the same type of product and present them with a flow-specific way of selecting the right subscription. If a user navigates from one of the product pages then we already use the [browser history state](https://developer.mozilla.org/en-US/docs/Web/API/History/state) to avoid the user waiting to load the same data again from `members-data-api` however if the user comes to a flow directly (say from a payment failure email) and they have multiple subscriptions of the same type of product then they see the options.
When working on …

FIX redundant call to members-data-api from the 'flow start component'

---

app/package.json
app/server/html.ts
app/server/routes/frontend.ts
app/shared/globals.ts
app/types/browserslist-useragent.d.ts
app/yarn.lock

A **long time back** we added `browserslist-useragent` dependency in-order to be able to interpret our '[browserlist](https://browserl.ist/)' config (in the `package.json` and used by 'babel') and use it at runtime (server-side) to compare against the `User-Agent`, so we could present an 'unsupported browser' banner accordingly - see - see https://github.com/guardian/manage-frontend/pull/101.
Shortly after we observed some mistaken displays of this banner on browsers which were actually supported, so we added some logging (https://github.com/guardian/manage-frontend/pull/102) but ultimately disabled the banner by forcing the `supportedBrowser` boolean to true (https://github.com/guardian/manage-frontend/pull/104) leaving the logging in place to see if we could figure out a pattern to the …

remove "browserslist-useragent" since we're not really making proper use of it

---

app/client/components/consent/Cookie.tsx
app/client/components/consent/PrivacySettings.tsx

CMP UI now reads the IAB cookie and updates its state accordingly on load.
This allows up to show the user's choices when resurfacing the UI.

Read IAB cookie from CMP UI

---

app/client/components/consent/PrivacySettings.tsx
app/client/consent.tsx
app/server/consent/html.ts
app/server/routes/consent.ts
app/shared/globals.ts

This PR enables raven/sentry error capturing on the CMP UI. The implementation is largely based upon the technique used elsewhere in `manage-frontend`.

Enable raven/sentry on the CMP UI

---

app/client/components/consent/PrivacySettings.tsx
app/server/consent/html.ts

This PR introduces a new post message emitted from the CMP UI to notify it's `window.parent` consent has been saved. The module [lib/cmp.js](https://github.com/guardian/frontend/blob/master/static/src/javascripts/lib/cmp.js) that currently lives in frontend will listen for this message and upon receiving it will execute any callbacks that have been scheduled to execute when consent changes.
The corresponding PR that handles these events is here: https://github.com/guardian/frontend/pull/21766

Send message from CMP UI to notify parent consent has been saved

---

app/client/components/consent/PrivacySettings.tsx

The way we exposed the new link so that it's available from other domains had to be temporarily reverted so we're going back to the previous link as well.

Revert vendorlist link

---

app/tslint.json

Added the `no-empty-interface` tslint rule that prevents using a type/interface that's hasn't been declared. Before it would silently assume type `any`. Now it'll throw an error instead.

Added no-empty-interface tslint rule

---

app/client/components/productPage.tsx

This PR displays the entry button into the holiday stops flow for Guardian Weekly, on the subscriptions tab, for approx 10% of users 🚀.
This approx 10% is determined by the users identity ID, specifically if their identity ID ends in `2`. Using this approach for canary release is to ensure that the same customers who initially see this functionality always have access to it, including across devices - which isn't guaranteed when using other approaches.
Main PR - https://github.com/guardian/manage-frontend/pull/227
Responsiveness PR - https://github.com/guardian/manage-frontend/pull/267

canary launch GW holiday stops to  approx. 10% of users (based on their identity ID)

---

app/client/components/productPage.tsx

Follows on from
- 10% canary release - https://github.com/guardian/manage-frontend/pull/266
- 50% canary release - https://github.com/guardian/manage-frontend/pull/270
This PR removes all that canary percentage logic and also the URL parameter since there's no point in that now.

remove canary percentage logic for GW Holiday Stops CTA (i.e. release 💯%)

---

app/server/server.ts

This PR updates the `content-security-policy` for the `/consent` route to allow it to be iframed in from sites running on `localhost` and `thegulocal` when `manage-fromtend` is running on `CODE`.
We're doing this so developers running `frontend` locally don't have to have `manage-frontend` running locally to see a CMP UI.

allow frame ancestors from localhost and thegulocal when CODE

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/nav.tsx
app/client/components/userNav.tsx

Partially release #239 to audience. Users will only be able to access the new tab via indirect navigation, i.e. navigating to another manage.guardian tab and then navigating to the public profile tab
* #239

Activate Profile Tab Migration Test

---

app/client/components/holiday/holidayDateChooser.tsx
app/client/components/holiday/holidayStopApi.ts
app/client/components/holiday/holidaysOverview.tsx
app/server/holidayStopApiHandlers.ts

Refactor to call V2 of the `/potential` endpoint of `holiday-stop-api` which now takes subscription name as a path parameter. This enables the transitionary code & naming in that lambda to be eliminated (see https://github.com/guardian/support-service-lambdas/pull/413).
PLUS couple of quick tweaks...
- replaced instances of `map()` followed by `flat()`, with `flatMap()` - for better browser compatibility
- minor UI tweak for /potential spinner on larger mobiles to prevent jank

holiday-stops: use V2 /potential endpoint of holiday-stop-api

---

app/client/components/holiday/holidayConfirmed.tsx
app/client/components/holiday/holidayDateChooser.tsx
app/client/components/holiday/holidayReview.tsx
app/client/components/holiday/holidayStopApi.ts
app/client/components/holiday/holidaysOverview.tsx
app/client/components/holiday/summaryTable.tsx

Had to move a fair bit of code around and instead of passing around arrays of `string`/`Moment`, pass around objects which contain `publicationDate` and optionally `estimatedCredit`. 
Also involved creating `PotentialHolidayStopsAsyncLoader` for the Review Screen now that it needs to call `/potential` endpoint passing `&estimateCredit=true`. The results of which are displayed on both the Review Screen AND make their way to the Confirmed Screen, by overriding the `SharedHolidayDateChooserState` object by inserting a new `<HolidayDateChooserStateContext.Provider>` in the DOM with the `publicationDate` swapped out for the ones including the estimated credit (from the the /potential endpoint).
Now displays estimated (or indeed actual) credit on the overview screen (from what's stored in …

holiday stops : self-serve : estimated credits

---

app/client/components/identity/PublicProfile/AvatarSection.tsx
app/client/components/identity/idapi/avatar.ts
app/client/components/identity/models.ts

The Avatar api returns a 404 error when a user has not set an Avatar. This legitimate response should not be logged to Sentry. This Fix makes the Avatar form error handler ignore this type of error when dispatching to Sentry.
* Add a `NOT_FOUND` error type.
* IDAPI `avatar` adapter will now return the `NOT_FOUND` error type specifically on Avatar not found responses.
* `PublicProfile/AvatarSection` will not log `NOT_FOUND` errors returned during an Avatar api transaction.

Fix: Prevent unnecessary Avatar 404 logging

---

app/client/components/consent/PrivacySettings.tsx

Change the links in the CMP UI so that they open new tabs instead of opening within the CMP iFrame.

Change links in the CMP UI to open in new tabs

---

app/client/components/consent/PrivacySettings.tsx
app/server/server.ts

The `scrollToPurposes` function was buggy on mobile devices, to fix this we've refactored the function so we check whether the scrollable container has scrolled the maximum it can, and if so we kill the `requsetAnimationFrame` cycle.

Fix scrollToPurposes bugs

---

app/server/server.ts

The PR https://github.com/guardian/manage-frontend/pull/254 updated the `/consent` route to allow it to be iframed in from Guardian domains. This has been working when we've been testing on our desktop browsers/operating systems, however when cross browser testing using Safari on iOS we found the `X-Frame-Options` header that's added by the express security middleware `helmetjs` was preventing the `/consent` route from loading in an iframe.  The error we'd see in the console was: `Refused to display 'https://manage.theguardian.com/consent' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.`
This PR updates the `/consent` route only so the `X-Frame-Options` header is not included. This  was the best course of action we could take as you can't allow `X-Frame-Options` to take …

Remove X-Frame-Options from /consent route

---

app/client/components/consent/ConsentMangementPortal.tsx
app/client/components/consent/PrivacySettings.tsx

On iOS the height of the iframe that contains the CMP UI always grows to match the content of the CMP UI, this is a problem as it breaks the positioning of all sticky elements  (eg. the buttons which we want to be visible on the initial impression are no longer visible).
To overcome this we introduce a containing `div` in the CMP UI that wraps all the content, we refer to this as the "scrollable". The scrollable has a height set to `100vh`, which tricks iOS into keeping the iframe that contains the CMP UI to be 100% viewport height too. 
We've then had to add the CSS rule `overflow-y: scroll;` to the scrollable so users can scroll this area. This works on mobile, but you don't get any smooth "momentum scrolling". In order to achieve this momentum scrolling this PR adds the CSS rule …

CMP UI - scroll enhancement

---

app/server/consent/html.ts

An arrow function exists in the the `<head>` of the CMP UI, as expected this causes errors on older browsers that don't support this JS feature, replacing with a standard function fixes this.

CMP UI - IE fix

---

app/server/routes/products.ts
app/shared/productTypes.tsx

- Update the 'friendly name' for digipack in the `productTypes.tsx` to remove the 'pack' keyword, which is used in for example the heading of the payment flow SO now it looks like...
- provide an alternate value for 'tier' on the digipack product to ensure we show 'Digital Subscription' (rather than 'Digital Pack', _which is provided by `members-data-api`_) SO now it looks like...
- introduced 🆕 optional field `legacyUrlPart` on `ProductType` interface, and defined if for digipack as "digitalpack" and changed the `urlPart` to just "digital" 
- added blanket server-side redirect mechanism to replace the `legacyUrlPart` within any URL with the `urlPart`, _for example `/payment/digitalpack` ... redirects to ... `/payment/digital`_
https://github.com/guardian/members-data-api/pull/410

'digital pack' -> 'digital subscription'

---

app/client/components/consent/App.tsx
app/client/components/consent/ConsentMangementPortal.tsx
app/client/components/consent/PrivacySettings.tsx

Because we load the CMP UI within an iframe from the righthand side of theguardian.com you get 2 scrollbars positioned side by side, one for the iframe scrollable area and one for the parent site. To overcome this we can position the content of the iframe to take into account the scrollbar and hide it. We do this with JavaScript by calculating the `scrollbarWidth`.

CMP UI - hide scroll bar

---

app/client/consent.tsx

Sentry has been reporting Invariant Violation errors ("Target container is not a DOM element") which we believe are being caused by calling `document.getElementById("app")` inside `run()` before the body is parsed.
Despite not being able to recreate the issue locally we believe this change will fix it.
Tested locally and on CODE to make sure there are no adverse effects.

Fix Invariant Violation error

---

app/shared/productTypes.tsx

This PR introduces two _new_ product types `voucher` and `homedelivery` - previously these were grouped under 'newspaper' (which still remains until Braze email templates are updated).

split 'paper' into 'voucher' and 'homedelivery'

---

app/client/components/holiday/holidayDateChooser.tsx
app/client/components/holiday/holidayReview.tsx
app/client/components/holiday/holidayStopApi.ts
app/client/components/holiday/holidaysOverview.tsx
app/package.json
app/server/holidayStopApiHandlers.ts
app/server/routes/products.ts
app/shared/productTypes.tsx

Following https://github.com/guardian/support-service-lambdas/pull/456, the `holiday-stop-api` uses the subscription name that was already part of all of the URLs to determine the product variant, rather than relying on headers or query params.
**This PR simplifies the calling logic and reads the new response structures.**

refactor to use cleaned/simplified version of 'holiday-stops-api'

---

app/client/components/datePicker.tsx
app/client/components/hackedDateRangePicker.tsx
app/client/components/holiday/holidayAnniversaryDateExplainerModal.tsx
app/client/components/holiday/holidayConfirmed.tsx
app/client/components/holiday/holidayDateChooser.tsx
app/client/components/holiday/holidayQuestionsModal.tsx
app/client/components/holiday/holidayReview.tsx
app/client/components/holiday/holidayStopApi.ts
app/client/components/holiday/holidaysOverview.tsx
app/client/components/user.tsx
app/shared/productTypes.tsx

- Added configuration for voucher holiday stops flow and made all the steps use the product specific keywords and copy where they were hardcoded before.
- Made the date chooser support multiple 'Issue Day' indicators ('Voucher Day' in this scenario)
- Added a confirmation checkbox for this voucher flow only, where 'Confirm' is disabled until this is checked _(Guardian Weekly remains unaffected)_...
... with modal for more info ...
<hr/>
_Using copy explained in https://docs.google.com/presentation/d/1d4wHdkZ-HFQY8rtoVjJD67dI3z0e4YVoDQq-Bt_DXZo with help text from https://docs.google.com/presentation/d/1c0hSAKxvELw_oX2w1Uu5r7H-f_tbhfLTfTwbG0hWLfQ_

Self-Serve Voucher holiday stops

---

app/client/components/holiday/holidayQuestionsModal.tsx
app/shared/productTypes.tsx

This PR hides the selected text below for the voucher holiday stop flow...

hide 'delivery redirection' bullet point in help modal on voucher flow

---

app/client/components/holiday/holidayConfirmed.tsx
app/client/components/holiday/holidayReview.tsx
app/client/components/holiday/holidayStopApi.ts
app/client/components/holiday/holidaysOverview.tsx
app/client/components/holiday/summaryTable.tsx

replaced one remaining instance of hardcoded "issue" with the dynamic product-specific `issueKeyword` (which was missed in the main voucher holiday stops PR)

replace hardcoded "issue" with the dynamic product-specific 'issueKeyword'

---

app/client/components/holiday/holidaysOverview.tsx

Noticed this class would be better using the `children` '_render props pattern_' (see https://reactjs.org/docs/render-props.html#using-props-other-than-render)

Refactor holiday stops overview row

---

app/package.json

The 'parallelisation' attempted in https://github.com/guardian/manage-frontend/blame/b5675a3c/app/package.json#L27 was in-fact forking/backgrounding the `type-check' and 'lint' steps, allowing the pre-commit hook to pass even if there were problems - not ideal.
To achieve actual  'parallelisation' would require something like https://stackoverflow.com/questions/356100/how-to-wait-in-bash-for-several-subprocesses-to-finish-and-return-exit-code-0

de-parallelise the 'pre-commit' hook

---

app/client/components/holiday/collatedCredits.tsx
app/client/components/holiday/holidayStopApi.ts
app/client/components/holiday/holidaysOverview.tsx
app/client/components/holiday/summaryTable.tsx

- ✅ https://github.com/guardian/support-service-lambdas/pull/461
- ✅ https://github.com/guardian/manage-frontend/pull/308
- ✅ https://github.com/guardian/manage-frontend/pull/307
- ✅ https://github.com/guardian/support-service-lambdas/pull/462
- ✅ https://github.com/guardian/manage-frontend/pull/310
- Introduced new `CollatedCredits` component, which aggregates credits by 'invoice date'.
- `CollatedCredits` is used on the overview screen (aggregating across ALL existing holiday stops) and in the SummaryTable (on Review and Confirmed screens only) to show the collated credits for just the new holiday stop request. 
- IMPORTANT: Invoice date and credit amount (estimated or actual) MUST be present on all the publications - otherwise it will display _"Unavailable at this time."_
_There is …

Display holiday credit invoice dates

---

app/client/components/consent/OnOffRadio.tsx
app/client/components/consent/PrivacySettings.tsx

This PR fixes 2 bugs that were showing up in Safari on iOS:
- Buttons with SVGs as children would render below their expected position. (how: Increased the `line-height` on buttons to make sure they stay in the same position)
- Radio buttons get squashed to the side (how: added `flex-shrink: 0` on the container around the radio buttons) 
Before:
After:

Fix UI glitches for Safari on iOS 6

---

app/client/components/callCentreNumbers.tsx

PR to update the opening times of the contact centre in the USA & Canada as it is now open from 9 to 5 rather than 9:15 to 6pm
A similar PR is there to update the old subscribe.../manage (https://github.com/guardian/subscriptions-frontend/pull/1284)

Update contact centre opening times for USA & Canada

---

app/client/components/consent/App.tsx
app/client/components/consent/ConsentMangementPortal.tsx
app/client/components/consent/PrivacySettings.tsx
app/client/consent.tsx
app/package.json
app/server/routes/consent.ts
app/shared/globals.ts
app/yarn.lock

We need to be able to A/B test the new CMP UI. Whilst we continue to use the `iframe` we propose that we use the A/B test framework on frontend and notify the CMP UI of the variant the user is in via a query string parameter:`?abTestVariant=CmpUiNonDismissable-variant`.
The value of `abTestVariant` is in the format _TestId_-_VariantId_, we're padding a single string around as this string is eventually sent in the data we post to the consent logs which expects a single string in this format as appose to an Object such as `{ testId: "CmpUiNonDismissable", variantId: "variant" }`
We notify the `<App>` component of the variant by passing it down as a prop `abTestVariant` when we initialise it.If this is `abTestVariant` query string parameter isn't we set the default value of the …

CMP UI - New CMP UI A/B test without cancel button

---

app/client/components/hackedDateRangePicker.tsx

As per Sentry `/create` is breaking on IE and Mobile Safari...
_17 instances of this_
... 🙈

polyfill Number.isInteger (which is used in 'react-daterange-picker') for IE11 & Mobile Safari 8

---

app/client/components/dateInput.tsx
app/client/components/datePicker.tsx
app/client/components/hackedDateRangePicker.tsx
app/client/components/holiday/existingHolidayStopActions.tsx
app/client/components/holiday/holidayDateChooser.tsx
app/client/components/holiday/holidayReview.tsx
app/client/components/holiday/holidayStopApi.ts
app/client/components/holiday/holidaysOverview.tsx
app/client/components/holiday/summaryTable.tsx
app/client/components/user.tsx

This PR follows on from https://github.com/guardian/manage-frontend/pull/312 but adds the ability to **amend** existing holiday stop requests.
This makes further use of the `mutabilityFlags` from `holiday-stop-api` (introduced in https://github.com/guardian/support-service-lambdas/pull/463) to determine whether to show an **`Amend`** button or an **`Amend end date`** button or indeed no amend related button (for when it's too late to change the holiday stop request in any way).
This displays if `mutabilityFlags.isFullyMutable` is `true`.
If the user clicks it, this sets a new optional property (`existingHolidayStopToAmend`) of the `ReloadableGetHolidayStopsResponse` which is available to all the steps of the flow via the existing `HolidayStopsResponseContext` with the full detail of that …

'amend' holiday stop feature

---

app/client/components/holiday/holidaysOverview.tsx

...with explainer message, although if there are any existing then it still displays those (we know of approx. 20 non-auto-renewing subs where users created holiday stops via self-service prior to this change).
|  ...with existing holiday stops | ...without existing holiday stops | 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/19289579/68779707-05462700-062d-11ea-9798-e77b24fd28a8.png) | ![image](https://user-images.githubusercontent.com/19289579/68779979-708ff900-062d-11ea-9ab1-2a220a3ed65d.png) |
... **NOTE**
- subtly different explainer ("cannot" vs "can no longer")
- no `Create Suspension` button on either

prevent creation of holiday stops on non-auto-renewing subs

---

app/client/components/cancel/cancellationFlow.tsx
app/client/components/flowStartMultipleProductDetailHandler.tsx
app/client/components/holiday/holidaysOverview.tsx
app/client/components/payment/update/updatePaymentFlow.tsx

If customers have multiple subscriptions of a given type (e.g. `guardianweekly`) and they enter any of the flows directly (for example enter the holiday stops flow direct from an email or FAQ page) then they're presented with a list of subs of that type so they can select the one they want to proceed with. _Note that if they come from the product tab (e.g. subscriptions) then it uses the 'browser history state' to denote the desired one to proceed with._
**Previously, 'cancelled' subs would be filtered out of this list**, likewise if the customer had just one subscription of that type which was cancelled and entered the flow directly they would just see the generic `NoProduct` page (which states for example `You do not currently have a newspaper voucher subscription.`) which is kind of …

better message(s) when users go direct to a flow on a cancelled sub

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/buttons.tsx

This PR fixes a regression introduced in https://github.com/guardian/manage-frontend/pull/267 - that was a hectic time.
Prior to the above regression the Button component had a `line-height` to make it work on IE (see https://github.com/guardian/manage-frontend/commit/3de4285451aebf9040d20868e1f644ca268f06b0#diff-5afa62adc28365a0ece2481e3bc1a7afL122 specifically). However that made the wrapping quite funky and so it was phased out in the above commit.
In order to fix the regression it now specifies the `height` as well as the `min-height` which allows the `align-items: center` to actually work... because IE 🙈(see https://github.com/philipwalton/flexbugs/issues/231).
_This is a better solution than using `line-height` due to its effect on wrapping buttons with long labels._
| During …

fixed internal button padding on IE

---

app/client/components/productPage.tsx

Follows on from https://github.com/guardian/manage-frontend/pull/319 - this hides holiday stops row on product page for to avoid disappointment when they then find out holiday stops are not supported for non-auto renewing subs.

hide holiday stops row on product page for non-auto renewing subs

---

app/client/components/productPage.tsx

Given we're now selling new types of one-off gift subs (see https://github.com/guardian/support-frontend/pull/2188) we need to hide the following nastiness...
...the red rows do not make sense for these new one-offs.

hide "Next payment date" and 'next payment' rows for one-off subs

---

app/client/components/holiday/holidayReview.tsx
app/client/components/holiday/holidayStopApi.ts

renames `start` -> `startDate` and `end` -> `endDate` in a number of places following https://github.com/guardian/support-service-lambdas/pull/495

rename payload keys to not use Salesforce reserved keywords

---

app/client/components/flowStartMultipleProductDetailHandler.tsx
app/client/components/nav.tsx
app/client/components/page.tsx

`maxWidth` was removed from the `PageContainer` component in https://github.com/guardian/manage-frontend/pull/324... which made the flows (e.g. payment, holiday stops, cancellation) go full width ... so added `maxWidth` back in.
`PageContainer` will be phased out in future once the flows use the grid and final design.s

Fix visual regression on userflows (layouts that don't yet use grid)

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/header.tsx

On desktop, now the 'My account' dropdown has fewer options, being able to click the big 'My account' heading allows the user to exit the flow.

[RB] - make header title clickable

---

app/client/components/productPage.tsx

Alternating backgrounds used to stretch to 100% width which is now doesn't look great within the new grid placement...
Added separating lines instead...

[RB] - replaced alternating grey backgrounds on product pages with divider lines

---

app/client/components/flowStartMultipleProductDetailHandler.tsx

Similar to https://github.com/guardian/manage-frontend/pull/330 which reinstated the `maxWidth` for flows, this reinstates the `padding` lost via https://github.com/guardian/manage-frontend/pull/324/files#diff-15d74ea927ca1ba8c634f25c2badc72aL15-L19
It has been reinstated in the wrapper component around all flows for simplicity and to avoid conflict with the new grid system, because in the not too distant future the flows will use the grid too.

fix padding on flows

---

app/client/components/cancel/cancellationFlow.tsx
app/client/components/cancel/caseCreationWrapper.tsx
app/client/components/cancel/stages/executeCancellation.tsx
app/client/components/cancel/stages/genericSaveAttempt.tsx
app/client/components/flowStartMultipleProductDetailHandler.tsx
app/client/components/holiday/holidayConfirmed.tsx
app/client/components/holiday/holidayDateChooser.tsx
app/client/components/holiday/holidayReview.tsx
app/client/components/holiday/holidaysOverview.tsx
app/client/components/payment/update/confirmPaymentUpdate.tsx
app/client/components/payment/update/paymentUpdated.tsx
app/client/components/payment/update/updatePaymentFlow.tsx
app/client/components/productPage.tsx
app/server/awsIntegration.ts
app/server/middleware/apiMiddleware.ts
app/server/routes/api.ts
app/shared/productResponse.ts

Shortly we will need to be augmenting the `members-data-api` response with `deliveryAddressChangeEffectiveDate` from `fulfilment-date-calculator`, so making some preparatory changes to keep that PR easier to digest.
- move `isTestUser` annotation of the `members-data-api` response to the server-side 
- various renaming and restructuring

renaming and restructuring, in anticipation of consuming `fulfilment-date-calculator`

---

app/server/fulfilmentDateCalculatorReader.ts
app/server/routes/api.ts
app/shared/productResponse.ts
app/shared/productTypes.tsx
cfn.yaml

_Preparatory refactor PR : https://github.com/guardian/manage-frontend/pull/337
Also relies on https://github.com/guardian/members-data-api/pull/418_
When proxying the `mma` endpoint of `members-data-api` before sending on the response to the client, in addition to adding the `isTestUser` (see https://github.com/guardian/manage-frontend/pull/337) on **each** item (i.e. each subscription) in the array it now adds a `deliveryAddressChangeEffectiveDate` on each response **IF**...
1. ... the `ProductType` inferred from the item/subscription has a `fulfilmentDateCalculatorProductFilenamePart` defined
2. AND there is a file **for today** in the `fulfilment-date-calculator-STAGE` S3 bucket **for that product**
_(it logs and fires a Sentry error if there isn't such a file but one is expected …

'deliveryAddressChangeEffectiveDate' now available on 'members-data-api' mma response

---

app/client/components/productPage.tsx
app/shared/productResponse.ts
app/shared/productTypes.tsx

Currently if you have a subscription that is a gift the delivery address displayed is that of the gift-er not the gift-ee, which is not so helpful.
Until the API is ready to pass through the gift-ee's address and also update that address, hide the display of the delivery address and the edit address button for gift subscriptions.
[trello ticket](https://trello.com/c/4oQHqLEM/774-remove-delivery-address-display-and-update-for-subscriptions-that-are-gifts)

remove delivery address for gift subscriptions

---

app/client/components/delivery/address/deliveryAddressForm.tsx

Browser support for the flat method is not good for safari and ie/edge. On top of that our babel setup doesn't appear to be polyfilling the flat method for these browsers.
FlatMap does seem to be working with babel. I have replaced the flat calls with flatMap callls as a temporary solution until we work on making babel play nice with flat.

[RB] - replace flat method with flatMap

---

app/client/components/identity/idapi/user.ts

Temporarily fixes an issue where displayName and username (two concepts that should be invisible to manage-frontend) are not set to the same value, causing many major problems with displaying usernames in discussion and modtools. This should be reverted once necessary changes are made to IDAPI that eradicate displayName.

Ensure displayName also set when username updated

---

app/client/components/delivery/records/deliveryRecords.tsx
app/client/components/delivery/records/deliveryRecordsApi.ts
app/client/components/delivery/records/deliveryRecordsTable.tsx
app/shared/productTypes.tsx

Guardian weekly subscriptions do not have delivery instructions associated with their delivery records.
Here is what it should look like (home delivery subscription for comparison):

[RB] - dont show delivery instructions for Guardian weekly subscriptions

---

app/client/components/holiday/existingHolidayStopActions.tsx
app/client/components/holiday/holidayConfirmed.tsx
app/client/components/holiday/holidayReview.tsx
app/client/components/holiday/holidaysOverview.tsx
app/client/components/holiday/summaryTable.tsx

The DELETE (a.k.a withdraw - see https://github.com/guardian/manage-frontend/pull/312) feature was not respecting 'test-users' and thus targeting the wrong instance `holiday-stop-api` when being used by a test-user.
This was because the test user header was missing from the request - this PR fixes that 🛠

add missing test user header on the DELETE holiday stops call

---

app/client/components/holiday/holidayDateChooser.tsx
app/client/components/holiday/holidayReview.tsx
app/client/components/holiday/holidayStopApi.ts

since it is redundant following https://github.com/guardian/support-service-lambdas/pull/561

removed redundant `estimateCredit` query param on 'holiday-stop-api' call to 'potential' endpoint

---

app/client/components/callCenterEmailAndNumbers.tsx

Rather than just adding a space, I decided to make the number bold, like the email above and the numbers for AUS & USA.

FIX missing space in call centre numbers

---

app/client/components/delivery/records/deliveryRecordsApi.ts
app/client/components/productPage.tsx
app/shared/productResponse.ts
app/shared/productTypes.tsx

It looks like https://github.com/guardian/manage-frontend/pull/353/files#diff-3804b2206d4f5da38c1348e201469148 introduced a pernicious little regression, where for gift subscriptions it started displaying the billing address of gifter under the heading of delivery address (and presented the `Edit address ->` CTA, but once in the flow it says `No addresses available for update` as expected).
This was caused by detecting the presence of the `showDeliveryAddressCheck` rather than executing it, nasty.
This PR fixes that, PLUS...
- few little refactors (like pulling out `subscription` on the `productDetail` into its own `const`, to avoid repetition of `productDetail.subscription`)
- displaying a really basic `[GIFT]` badge on gift subscriptions

fix regression in hiding delivery address for gifters

---

app/client/__tests__/components/delivery/records/deliveryRecords/step1.tsx
app/client/components/cancel/stages/executeCancellation.tsx
app/client/components/delivery/records/deliveryRecords.tsx
app/client/components/productPage.tsx

In https://github.com/guardian/manage-frontend/pull/366, there was a little oversight in the logic to release delivery problem reporting to me only, this PR fixes that.
PLUS
- a little tweak to use the new gift flag/badge more widely
- fix to the modified cancellation stuff to ensure it still works for 'effective immediately' cancellations (e.g. contributions)

correct limited release of delivery problem reporting 

---

app/client/__tests__/components/delivery/records/deliveryRecordStatus.tsx
app/client/__tests__/components/delivery/records/deliveryRecords/problemForm.tsx
app/client/__tests__/components/delivery/records/deliveryRecords/step1.tsx
app/client/components/delivery/address/deliveryAddressForm.tsx
app/client/components/delivery/records/deliveryRecordCard.tsx
app/client/components/delivery/records/deliveryRecordStatus.tsx
app/client/components/delivery/records/deliveryRecords.tsx
app/client/components/delivery/records/deliveryRecordsAddress.tsx
app/client/components/delivery/records/deliveryRecordsProblemConfirmation.tsx
app/client/components/delivery/records/deliveryRecordsProblemForm.tsx
app/client/components/delivery/records/deliveryRecordsProblemReview.tsx
app/client/components/delivery/records/productDetailsTable.tsx
app/client/components/svgs/giftIcon.tsx
app/shared/productTypes.tsx

- navigate up to parent if context information is missing eg user refreshes the confirmation page
- design review: button style consolidation, show more link styling, text area width, delivery record card alignment
- update component tests to reflect markup/component updates
- remove 'select all' checkbox
- update paragraphs to textSans
- add problem type form component tests
- don't show future records past read only mode
- add 'Delivered despite suspension' back into the problem options and link it to holiday stop records

Report delivery problems update

---

app/client/components/delivery/records/deliveryRecords.tsx
app/client/components/delivery/records/deliveryRecordsApi.ts
app/client/components/delivery/records/deliveryRecordsProblemConfirmation.tsx

`test-user`s were not being respected for the `delivery-records-api` calls from manage.
This is because the server-side portion of manage requires the `X-Gu-Membership-Test-User` request header to be present so it knows what instance of the lambda to call. The client was not sending this... now it is 😸 
In an ideal world, `test-user`s would be a first-class concept in identity and would come back from calls to IDAPI (rather than separately implemented in loads of RR stacks)... I'll try and push for this with identity.

FIX delivery records for 'test-user'

---

app/client/components/identity/PublicProfile/ProfileFormSection.tsx

Users now have to set a username before commenting. First and last name is not a default.

reword set username message

---

app/server/routes/api.ts
cfn.yaml

improve manage-frontend 5XX alarm (backend + ELB)
- trigger alarm on any 500 happening on the application server
- trigger alarm on any 500 happening on the LoadBalancer
tested for both situation for
- failing app server
- ELB giving 503 when number of EC2 instances was 0
- https://trello.com/c/tvxGB2UF/937-task-improve-manage-frontend-5xx-alarm-backend-elb
- Following the precedent set here https://github.com/guardian/members-data-api/pull/425

improve manage-frontend 5XX alarm (backend + ELB)

---

app/client/components/delivery/address/deliveryAddressForm.tsx
app/client/components/delivery/address/formValidation.tsx
app/client/components/delivery/address/select.tsx
app/client/components/delivery/records/deliveryRecordCard.tsx
app/client/components/delivery/records/deliveryRecords.tsx
app/client/components/delivery/records/deliveryRecordsAddress.tsx
app/client/components/delivery/records/deliveryRecordsApi.ts
app/client/components/delivery/records/deliveryRecordsProblemConfirmation.tsx
app/client/components/delivery/records/deliveryRecordsProblemReview.tsx
app/client/components/delivery/records/productDetailsTable.tsx
app/client/components/delivery/records/userPhoneNumber.tsx
app/client/components/productPage.tsx
app/shared/productTypes.tsx

- Removed the notion of `canReportProblem` since we now want problem reporting enabled for all products which have delivery records configured (Home Delivery and Guardian Weekly).
- Also removed the usage of `fulfilmentDateCalculator` config in the delivery problem reporting logic, for better separation of concerns (replaced it with the same product name strings repeated in the section of `productTypes.tsx` dedicated to delivery records).
- Fixed a little display bug on the 'Show more' button on the delivery addresses
- Fixed little layout bug in the detail tables between mobile and tablet breakpoints, throughout the delivery problem flow (now just always stacks vertically below tablet).
- Fixed the phone number updater
- Fixed the total credit amount calculation (which means some will …

release home delivery problem reporting

---

app/client/components/delivery/address/deliveryAddressForm.tsx

…which makes its way into `Address_Change_Information_Last_Quoted__c` (see https://github.com/guardian/manage-frontend/pull/365).
This is to help keep the email confirmation as simple as possible, because the `AfterInsert` Salesforce trigger on `Contact` need only check if `Address_Change_Information_Last_Quoted__c` has changed. However without the addition of this timestamp, then a user could update their address multiple times in the same day and only receive email confirmation for the first change, or we'd need more complexity on the Salesforce side.

[delivery-address-flow] add timestamp to the address change information

---

app/client/components/cancel/stages/genericSaveAttempt.tsx

no cancellation cases are 'Open'ed when feedback is provided

---

app/client/components/callCentreNumbers.tsx
app/client/components/cancel/cancellationConstants.ts
app/client/components/cancel/cancellationReason.ts
app/client/components/cancel/caseCreationWrapper.tsx
app/client/components/cancel/contributions/contributionsCancellationFlowStart.tsx
app/client/components/cancel/contributions/contributionsCancellationReasons.tsx
app/client/components/cancel/digipack/digipackCancellationFlowStart.tsx
app/client/components/cancel/digipack/digipackCancellationReasons.tsx
app/client/components/cancel/membership/membershipCancellationReasons.tsx
app/client/components/cancel/stages/genericSaveAttempt.tsx
app/client/components/genericErrorScreen.tsx
app/client/components/holiday/holidayReview.tsx
app/client/components/payment/update/confirmPaymentUpdate.tsx
app/shared/productResponse.ts
app/shared/productTypes.tsx

This PR introduces a **self-service cancellation flow for the Digital Subscription**, using the same mechanism as we have for membership & contributions.
This PR also includes some tweaks to existing cancellation flows and some call centre related components, which aim to reduce contact to the call centre during this challenging time (Coronavirus 😷).
_notice the `Cancel this digital subscription` link at the bottom_
_the `Continue` button becomes enabled when user selects a reason option_
_... and after having entered & submitted feedback in the box..._
_... or if you don't currently have a recurring contribution, you see the 'thrasher' beneath..._

Digipack cancellation flow

---

app/client/components/cancel/stages/executeCancellation.tsx

No longer bother calling `sf-cancellation-cases-api` on confirmation page (to update the case) if we don't have a `caseId` (because it failed to create one earlier in the flow), because it would obviously always fail and was therefore obscuring the success/failure of their actual cancellation call. 
With the increase in failures from `cancellation-sf-cases-api` (because of sync slowness - see https://trello.com/c/oAZ1nzrk/1066-consider-a-queue-for-the-cancellation-cases-mechanism) users will be seeing errors on the confirmation screen even though they in fact do succeed in cancelling their product - bad UX essentially.
Note, this is already handled gracefully on 'Step 2' by not showing the feedback box.

[cancellation flow] don't bother calling `sf-cancellation-cases-api` on confirmation page if we have no caseId (was bad UX)

---

app/client/components/delivery/address/deliveryAddressForm.tsx
app/client/components/flowStartMultipleProductDetailHandler.tsx
app/shared/productTypes.tsx

When going to `/delivery/<PRODUCT TYPE>/address` it invokes the `FlowStartMultipleProductDetailHandler` (much like all the other flows) which exists to handle multiple subs of the same type (think of it as an interstitial product picker specifically for the product type in the URL. If the user comes from the product page the specific sub they chose is passed through via 'browser history state' to avoid additional unnecessary calls.
The delivery address update flow needs ALL subs to form the list of 'affected subscriptions', so previously if user had gone directly to say `/delivery/voucher/address` they would have only seen voucher in the list of affected subs (which is incorrect).
This change passes through a product type override for the fetch this does, such that for the delivery …

fix list of affected subs on delivery address update flow when coming into the URL directly (rather than via subscriptions page)

---

app/client/components/asyncLoader.tsx
app/client/components/cancel/cancellationContexts.tsx
app/client/components/cancel/cancellationFlowEscalationCheck.tsx
app/client/components/cancel/cancellationReason.ts
app/client/components/cancel/cancellationSummary.tsx
app/client/components/cancel/contributions/contributionsCancellationFlowStart.tsx
app/client/components/cancel/digipack/digipackCancellationFlowStart.tsx
app/client/components/cancel/gw/gwCancellationFlowStart.tsx
app/client/components/cancel/gw/gwCancellationReasons.tsx
app/client/components/cancel/physicalSubsCancellationFlowWrapper.tsx
app/client/components/cancel/stages/genericSaveAttempt.tsx
app/client/components/cancel/voucher/voucherCancellationFlowStart.tsx
app/server/routes/api.ts
app/shared/productTypes.tsx

**Similar to recent voucher cancellation flow (https://github.com/guardian/manage-frontend/pull/384) in terms of the notion of an 'escalation route' etc. The key differences are...**
- of course, different copy and slightly different reasons
- an additional call to the [`/cancel` endpoint of `delivery-records-api`](https://github.com/guardian/support-service-lambdas/pull/643) which wasn't required for voucher. This is done in parallel with the equivalent `holiday-stops-api` call, which required some refactoring of `AsyncLoader` to support multiple `Response`s.

GW cancellation flow

---

app/client/components/payment/update/card/cardInputForm.tsx
app/server/routes/frontend.ts
app/server/stripeSetupIntentConfig.ts
app/server/stripeSetupIntentsHandler.ts
app/shared/globals.ts

Recently fraudulent card testers have moved on from `support-frontend` onto the payment update flow of MMA. 
In this PR we **add Google reCaptcha v2 to the payment update flow (with verification on the server-side portion on the SetupIntents endpoint - since that was the endpoint being abused)**.
In the UI, after some back and forth I've placed it as a pre-requisite to entering new card details (rather than just before completing the payment update) because it's an input to the SetupIntent and previously the card form wouldn't load if we couldn't create a SetupIntent (to avoid user pointlessly entering their new card details) and I figure the same still applies. 
In addition to our mandatory sentence I've added an explainer sentence as to why they're being asked...

⛔🤖🚫⚠🚥🚦🚗 ⛰️ 🚲 🚧 🛣️ 

---

app/client/components/holiday/existingHolidayStopActions.tsx
app/client/components/holiday/holidayDateChooser.tsx
app/client/components/holiday/holidayStopApi.ts
app/client/components/holiday/holidaysOverview.tsx
app/client/components/holiday/summaryTable.tsx

Note explainer text in place of usual 'actions' and note that the Summary doesn't include these issues in the count/limit.
Note again that the imposed holiday stop isn't included in the count/limit (57 remaining).

[holiday-stops] add support for bulk suspensions

---

app/client/components/cancel/stages/executeCancellation.tsx

Now the underlying cancellation error scenario is fixed (https://github.com/guardian/members-data-api/pull/437) we should escalate error cases so the CSRs can take a look.

escalate cancellation errors (now the underlying error scenario is fixed in members-data-api)

---

app/server/apiProxy.ts
app/server/awsIntegration.ts
app/server/log.ts
cfn.yaml

Following https://github.com/guardian/manage-frontend/pull/373 (detailed logging) and https://github.com/guardian/manage-frontend/pull/402 (50% mechanism for Account Overview release) we can now put in place metrics to track all our key events for better visibility/monitoring.
The initial purpose is for extra visibility as we roll out Account Overview, but once that's out to 100% **we can begin using these metrics to set alarm thresholds (e.g. _no card updates in the last hour_).**
It uses the [`CloudWatch.putMetricData`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatch.html#putMetricData-property) (part of AWS SDK - already a dependency). The metric namespace is fixed as `manage-frontend` and uses the `loggingCode` (e.g. `MDA_UPDATE_PAYMENT_CARD`) as the metric name, …

custom CloudWatch Metric for every `loggingCode`

---

app/server/stripeSetupIntentsHandler.ts

Following on from https://github.com/guardian/manage-frontend/pull/404 - missed an additional place that doesn't use the proxy but needed metrics.

add missing calls to putMetric for things outside of the proxy

---

app/client/components/identity/EmailAndMarketing/index.tsx

"It does exactly what is says on the tin"

[RB] - remove pesky back tick from the Email and marketting section title

---

app/server/apiProxy.ts

Caught by server-side Sentry errors...
Really pernicious problem, caused by using `log.warning` rather than `log.warn`  - introduced in https://github.com/guardian/manage-frontend/pull/373 - the exception was fortunately being caught by the `.catch` on the promise, and so no real difference for users (since this only affected non-OK responses anyway).
This also explains why, in the logs, we had no visibility on the `responseBody` for all non-OK responses.

fix problem with logging of non-OK responses

---

app/client/components/accountoverview/manageSubscription.tsx

The old `productPage.tsx` only showed holiday stops linkage for certain supported product types (Voucher, HD, GW)... the newer `manageSubscription.tsx` was missing some conditions in the conditional rendering (so was displaying the holiday stops section for digipack, which linked to a Not Found, since the actual routes are only created based on the outcome of `shouldHaveHolidayStopsFlow(productType)`, so now the conditional rendering uses the same function.
Also tweaked the copy since the annual issue limit is different for each product type (which is provided by `holiday-stop-api` and therefore can't be displayed accurately on this page) so is now more generic and uses the dynamic `issueKeyword` (issue, paper or voucher) accordingly.

FIX conditional rendering of holiday stops section on the 'manage subscription' page

---

app/client/components/accountoverview/manageSubscription.tsx
app/client/components/productPage.tsx
app/shared/productTypes.tsx

Adds renewal section to manage subscription page if not auto renewing and if enabled in productTypes (currently only Guardian weekly).
The old behaviour for GW renewal was to link to the `/manage` section of the old subs platform, if (and only if) the customer had a single subscription (because the old subs platform could only display one at once) or otherwise display instructions to contact the call centre. The manual renewals mechanism in the old platform...
- is super ugly
- credit card appears to be broken
- was the only outstanding link from manage.theguardian.com to that platform
... plus detecting multiple subs when within 'manage subscription' page of the newer style design of MMA would be nasty. SO, **I decided to kill that last linkage to the old platform** and always prompt …

GW renewal link

---

app/client/components/accountoverview/accountOverview.tsx
app/client/components/accountoverview/accountOverviewCard.tsx
app/client/components/accountoverview/manageMembership.tsx
app/client/components/accountoverview/manageSubscription.tsx
app/client/components/productPage.tsx
app/shared/productResponse.ts
app/shared/productTypes.tsx

rename product.tsx to accountOverviewCard.tsx. Move away from string comparisons for branching logic and use properties in productType object (config)

[RB TR] - Account overview product card refactor

---

app/client/components/page.tsx

Make page header title holder wider on small mobile breakpoints (320 - 374px) to stop title from wrapping

[RB] - page header title space

---

app/client/components/accountoverview/manageSubscription.tsx

Adds the gift icon to the right hand side of the product title in the manage subscription page if the subscription is a gift.
Desktop breakpoint             |  Mobile breakpoint (320px)

[RB] - add gift icon to manage sunscription header if applicable

---

app/client/components/payment/directDebitLogo.tsx

Remove height auto attribute from direct debit logo (not needed and looks whack on chrome

[RB TR] - fix direct debit svg height on chrome

---

app/client/components/page.tsx
app/client/components/productDescriptionListTable.tsx

on ProductDescriptionListTable  component only show the alternate row background colours if there is enough data to render more than 1 row.
Increase the padding-top slightly for the page header on Mobile breakpoints

[RB] - styling housekeeping

---

app/client/components/user.tsx

fix redirect from wild card path
reach router requires a from property. Also when using a wildcard you need to prepend a `/` eg `/*`

[RB TR] - fix redirect from wild card path

---

app/shared/productTypes.tsx

Add digital voucher product type to `PRODUCT_TYPES` with the customer facing name of "subscription card"

[RB TR] - add product type for digital voucher

---

README.md
nginx/README.md
nginx/identity-frontend-CODE-fallback.conf
nginx/members-data-api-CODE-fallback.conf
nginx/setup.sh

add nginx configs to proxy CODE instances of `identity-frontend` and `members-data-api` **as a fallback** if not running locally (to develop those services in parallel one has to simply run them locally and it will use instead of CODE).
The set-up instructions were quite involved for new starters previously - now just one set-up script for nginx, plus a couple of simple commands for manage itself.
Also day-to-day (for all devs) having to start various other services locally was not only a faff but a distraction when debugging (if one crashed or didn't have some config etc).
README changes cover this

simplify first time set-up and day-to-day running of manage-frontend

---

app/client/components/accountoverview/accountOverview.tsx
app/client/components/accountoverview/manageProduct.tsx
app/client/components/payment/paymentFailureAlertIfApplicable.tsx
app/client/components/payment/update/updatePaymentFlow.tsx
app/shared/productResponse.ts

- Add paymentFailureAlertIfApplicable component to remove duplication
- Following https://github.com/guardian/members-data-api/pull/461 removed the nasty replace function in favour of simply appending the `Please check that the payment details shown are up to date.` sentence

[RB TR] - payment failure alert refactor

---

app/client/components/accountoverview/manageProduct.tsx
app/client/components/callCenterEmailAndNumbers.tsx
app/client/components/cancel/cancellationFlow.tsx
app/client/components/cancel/contactUsToCancel.tsx
app/client/components/delivery/address/deliveryAddressForm.tsx
app/client/components/delivery/address/deliveryAddressReview.tsx
app/client/components/delivery/records/deliveryAddressStep.tsx
app/client/components/delivery/records/deliveryRecordsProblemConfirmation.tsx
app/client/components/infoSection.tsx
app/client/components/user.tsx
app/shared/productResponse.ts
app/shared/productTypes.tsx

Following https://github.com/guardian/members-data-api/pull/459 we now get a new top level object with key `selfServiceCancellation` on our `ProductDetail` type, for example...
... which we use to drive...
- a new `CancellationCTA` component (part of `manageProduct.tsx`) which, depending on what we get from the API, shows either... 
...OR... 
...OR nothing if the sub is already cancelled. 
The above both link to cancellation flow regardless and then the cancellation flow either displays the existing 3-step self-service flow OR...
- a new `ContactUsToCancel` component which displays contact details (filtered by the properties in the new `selfServiceCancellation` from the API - which required a refactor of `callCenterEmailAndNumbers.tsx`)...
At one point we thought we were going to need in …

Cancellation contact us

---

app/client/components/cancel/cancellationFlow.tsx
app/client/components/cancel/membership/membershipCancellationFlowStart.tsx
app/client/components/cancel/voucher/voucherCancellationFlowStart.tsx
app/shared/productTypes.tsx

Only show membership benefits for people cancelling if they are not on Friend tier

[RB TR] - Hide membership benefits during cancellation for friend tier

---

app/client/components/help.tsx

Calvin needs more visibility into how the FAQs page is being used, so adding click tracking the the `<a>` tags.

add click tracking to the Help FAQs

---

app/client/components/accountoverview/accountOverviewCard.tsx

In anticipation of the AUS moment being added to manage... adding some 'event' tracking to the two CTAs on each `AccountOverviewCard`...
... to make it easier to track any detrimental impact to our critical paths.
Note that its already possible to track this via the page transitions from Account Overview (which is on the root of manage i.e. `/`) to the 'manage product' page (which is on `/membership`, `/contributions` or `/subscriptions` depending on the product) via GA and/or Ophan... this just makes it easier.

add click tracking to the two CTAs on each AccountOverviewCard (AUS moment prep)

---

app/client/components/delivery/records/deliveryRecordCard.tsx
app/client/components/delivery/records/deliveryRecords.tsx
app/client/components/delivery/records/deliveryRecordsProblemConfirmation.tsx
app/client/components/delivery/records/deliveryRecordsProblemReview.tsx

Delivery instructions are currently only guaranteed to be forwarded on to newspaper subscription delivery partners. This does not include Guardian Weekly subscriptions.
This pr is to remove the delivery instructions from the delivery history/record problem reporting journey. The delivery instructions are only shown if the `showDeliveryInstructions` property is set to true in `productTypes`
[ticket](https://trello.com/c/jOtYGBz2/959-task-remove-instructions-for-guardian-weekly-on-delivery-history-display)

Remove delivery instructions for GW

---

app/client/components/accountoverview/accountOverviewCard.tsx
app/client/components/accountoverview/manageProduct.tsx
app/client/components/delivery/address/deliveryAddressEditConfirmation.tsx
app/client/components/delivery/address/deliveryAddressForm.tsx
app/client/components/delivery/address/deliveryAddressReview.tsx
app/client/components/delivery/address/input.tsx
app/client/components/delivery/address/select.tsx
app/client/components/delivery/records/deliveryAddressStep.tsx
app/client/components/delivery/records/deliveryRecordInstructions.tsx
app/client/components/delivery/records/deliveryRecordStatus.tsx
app/client/components/delivery/records/deliveryRecords.tsx
app/client/components/delivery/records/deliveryRecordsAddress.tsx
app/client/components/delivery/records/deliveryRecordsProblemConfirmation.tsx
app/client/components/delivery/records/deliveryRecordsProblemForm.tsx
app/client/components/delivery/records/deliveryRecordsProblemReview.tsx
app/client/components/delivery/records/readOnlyAddressDisplay.tsx
app/client/components/delivery/records/userPhoneNumber.tsx
app/client/components/header.tsx
app/client/components/help.tsx
app/client/components/nav/dropdownNav.tsx
app/client/components/nav/leftSideNav.tsx
app/client/components/page.tsx

Source's [global colour names](https://www.theguardian.design/2a1e5182b/p/492a30-light-palette) have changed from semantic words to numbers representing approximate lightness values. This approach was considered more scalable. The word-based names are deprecated and the number-based names have been available for some time.
With 2.0.0 we have decided to declutter the API and delete the old names. This change migrates manage-frontend from the old naming system to the new one.
Difficult, as the change spans a large number of files and flows. You can read the [colour mapping spreadsheet](https://docs.google.com/spreadsheets/d/1rcBqHDJmNFnS0NavpotpEvg-dW3ONxvWDL7eSWyfPPY/edit?usp=sharing) I used to ensure I didnt make any typos. This is derived from mappings in the [global colours …

Migrate legacy colour names to new colour names

---

app/client/__tests__/components/identity/MarketingPreference.tsx
app/client/__tests__/components/identity/__snapshots__/MarketingPreference.tsx.snap
app/client/components/identity/EmailAndMarketing/NewsletterSection.tsx
app/client/components/identity/MarketingPreference.tsx
app/client/components/identity/idapi/newsletters.ts
app/client/components/identity/models.ts

Tracking in Ophan is needed for the newsletters in order to measure impact of upcoming changes as part of the newsletters OKR.
We have added `data-link-name` attributes to the newsletter checkboxes and have used the `identityName` as the identifier. This also means that the `ConsentOptions` model has been updated to include this field.
Co-authored-by: Alex Dufournet <alex.dufournet@theguardian.com>
On the marketing preferences page, checking and unchecking a newsletter should trigger an Ophan page click tracking event in the network inspector. This event shouldn't be triggered for normal marketing preferences.
Ophan tracking from the email preferences page.
I don't think there are any potential risks here, unless there needs to be an update to any privacy information about this being …

Add ophan tracking to newsletter preferences

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/nav/dropdownNav.tsx
app/client/components/nav/navConfig.tsx

previously at larger (desktop) breakpoints the dropdown nav only had "Comments & replies" and "Sign out" in it. Now it has the full set of nav items at all breakpoints.
Before  |  After

[RB] - dropdown nav update

---

app/package.json
app/server/awsIntegration.ts
app/yarn.lock

https://trello.com/c/YlnL1eOP/1523-secure-invoicing-api
This PR provides the ability to use any HTTP client to send AWS [signed](https://docs.aws.amazon.com/apigateway/api-reference/signing-requests/) requests to API Gateway resources which require AWS_IAM authorisation. The function `getAwsSignature` by default uses `CredentialProviderChain` defined in `awsIntegration.ts` to resolve AWS credentials.
```http
POST /DEV/refund HTTP/1.1
Host: ${apiId}.execute-api.${region}.amazonaws.com
Content-Type: application/json
x-api-key: ********
X-Amz-Content-Sha256: ******
X-Amz-Security-Token: ****
X-Amz-Date: ****
Authorization: ****
{ "foo": "bar" }
```
```typescript
import {getAwsSignature} from "./awsIntegration";
const body = JSON.stringify({ "foo": "bar" })
const host = …
```

Sign AWS API Gateway requests for AWS_IAM authorization

---

cfn.yaml

Without this policy, Invoicing API which requires IAM authorization https://github.com/guardian/manage-frontend/pull/465, responds with 403
```
User: arn:aws:sts::*********:assumed-role/support-CODE-manage-frontend-AppRole-********/i-******* 
is not authorized to perform: execute-api:Invoke 
on resource: arn:aws:execute-api:eu-west-1:************:********/DEV/GET/invoices"}
```
Go to 
```
https://manage.code.dev-theguardian.com/billing
```
and tail with
```
awslogs get --profile membership support-manage-frontend-CODE --watch | grep -i LIST_INVOICES
```
should respond with
```
"status":200,"isOK"
```
As mentioned in https://github.com/guardian/manage-frontend/pull/465 we should alarm on 403 because it should never occur.
Due to environment switching design we have to hardcode stages
``` …
```

Give permission to invoke API Gateway needed for AWS signature

---

app/client/components/payment/update/card/cardInputForm.tsx

only load the stripe sdk when the user explicitly decides to update their payment details:
I've taken some screenshots in order to explain the approach here ...
The first image is the default route (account overview) on the existing master branch
The 2nd image is if we move the loadStripe call within the useEffect hook but keep the existing stripe imports (again on the default route - account overview):
The 3rd and 4th images are the approach taken in this pr (the 1st image being the default route and the 2nd being the update payment page after capthca is complete)
update payment page:

[RB] - only load stripe SDK on intent

---

app/client/components/billing/invoicesTable.tsx
app/shared/productResponse.ts

For invoices that span multiple subscriptions display the string "Multiple prices" instead of the price in the invoice table.
reliant on the 2 following prs:
https://github.com/guardian/manage-frontend/pull/477
https://github.com/guardian/invoicing-api/pull/15
Before            |  After

Duplicate invoices

---

app/client/components/billing/billing.tsx
app/client/components/billing/invoiceTableYearSelect.tsx
app/client/components/billing/invoicesTable.tsx

adds GA tracking for the view and download invoice links, clicks on the invoice pagination, and the selection of a year from the invoice year select.
The event labels are as follows:
pagination event: `invoice_pagination_select`
view pdf tracking event: `view_XXXX_pdf_invoice` eg `view_homedelivery_pdf_invoice`
download pdf tracking event: `download_XXXX_pdf_invoice` eg `download_homedelivery_pdf_invoice`
year select event: `invoice_year_select`

[RB] - add GA tracking for invoice interactions

---

app/package.json

Fix 
```
warning " > @guardian/src-inline-error@1.9.1" has incorrect peer dependency "@guardian/src-foundations@^1.9.1".
```

Resolve incorrect peer dependency

---

build-tc

Related PR: https://github.com/guardian/manage-frontend/pull/496
Some TC agents apparently did not have global yarn installed which is needed to boostrap local yarn under `.yarn/releases/` via `yarn-path` in `.yarnrc`. So now we do not depend on agent's installation at all (although this is non-standard way of doing it).
- Try to run TC build
- Check build log output for correct version of yarn

Do not depend on yarn installed on TC agent even for bootstraping

---

app/shared/productTypes.tsx

- Related service-layer PR: https://github.com/guardian/support-service-lambdas/pull/692
- Related Salesforce PR: https://github.com/guardian/salesforce/pull/278
- Enable users to self-service their Subscription Card holiday suspensions
In DEV:
1. Until `Subscription Card` has been properly released, enable its acquisition like so
1. Change `val useDigitalVoucher = true` in [support-frontend](https://github.com/guardian/support-frontend/blob/920e638c35430cc260acdb1878f37bffa1d12fae/support-models/src/main/scala/com/gu/support/catalog/Product.scala#L93)
1. Deploy branch with above change to CODE by deploying `support:support-workers-mono` and `support:frontend-mono`
1. Acquire Subscription Card without using test user at https://support.code.dev-theguardian.com/uk/subscribe/paper
1. Fetch …

Enable holiday stops for Subscription Card (Digital Voucher)

---

app/client/components/identity/PublicProfile/ProfileFormSection.tsx
app/client/components/identity/PublicProfile/index.tsx
app/client/components/identity/idapi/user.ts
app/client/components/identity/models.ts

A decisions has been made to remove public profile information from user profiles for about me, location and interests.
This PR removes it from manage-frontend. We will eventually delete the data from IDAPI
https://trello.com/c/ALpVrAu3/2340-removing-about-me-location-interests-just-the-ui-m
Tested locally running manage
Users can no longer see or enter these details

Remove public profile information from manage

---

app/client/components/accountoverview/accountOverviewCard.tsx
app/client/components/accountoverview/manageProduct.tsx
app/client/components/cancel/cancellationDateResponse.ts
app/client/components/cancel/cancellationFlow.tsx
app/client/components/cancel/cancellationSummary.tsx
app/server/routes/api.ts
app/shared/dates.ts
app/shared/productResponse.ts

- https://trello.com/c/b8Rx4P6u/1642-manage-frontend-cancellation-flow-give-user-choice-of-date-of-cancellation-but-the-date-is-never-used-s
- https://trello.com/c/IIlIyWzB/1636-self-service-cancellation-effective-date-bug
- Related PR: https://github.com/guardian/members-data-api/pull/472
- MMA will now make use of dedicated endpoint in MDAPI to first determine effective cancellation date
- If subscription is in trial period or lead time, then it will cancel now without CSR manual intervention
- If subscription is in invoiced period, then MDAPI will respond with end of last invoice period date, and user will be presented with options to cancel now or at the end of invoice. If user chooses now, then case will be raised to CSR for manual intervention
- Showing of options can be entirely …

Get cancellation effective date from dedicated endpoint in MDAPI

---

app/client/components/accountoverview/newsletterOptinSection.tsx

Tracking for successful opt-in and opt-out as well as update error state.
Target newsletter id is passed through as part of the event label.
no visual changes

[RB] - add tracking to the newsletter opt in check box form

---

app/client/components/accountoverview/accountOverviewCard.tsx
app/client/components/accountoverview/manageProduct.tsx
app/client/components/buttons.tsx
app/client/components/productDetailProvider.tsx

`ProductDetails` is sometimes passed directly as the `state` object of Reach Router [Link](https://reach.tech/router/api/Link) component
```
<Link
state={props.productDetail}
...
>
```
and other times nested inside another object 
```
<LinkButton
state={
{
productDetail,
flowReferrer: {
title: NAV_LINKS.billing.title,
link: NAV_LINKS.billing.link
}
}
}
...
/>
``` 
so this PR accounts for both possibilities in `ProductDetailProvider` component. This fixes the bug where  `ProductDetailProvider` would think there is nothing in the state, and then re-request from MMA, however MMA could respond with less precise information, for example, there could be two subscriptions of the same kind, and `ProductDetailProvider` would not have enough information to know which the user has picked, so it …

Fix early redirection to root due to productDetail existing at different levels in location.state

---

app/client/components/holiday/holidayDateChooser.tsx
app/client/components/holiday/holidayStopApi.ts
app/shared/productResponse.ts

* https://trello.com/c/PlKMGmbK/1652-unable-to-apply-holiday-stops-via-mma-if-termstartdate-is-far-enough-in-the-future
* Related PR: https://github.com/guardian/members-data-api/pull/476
* Use dedicate field for anniversary
1. Renew subscription few times to push termEndDate
1. Try to schedule holiday stops
For example, the user that raised the case (see trello card) is able to suspend subscription.
Tested end-to-end in DEV.

Fix holiday stops when termEndDate does not represent anniversary

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/footer/footer.tsx

Following a refactor of how the newsletter embeds will work, there won't be an iframe hosted at `profile.guardian.co.uk`. Instead I'm moving this to using `www.theguardian.com` directly, and we'll be implementing some changes to make sure that things like autofilling email addresses for logged in users will be implemented in a way that is suitable across platforms.
- https://github.com/guardian/frontend/pull/23051 (Reverted pending some work on the router, but the code will be the same following these changes)

Update newsletter footer embed src

---

app/.snyk
app/client/components/accountoverview/accountOverview.tsx
app/client/components/accountoverview/accountOverviewCancelledCard.tsx
app/client/components/accountoverview/supportTheGuardianSection.tsx
app/package.json
app/server/routes/api.ts
app/shared/productResponse.ts
app/shared/productTypes.tsx
app/yarn.lock

Related PR: https://github.com/guardian/members-data-api/pull/478
Cancelled products should show in the account overview page for 3 months after they were cancelled.
A new `/cancelled` endpoint has been created (see [here](https://github.com/guardian/members-data-api/pull/478/commits/f350544476ecefaf0c9a240cc546a3ed014deabd)) which is called alongside the existing `/me/mma` members-data-api request.
A new `accountOverviewCancelledCard` component has been created to handle the response from the `/cancelled` endpoint. The response from the `/cancelled` endpoint is a slimmed down version of the `/me/mma` response and as such the component does not currently show payment information, a slightly slimmed down product title (`Newspaper Voucher` instead of `Newspaper Voucher - Everyday` for …

[RB] - display cancelled products in the account overview page for 3 months

---

app/client/components/contactUs/contactUs.tsx
app/client/components/contactUs/contactUsForm.tsx
app/client/components/contactUs/subTopicForm.tsx
app/client/components/contactUs/topicForm.tsx

This PR refactors the Contact Us React components. The goal is to make the main Contact Us component more lean.
The main Contact Us component was getting quite big. This made it more difficult to work on. It also affects the ease with which someone new to the code would be able to pick it up. Both of these negatively impact the team's speed of delivery.
The goal was achieved mainly by delegating minor responsibilities from the main component to its children. This opened up the possibility for some abstraction at the main component level, which in turn allowed the simplification of a big chunk of its logic.
The main Contact Us component went from **_~450 lines_** of code to only **_~285 lines_**. Components are better encapsulated and provide better abstraction.
- Removes the use of …

Refactor Contact Us form components

---

app/server/apiGatewayDiscovery.ts

use https instead of http for the contact us api url. The load balancer only supports https.
No more timeouts when submitting the contact us form

[RB] - use https instead of http

---

app/client/components/contactUs/contactUsForm.tsx

Remove timeout function that removed the recaptha form 1 second after the user had clicked on it.
Now the recaptcha should always be visible.

[RB] - don not hide the captha box after the user has ticked it

---

app/client/components/contactUs/contactUsForm.tsx

Fix bug where if you leave any mandatory form fields blank, regardless of whether you have told the world you are not a robot, you see the validation error complaining that you haven't told us you're not a robot!
Before                                |  After

[RB] - fix captcha validationbug

---

app/client/components/analytics.tsx
app/client/components/consent/consentsBanner.tsx
app/client/components/scrollToTop.tsx
app/client/components/user.tsx

This PR improves a tweak that was introduced in #133 to make all page navigations scroll to the top (as they would if it wasn't a single page app). It is now smoother. It also tweaks `@reach/router` settings so we can make the most of its accessibility features.
When a user navigates to a different page within the SPA `@reach/router` will focus the new component. This needs to happen for accessibility reasons (eg: not confusing screen readers). When this components is focused the browsers scrolls to it.
Because we're adding our header outside the client side routing (`Main` component) when the router focuses the element the scroll will hide part of the page. PR #133 fixes this by scrolling the page back to top shortly after navigation.
In cases where the user comes from a long page that …

Rework page flow tweak

---

app/client/components/contactUs/contactUs.tsx

We were using the wrong variable as a subtopic when submitting the Contact Us form. This PR fixes it.

Use the correct variable

---

app/.snyk

Updates the synk wizard config.
Most of the dependencies  don't have a viable upgrade or patch available.
The dependencies and setting snyk to warn instead of breaking the build are to be looked at in subsequent health tasks.

[RB] - update synk wizard config

---

app/client/components/contactUs/contactUsForm.tsx
app/server/contactUsApi.ts

Adds length validation to the Contact Us form and endpoint. [Trello card](https://trello.com/c/9UUZDKq9/1778-alarm-5xx-rate-from-contact-us-api-prod).
On the client-side it makes it so the user is unable to go over the allowed length for the name, email and subject fields.
On the endpoint it trims the name, email, subject and message fields so they do no go over the allowed length.

Contact Us form length validation

---

app/.snyk

Snyk is blocking the build due to a 2 security vulnerabilities introduced by formik that aren't patched yet. Ignored for 30 days to allows the build to complete. This is yet another reason why we should work toward getting rid of formik.
```
✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-LODASH-590103] in lodash@4.17.19
introduced by formik@1.5.8 > lodash@4.17.19
This issue was fixed in versions: 4.17.20
✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.io/vuln/SNYK-JS-UAPARSERJS-610226] in ua-parser-js@0.7.19
introduced by formik@1.5.8 > create-react-context@0.2.3 > fbjs@0.8.17 > ua-parser-js@0.7.19
This issue was fixed in versions: 0.7.22
```
We **_may_** be vulnerable to denial of service attacks in our pages that use formik (Settings …

Update snyk policy

---

app/client/components/contactUs/contactUsForm.tsx

This PR makes 3 changes.
- Uses the correct variable for email when updating the validation state on `ContactUsForm`. This bug hasn't had impact in the wild because the `isValid` is being set correctly and the error message in the fullName and email fields are the same.
- Changes the email error message to more descriptive of the issue.
- Removes the email type from the email input as it interferes with our validation code and presents our users with an inconsistent experience (example in the screenshot below).
| Before        | After           |
| ------------- |:-------------:|
| ![image](https://user-images.githubusercontent.com/48949546/99789944-49f77e80-2b1b-11eb-87f8-80fb3868c81c.png) | ![image](https://user-images.githubusercontent.com/48949546/99790277-c7bb8a00-2b1b-11eb-9863-ea911 …

Contact Us: Fix email validation

---

app/client/components/contactUs/contactUs.tsx
app/client/components/contactUs/contactUsForm.tsx
app/server/contactUsApi.ts
app/shared/contactUsConfig.ts
app/shared/contactUsTypes.ts

This PR makes a few changes to the Contact Us form.
- Renames variables so they are common across all the Contact Us components (client-side, json requests, server-side) and consolidates the types.
- Ensures selective field forwarding happens for attachment fields. Currently a malicious user can manipulate our code to add any number of of fields (spam) inside the attachment request and this would be forwarded to the contact-us-api lambda.
- increases the character limit for the subject. Longer subjects were getting clipped leading to some confusion for our CSRs.

Contact Us form fixes and tweaks

---

app/server/contactUsApi.ts

If the user doesn't attach a file along with the form then the attachment object passed through to the `buildContactUsReqBody` function will be undefined, which is where this bug kicks in, trying to access a property of undefined. 
Solution is to use optional chaining to avoid trying to access property of undefined attachment object.

[RB] - fix contact us buildContactUsReqBody function to stop 400 errors

---

app/client/components/helpCentre/helpCentreConfig.ts

Updates to the help centre config:
- update the link for the `I have an Apple/iTunes subscription that I need help with` option
- update the copy for the `I need to report a bug with your app/website` option

[RB] - help centre config link change and question copy change

---

app/client/components/help.tsx

Now that the help centre is live there is no need to duplicate it's content in the help page in MMA. 
This pr replaces the old content with links to popular questions, a link to the help centre and links to the call centre contact details and contact us form
Before            |  After

[RB] - remove old help page content. Replace with help centre context

---

app/client/components/header.tsx

Don't show the 'My Account' header for 'public' routes (routes that don't go through the identity sign in process)

[RB] - 'My Account' header display

---

app/client/components/helpCentre/helpCentre.tsx

Increase the font size of the `How can we help you?` title in the help centre on mobile breakpoints

[RB] - increase title font size on mobile breakpoints

---

app/client/__tests__/components/accountoverview/contributionUpdateAmount.tsx
app/client/components/accountoverview/contributionUpdateAmount.tsx
app/client/components/accountoverview/contributionUpdateAmountForm.tsx
app/client/components/accountoverview/manageProduct.tsx
app/package.json
app/yarn.lock

The main point of this PR was to pull out the contributions amount update form into a separate component so we can use it during the cancellation flow. To do that `ContributionUpdateAmountForm` was renamed to `ContributionUpdateAmount` and the form part of that was pulled out into a new (albeit with an old name!) `ContributionUpdateAmountForm`. 
I also took the oportunity to update the form itself. We've now got 'frequency buttons' (e.g $3 per month) and we're using source for choice cards + text input. We've also got the weekly breakdown (e.g. Contributing £3 works out as £0.69 each week). There were also some small tweaks to padding.

Refactor + update contributions amount update form

---

app/client/components/analytics.tsx

Puts Google Analytics behind consent. It also converts the `AnalyticsTracker` components to use hooks.
Most of the changes in the PR are related to the conversion to hooks. The parts that are specifically about putting GA behind consent are the parts inside the `useEffect` and the `cmpIsInitialised`. The behaviour now will be to wait until the first consent signal is obtained (meaning the CMP is initialised) before starting to track the page views (bit inside the component's return) and that's what the `cmpIsInitialised` state variable is used for. The way we suppress tracking events when consent is not present is by using the opt out mechanism described in [GA's documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out) on line 135.
Tested …

Put GA behind consent

---

app/client/components/callCenterEmailAndNumbers.tsx

Add xmas opening times to the callCentreEmailAndNumbers component
----------------------------------------
----------------------------------------

[RB] - add optional additional info p below opening times p

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/callCenterEmailAndNumbers.tsx

Remove the xmas and new years opening hours from the contact phone numbers and email component

[RB] - remove the xmas and new years opening hours

---

app/client/components/cancel/contributions/contributionsCancellationReasons.tsx

Update the copy for the feedback intro for contributions cancellations and remove the standard save body. The copy was repeated between the two.

Update feedback intro copy and remove standard save body

---

app/server/apiGatewayDiscovery.ts
app/server/routes/core.ts

* https://trello.com/c/lNk6s2s8/1766-hook-up-authentication-to-healthcheck-in-manage-frontend
* Occasionally, although with seemingly increasing frequency, upon deployment we fail to fetch API Gateway credentials due to AWS rate limiting which results in inability to talk to any of the APIs in the "service layer"
```
{"message":"ERROR loading host and api key for ...Rate exceeded","code":"Throttling", ...}
```
* This PR tries to hook up credentials resolution to the healthcheck such that instances do not spin up in the first place. Previously despite failure to load api keys it would still deploy the boxes which would result in users likely facing errors in MMA.
My flow is usually
1. Fresh janus
1. sudo nginx
2. start-api.sh members-data-api
2. cd app
3. yarn watch
4. failure injection by …

Add API Gateway key resolution to healthcheck

---

app/client/components/delivery/records/deliveryRecords.tsx

Over the Christmas period we allowed users to go through the delivery reporting journey without escalation to csr's.
This pr revert that change so that existing delivery problems get escalated as before.

[RB] - re-escalate existing newspaper delivery problems

---

app/package.json
app/yarn.lock

Upgrade the `aws-sdk` library following snyk's alert of a vulnerability being found.

Upgrade aws-sdk library

---

app/client/components/cancel/contributions/contributionsCancellationFeedbackForm.tsx
app/client/components/cancel/contributions/contributionsCancellationFeedbackFormThankYou.tsx
app/client/components/cancel/contributions/contributionsCancellationFlowFinancialSaveAttempt.tsx
app/client/components/cancel/contributions/contributionsCancellationFlowPaymentIssueSaveAttempt.tsx
app/client/components/cancel/contributions/contributionsCancellationReasons.tsx
app/client/components/cancel/contributions/utils.ts

Update "A payment issue" cancellation flow, as per [this card](https://trello.com/c/BbWsdbz6/2491-mma-cancellation-a-payment-issue-flow). There's some duplication here, but it didn't seem worth the effort to fight to get the current feedback form working for me so I created a new one (which will also use on the "I would rather do a [single/monthly/annual] contribution]" flow.

Update "A payment issue" cancellation flow

---

app/client/components/cancel/contributions/contributionsCancellationFlowPaymentIssueSaveAttempt.tsx

Redirect the user directly to the update payment method page, instead of to the account overview page.

Redirect straight to update payment method page

---

app/client/components/help.tsx

Renames the Help section page title to differentiate between the Help section on the MMA (old Help Centre) and the new Help Centre.

Rename Help section page title

---

app/client/components/cancel/cancellationFlow.tsx
app/client/components/cancel/cancellationReason.ts
app/client/components/cancel/contributions/contributionsCancellationReasons.tsx
app/client/components/cancel/stages/genericSaveAttempt.tsx

The two user facing changes are:
- Don't show "I would rather make an annual contribution" to annual contributors
- Don't show "I would rather make an monthly contribution" to monthly contributors 
To do this, I've added an optional (seemed less painfull to make it optional) `shouldShow` function to the `cancellationReason` model. I'm not super familiar with all the data types, but `ProductDetail` seemed like a reasonable choice for the argument here. It worked for this particular use case and I think it would work for potential future ones? (Very much open to suggestions here though!)

Don't show e.g "I would rather make an annual contribution" cancellation reason to annual contributors 

---

app/client/components/accountoverview/accountOverview.tsx
app/client/components/billing/billing.tsx
app/client/components/delivery/records/deliveryRecordsApi.ts

Older versions of Safari (versions 11 and 12) need the `credentials` and `mode` properties to be passed through with fetch calls.

[RB] - pass credentials explicitly through with fetch calls for older versions of safari

---

app/package.json
app/yarn.lock

Upgrade the consent-management-platform library to version 6.11.2.
This version requires the [`@guardian/libs`](https://github.com/guardian/libs) to be imported. The CMP uses this to output log and debug information to the console using a subscriber system.
If we need to see CMP log information in the console we will have to first subscribe to it by running the following command in the console:
`window.guardian.logger.subscribeTo('cmp');`
To prevent the CMP from outputting logging information use the following command in the console to unsubscribe:
`window.guardian.logger.unsubscribeFrom('cmp');`
The following wiki page will be updated after this PR is merged:
- [wiki/Cookie Consent Banner](https://github.com/guardian/manage-frontend/wiki/Cookie-Consent-Banner)

Update CMP lib to v6.11.2

---

app/client/components/main.tsx
app/client/components/user.tsx
app/client/user.ts
app/server/html.ts
app/server/routes/frontend.ts

This PR removes the React server-side rendering. It still server-side renders the HTML that React renders now so it's easier to introduce the extra information we want on it (such as global variables, scripts, etc.)
We are working on code splitting the codebase as a way to alleviate the large bundle size it currently has. Code splitting becomes quite complex if you couple it with server-side rendering. However manage-frontend does not get have much need of server-side rendering at this point, so we are trialing removing it to more easily introduce code splitting.
Removing the server-side rendering from the project aggravates the problem of having a large bundle size, as it takes longer for users to see content. For that reason **this PR is not to be merged until the code splitting PR is …

Remove react server rendering

---

app/client/__tests__/components/delivery/records/deliveryRecords/deliveryRecords.tsx
app/client/__tests__/components/delivery/records/deliveryRecords/step1.tsx
app/client/components/accountoverview/accountOverview.tsx
app/client/components/accountoverview/manageProduct.tsx
app/client/components/billing/billing.tsx
app/client/components/cancel/cancellationFlow.tsx
app/client/components/contactUs/contactUs.tsx
app/client/components/delivery/address/deliveryAddressForm.tsx
app/client/components/delivery/records/deliveryRecords.tsx
app/client/components/help.tsx
app/client/components/helpCentre/helpCentre.tsx
app/client/components/holiday/holidaysOverview.tsx
app/client/components/identity/EmailAndMarketing/index.tsx
app/client/components/identity/PublicProfile/index.tsx
app/client/components/identity/Settings/index.tsx
app/client/components/page.tsx
app/client/components/pageSkeleton.tsx
app/client/components/payment/update/updatePaymentFlow.tsx
app/client/components/user.tsx
app/jest.config.js
app/tsconfig.json

This PR introduces route based code splitting using React Lazy and Suspense. A Suspense fallback component has also been added which acts as an intermediary view whilst each separate code chunk is loading. React Lazy works with files that have a default export so the relevant pages have been updated.
The tsconfig `module` value has been changed from `commonjs` to `ESnext` in order to get the code splitting to work as expected, with the previous setting webpack had trouble separating chunks. As a result of changing the tsconfig the jest configuration has also been updated to ensure it uses commonjs.
- the parsed bundle size was 1.32mb and is now 1.06mb
- the gzipped bundle size was 362kb and is now 303.19kb
There was a risk of users seeing a blank whilst the page was loading. We have …

Introduce code splitting

---

app/client/components/delivery/records/deliveryRecords.tsx

The FormError component replaces the existing error message code in deliveryRecords with relevant content passed down in the form of props. This has been done to further simplify and standardise our codebase.

Refactor deliveryRecords.tsx to use our FormError component

---

app/server/apiGatewayDiscovery.ts
app/server/middleware/identityMiddleware.ts
app/server/routes/core.ts

Fix for [Add API Gateway key resolution to healthcheck #559](https://github.com/guardian/manage-frontend/pull/559)
Tested in CODE by forcing 500 result from `authKeysAreFetchableMemoisedHealthcheck` and observing deployment fail.
Arguably healthcheck logic could be made clearer however since `withIdentity` is used beyond just the healtcheck any refactoring is perhaps best left for a dedicated PR.

Check if auth keys are fetchable before identity healthcheck

---

app/server/apiGatewayDiscovery.ts

- CODE has no permissions to fetch PROD keys.
- Fix https://github.com/guardian/manage-frontend/pull/577
Try deploying to CODE.

Parameterise keys healthcheck by stage

---

app/client/components/accountoverview/manageProduct.tsx
app/shared/productTypes.tsx

We are no longer allowing members to change their tier via membership.theguardian.com so this PR removes the 'change tier' button from the manage product page. 
As membership was the product which had a change tier option I have also removed it from the ProductType type.
Log into manage with an account that has a membership and click the 'manage membership' button, you should no longer see the 'change tier' button on the manage product page.
This is just a tidy up exercise

Remove the changeTier field from ProductType

---

app/client/components/helpCentre/knownIssues.tsx

This PR adds an optional link to the an issue alert. This means we can now provide further information to the user about the issue should we choose to.
Before
After

Add functionality for links in Known Issues banner

---

app/client/HelpCentrePage.ts
app/client/MMAPage.ts
app/client/__tests__/components/header.tsx
app/client/components/HelpCentrePage.tsx
app/client/components/HelpCentrePageSkeleton.tsx
app/client/components/MMAPage.tsx
app/client/components/MMAPageSkeleton.tsx
app/client/components/header.tsx
app/client/components/help.tsx
app/server/routes/frontendCommon.ts
app/server/routes/helpCentreFrontend.ts
app/server/routes/index.ts
app/server/routes/mmaFrontend.ts
app/server/server.ts
app/webpack.common.js

This PR splits our single bundle (user.js) into an MMA bundle and Help Centre bundle to improve bundle size. MMA's bundle size has a minimal reduction but the Help Centre bundle shrinks significantly. This will provide a better experience for users accessing the Help Centre and the Contact Us form.
It also adds [magic comments](https://webpack.js.org/api/module-methods/#magic-comments) to the dynamic imports that instruct Webpack on how to name the chunk produced byt that import. This will make it easier for us to debug any issues that involve the chunks.
Note: More can be done to further decrease the bundle sizes, especially for the Help Centre. As it stands there is still unnecessary code being imported into each bundle because of how our code e organised.I will raise a separate PR with …

Split MMA and HelpCentre bundles

---

app/client/components/HelpCentrePage.tsx
app/client/components/HelpCentrePageSkeleton.tsx
app/client/components/contactUs/contactUs.tsx
app/client/components/help.tsx
app/client/components/helpCentre/helpCentre.tsx
app/server/server.ts
app/shared/__tests__/requiresSignin.ts
app/shared/requiresSignin.ts

The Contact Us form is part of the Help Centre. However, because it was created first it got its own separate URL. This PR moves it from `https//manage.theguardian.com/contact-us` to `https://manage.theguardian.com/help-centre/contact-us`.

Move Contact Us into Help Centre

---

app/client/components/accountoverview/manageProduct.tsx
app/client/components/identity/EmailAndMarketing/ConsentSection.tsx
app/client/components/identity/EmailAndMarketing/index.tsx
app/client/components/identity/idapi/consents.ts
app/client/components/identity/models.ts
app/shared/productTypes.tsx

This pr is the manage-frontend part of the wider soft-opt in work. The scope of this pr is the loading of the new consents endpoint from identity api and displaying of relevant soft opt in's dependent on what products the user has. 
Users should be able to see which emails they are opted into and out of and be able to opt in and out of them.
**Until the other parts of the soft-opt in work in support-frontend (work to opt users in, on product acquisition) and support-service-lambdas (work to opt users out when they reach their cancellation effective date) are done, then the new opt ins should not be visible to the user. This is handled crudely in the code using the following boolean in** `client/components/identity/EmailAndMarketing/ConsentSection.tsx`
example of the new opt ins (they will …

Soft opt ins

---

app/client/components/cancel/cancellationContributionReminder.tsx
app/client/components/cancel/cancellationSummary.tsx
app/package.json
app/server/reminderApi.ts
app/server/routes/api.ts
app/shared/productTypes.tsx
app/yarn.lock

Update the cancellation confirmed screen for recurring contributions to give users the option to sign up for a reminder in the future.

Add reminder sign up at end of contribution cancellation flow

---

app/client/components/cancel/cancellationContributionReminder.tsx

Send country code in create reminder request. The endpoint was initially getting this data from a header set by fastly. However, becaue this request is proxied via the manage backend, the location is the location of the AWS instance that serves that request, not the user. Now we send the country too which the reminder endpoint will use over the fastly header

Send country code in create reminder request

---

cfn.yaml

this makes it easier to understand the AWS console, also for reserved instances/trusted advisor

add instance name to ASG

---

app/client/components/HelpCentrePageSkeleton.tsx
app/client/components/MMAPageSkeleton.tsx
app/client/components/contactUs/contactUs.tsx
app/client/components/helpCentre/helpCentre.tsx
app/client/components/helpCentre/knownIssues.tsx
app/client/components/sectionHeader.tsx
app/client/components/sectionPageContainer.tsx

This updates the grid placement and text content for the landing and contact us pages. 
MMA and help centre page skeletons have also been updated to handle a trailing slash for each endpoint.

Update help centre landing page and contact us layout

---

app/package.json
app/yarn.lock

Upgrades `url-parse` to v1.5.1 due to snyk sending a vulnerability alert. Also upgrades `@types/url-parse` to v1.4.3.

Upgrade url-parse to v1.5.1

---

.github/workflows/snyk.monitor.yml
.github/workflows/snyk.test.yml
app/package.json

This PR removes snyk from the build step and moves it into a GitHub action
`snyk monitor` will run on any push to main. `snyk test` will run on all other branches. This will make it so our builds aren't blocked in case a vulnerability is found, which means we won't have to ignore them in the snyk policy. The snyk action is not required to pass for a PR to be merged. It's merely informative.
In a separate PR I will reset snyk's policy settings to remove the ignores we've been adding, now that it won't block the builds.
Note: Running `snyk wizard` will prompt to add a `snyk test` step to our `yarn test` script. This will no longer be necessary.

Remove snyk from the build steps

---

app/client/components/cancel/cancellationContributionReminder.tsx

Send an ophan event when the set reminder component is viewed. This is to allow us to more easily calculate a 'conversion rate' for one of our data studio dashboards.

Send ophan event on reminder view

---

app/client/components/analytics.tsx
app/client/components/gaStub.tsx
app/server/html.ts

This PR changes our analytics so they do not load any script until after consent has been obtained. This avoids race conditions as well as tracking through http requests.

Avoid loading GA unless consent has been obtained

---

app/package.json

Removes this `--skipLibCheck` flag from the `type-check` script.
Follows on from #389 which removed hundreds of type errors relating to `@typoes/react`, and subsequent PRs that remove `react-stripe-elements` and upgrade `jest`.
```sh
$ yarn type-check
```
Difficult, but I expect it would be useful at dev time to catch type issues with third party libs.
This could conceivably increase build time as all `*.d.ts` files from `node_modules` are now included in the compilation process. From testing, this adds about 3-5 seconds onto the build time.
However I think the increased integrity from integration testing third party libs is likely to be worth it.
No visual changes

Remove --skipLibCheck

---

cfn.yaml

This pr is to change the EC2 instance types from t3.small to t4g.small and also to update the instance OS from Ubuntu Xenial to Ubuntu Bionic (ARM).
A new recipe has been created in amigo `manage-frontend-arm` which is a clone of the original `manage-frontend` with the update to the OS and subsequent ARM version update to the node binary. Once this pr has been merged and monitored the original recipe can be deleted.
Cloudwatch logs should be monitored for any errors. Also worth checking the CPU usage of the instances to make sure it is not too high. (has already been checked in CODE, but with hardly any traffic)

[RB] - update cloudformation instance update to include prod

---

cfn.yaml

There's currently a major review of the guardian's security practices under the cyber security programme. One of the projects in this programme is to install a vulnerability scanner called Wazuh in guardian ec2 instances.
This patch enables Wazuh to work by
* Opening ports 1514 and 1515 for outbound traffic
* Giving permission to the instance to call describe-tags,
so the agent can identify itself in a human readable way with 
the wazuh server.
Deploy to CODE and see if the wazuh agent successfully connects with the central server 
Works in code ✅
Wazuh will start reporting vulnerabilities to infosec!
CFN could be wrong and cause downtime.

Patch in necessary permissions for wazuh

---

app/client/components/cancel/cancellationContributionReminder.tsx
app/client/components/identity/EmailAndMarketing/ConsentSection.tsx
app/client/components/identity/idapi/supportReminders.ts
app/client/components/identity/identity.ts
app/client/components/identity/models.ts
app/server/reminderApi.ts
app/server/routes/api.ts

Add a support reminder consent to the email reminders page. Removing this consent will cancel *all* pending reminders (both recurring and one-offs). Re-consenting will reactivate *only* their recurring reminder. A user that has never set a recurring reminder will not see this consent. 
**DO NOT MERGE** until after: https://github.com/guardian/members-data-api/pull/508 (this updates endpoint in mdapi)

Add support reminder consent to the email prefs page

---

app/client/components/helpCentre/HelpTopicBox.tsx
app/client/components/helpCentre/helpCentreConfig.ts
app/client/components/helpCentre/helpCentreMoreTopics.tsx
app/client/components/helpCentre/helpCentreStyles.tsx

Shared styling for the help centre is moved into a shared file and imported where necessary. A configuration object is added to the help centre in preparation for use in the upcoming help centre navigation component.

Update shared help centre styles and config

---

.github/workflows/snyk.yml

This PR refactor the Snyk GitHub Action. Instead of two different steps that run Snyk (one for main branch and another for all other branches), it has a single snyk step that runs either `test` or `monitor`, depending on the branch.
- It should now be easier to understand the default run mode (`snyk test`) and the alternative one for main branch (`snyk monitor`).
- Making changes to how we run Snyk should now only require editing one step.

Refactor Snyk GH Action

---

app/client/components/helpCentre/helpCentreNav.tsx

This includes a navigation component for the help centre which will be used to navigate between topics. Not currently in use.
| Mobile | Desktop |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/44685872/110486500-9c69a480-80e4-11eb-8526-ddb07d96dd22.png) | ![image](https://user-images.githubusercontent.com/44685872/110486555-a8556680-80e4-11eb-9d14-a513cb77d247.png) |

Create help centre nav component

---

app/client/components/helpCentre/helpCentreHeader.tsx
app/client/components/svgs/theGuardianLogo.tsx

This PR fixes the alignment of the help centre header on mobile
| ![image](https://user-images.githubusercontent.com/44685872/110959354-83136300-8345-11eb-94ed-0deeaad81479.png) | ![image](https://user-images.githubusercontent.com/44685872/110959185-5a8b6900-8345-11eb-94e1-605131e86663.png)|

Help centre header styling updates

---

app/client/components/contactUs/techIcon.tsx
app/client/components/svgs/commentsIcon.tsx
app/client/components/svgs/newspaperIcon.tsx
app/client/components/svgs/newspaperVoucherIcon.tsx

This PR centers the contact us form svg icons in their respective containers
|  ![image](https://user-images.githubusercontent.com/44685872/110955753-d2579480-8341-11eb-9314-ac197de28245.png) | ![image](https://user-images.githubusercontent.com/44685872/110955686-c23fb500-8341-11eb-9cd0-001a13c6db1e.png) |

Realign contact us form icons

---

app/client/components/helpCentre/knownIssues.tsx

This adds top padding to the known issues section and removes inline styling
| Before | After |
| ![image](https://user-images.githubusercontent.com/44685872/110973241-e5279480-8354-11eb-8866-43e79b2cf7d3.png) | ![image](https://user-images.githubusercontent.com/44685872/110973274-f2dd1a00-8354-11eb-8bc9-de3180063dc9.png) |

Adjust the spacing of the known issues section in the help centre

---

app/client/components/HelpCentrePage.tsx
app/client/components/helpCentre/BackToHelpCentreButton.tsx
app/client/components/helpCentre/HelpCentreTypes.ts
app/client/components/helpCentre/HelpTopicBox.tsx
app/client/components/helpCentre/helpCentre.tsx
app/client/components/helpCentre/helpCentreArticle.tsx
app/client/components/helpCentre/helpCentreConfig.ts
app/client/components/helpCentre/helpCentreLandingMoreTopics.tsx
app/client/components/helpCentre/helpCentreMoreTopics.tsx
app/client/components/helpCentre/helpCentreNav.tsx
app/client/components/helpCentre/helpCentreSingleTopic.tsx
app/client/components/helpCentre/helpCentreStyles.tsx
app/client/components/helpCentre/helpCentreTopic.tsx
app/client/components/sectionContent.tsx
app/server/helpCentreApi.ts
app/server/routes/api.ts
app/shared/requiresSignin.ts

This PR implements the Topic and Article pages, as well as corresponding endpoints.
The endpoints fetch the corresponding file from S3 and serve it as the body of the response. The page read the response from the endpoint to render the Topic or Article.

Help Centre Topic & Article pages

---

app/package.json
app/yarn.lock

Upgrades the `@guardian/consent-management-platform` to the latest version (v6.11.3), fixing the issue reported in guardian/consent-management-platform#412
Also upgrades `@guardian/libs` to the latest version.

Upgrade CMP to v6.11.3

---

app/client/components/scrollToTop.tsx

Fixes a bug introduced when we moved the Contact Us path from `/contact-us/` to `/help-centre/contact-us/` in #585 and forgot to update the exception in `scrollToTop`.
This bug made the page jump to the top when a user made a selection in the form.

Fix scrollToTop incorrectly triggering in the Contact Us form

---

app/client/components/contactUs/subTopicForm.tsx

Fixes the 'Failed prop type' React error in the Contact US form by moving the `onChange` handler from the `fieldset` into the `Radio` component. 
Full error description: ```Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.```

Fix 'Failed prop type' React error in Contact Us form

---

app/client/components/HelpCentrePage.tsx

This PR makes the Help Centre's article and topic pages accessible so they can be tested in PROD. Given that they are not linked to from anywhere crawlers should not pick up on them (we don't want them to for now) and users shouldn't stumble upon them.

Make article and topic pages available

---

cfn.yaml

To allow the bucket's access to be restricted.

Give read access to membership-dist bucket

---

app/client/components/identity/idapi/supportReminders.ts

The `api/reminders/status` introduced in PR #604 did not include the fix introduced in PR #572 so users with older Safari versions accessing the Email & Marketing section of MMA were seeing an error and were unable to change their settings. This PR adds the fix to the relevant endpoint and restores access.

Explicitly pass credentials on fetch requests

---

app/server/html.ts

Apparently, without a `lang` attribute screen readers will interpret text as being in the default language.
https://www.w3.org/WAI/WCAG21/Understanding/language-of-page
I'm not sure whether that's true but this is my first PR in the repo!

Add lang attribute to docs

---

app/client/components/helpCentre/helpCentre.tsx
app/client/liveChat.ts
app/shared/globals.ts

This adds in a script to test the live chat functionality when a certain query parameter and value is included.
When you navigate the site the query string is erased so to to save the flag set in the URL param the key value pair is added to session storage. 
- Navigate to the help centre on manage front end ```/help-centre```
- Add the following query parameter to the url ```?liveChat=1```
- You should then see the "Agent Offline" button appear in the bottom right corner of the screen
- Change the value of the liveChat parameter in the url to anything but 1 and the button should not appear

Integrate live chat

---

app/client/components/identity/EmailAndMarketing/ConsentSection.tsx

The Soft Opt-In features in MMA sit behind a sort of feature switch introduced in #587. This PR removes that switch so that these features can be made permanently available to our users ahead of the Soft Opt-In emails starting to be sent out tomorrow.
Sign in with an account that has active products and the email preferences page should show options to activate/deactivate the Soft Opt-Ins assigned to the active products.

Permanently activate Soft Opt-In feature

---

app/client/components/HelpCentrePage.tsx
app/client/components/helpCentre/helpCentreArticle.tsx
app/client/components/helpCentre/seoData.tsx

This adds some quite meagre structured data to Help Centre articles for search engine results.
It clears the data on all Help Centre pages and then creates a new element containing the structured data for articles.
This has been tested in Google's [rich results testing tool](https://search.google.com/test/rich-results):
And also in the [Schema markup validator](https://validator.schema.org/):

Add data for structured search results

---

app/client/components/helpCentre/knownIssues.tsx

Updates the design of the Help Centre Alert feature so that this component complies with design and similar features elsewhere on the site.
| ![image](https://user-images.githubusercontent.com/44685872/120014355-de1a3500-bfd9-11eb-947d-9653419936fc.png) | ![image](https://user-images.githubusercontent.com/44685872/120014027-7368f980-bfd9-11eb-84eb-2bd8b3908734.png)  |

Redesign known issues section of the help centre

---

app/client/components/helpCentre/helpCentreArticle.tsx

Name seemed to have been copied from `helpCentreTopic`.

Correct name of Help Centre article

---

app/server/routes/core.ts

This should regulate well-behaved bots indexing our content to ensure that, in production, they only try to access the new Help Centre content.
In pre-prod stages no content is allowed to be indexed.
Prod:
```
UserAgent: *
Allow: /help-centre
Allow: /help-centre/
Disallow: /
User-agent: AdsBot-Google
User-agent: AdsBot-Google-Mobile
Disallow: /
```
Pre-prod:
```
UserAgent: *
Disallow: /
```
See:
* https://www.theguardian.com/robots.txt
* https://developers.google.com/search/docs/advanced/robots/create-robots-txt
* https://developers.google.com/search/docs/advanced/crawling/overview-google-crawlers
* https://en.wikipedia.org/wiki/Robots_exclusion_standard

Add robots.txt to control site indexing

---

app/server/routes/core.ts

There was a small bug in my logic!
[Environments](https://github.com/guardian/manage-frontend/blob/main/app/server/config.ts#L23-L26) is just an enum so `Environments.PRODUCTION` is always false.

Fix logic to choose a robots.txt

---

app/server/awsIntegration.ts
app/server/routes/core.ts

This change enables us to [read a text/plain file from S3](https://github.com/guardian/manage-frontend/compare/kc-sitemap?expand=1#diff-62a24087ea863ccce38811f99ae580255284a941e7a14330927046efd0413514R102-R119) and serve it.  
In particular, it gives us [a sitemap on the path `/help-centre/sitemap.txt`](https://github.com/guardian/manage-frontend/compare/kc-sitemap?expand=1#diff-86bcdb7857d4c2fdb564aac4765f0a284e62fae9452da60431d0fa3ede65c357R48-R70).
This sitemap is specifically for help-centre content, hence it isn't at the site root.
See also:
* guardian/manage-help-content-publisher#114
* guardian/manage-help-content-publisher#119
* https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap

Serve Help Centre sitemap from S3

---

app/client/components/accountoverview/accountOverviewCard.tsx
app/client/components/billing/invoicesTable.tsx
app/client/components/payment/paymentDetailsTable.tsx
app/client/components/payment/sepaDisplay.tsx
app/client/components/payment/update/currentPaymentDetails.tsx
app/shared/productResponse.ts

Add support for SEPA payment method. This PR depends on a couple of other PRs when fetching user data: 
- `mdapi` PR: https://github.com/guardian/members-data-api/pull/589 
- `invoicing-api` PR: https://github.com/guardian/invoicing-api/pull/71
Specifically, this PR makes MMA correctly display a users payment method for SEPA. A user can update their contribution amount, but cannot switch payment method.

Add support for SEPA

---

app/client/components/helpCentre/knownIssues.tsx

The outer container for the knownIssues component was rendered regardless of whether there were no issues i.e. when `issuesData` was empty. This added unnecessary markup and css to the DOM when there were no issues. This PR updates the component to conditionally return markup dependent on whether there are issues.

KnownIssues container fix

---

app/artifact.json
cfn.yaml

Updates the build compression to ZIP and fixes a deployment bug introduced in #653.
The library we upgraded to in #653 made us change the compression of the built files to tar (tgz isn't supported). However we did not update the bash scripts in the CloudFormation to reflect this change. This caused the deployment to succeed but instead of deploying the latest build (inside `manage-frontend.tar`) it was deploying the last version deployed before #653 was merged (inside `manage-frontend.tgz`). This was detected because @prout-bot (🙇 ) warned us that the PR was overdue on PROD. No other PRs were merged since so that was the only merge affected. This bug is now fixed.
While researching the cause of this bug we realised that while the average compressed file size was 16.5MB when using tgz …

Fix deployment pipeline/update compression used for build files

---

app/client/components/helpCentre/helpCentreArticle.tsx
app/client/components/svgs/thumbsUpIcon.tsx

This adds the  'Did you find the information you need?' feedback widget at the bottom of Article pages. The buttons track the user's click
| Desktop  | Mobile | 
| ![image](https://user-images.githubusercontent.com/44685872/122370055-a6f2d000-cf56-11eb-97f6-c3542d1d8abd.png)  | ![image](https://user-images.githubusercontent.com/44685872/122370104-b2de9200-cf56-11eb-9ec6-c8c62e21d9e7.png) |

Add help centre article feedback widget

---

app/client/__tests__/dates.ts

When comparing 2 dates like the following:
`dateIsSameOrAfter(new Date(), new Date())`
There seems to be a small chance the the 2 dates will not be the same, eg off by a fraction of a second.
Where 2 dates that are supposed to be equal are being compared in the tests I have set them explicitly to be the date of judgement day in Terminator!
This only affected the test run and has no effect on the code.

[RB] - set explicit date values in tests when comparing

---

app/client/components/helpCentre/helpCentreArticle.tsx

This adds custom css for help centre article links.

Add custom css for help centre article links

---

app/client/components/helpCentre/helpCentreConfig.ts
app/client/components/helpCentre/helpCentreTopic.tsx
app/client/components/svgs/helpSectionIcons.tsx

Sync the `website` and `subscriptions` id's in the `helpCentreConfig.ts` to match the json object structure in s3. 
Update the highlight of the selected nav item when navigating between options so that the selected option is always highlighted

[RB] - Help centre topic nav fix

---

app/client/components/helpCentre/helpCentreArticle.tsx

Add callCenterEmailAndNumbers component to the bottom of the help centre article pages

[RB] Add callCenterEmailAndNumbers component to the bottom of the help centre article pages

---

app/client/components/helpCentre/helpCentreHeader.tsx

This PR fixes the alignment issues of the help centre header for signed out users by removing superfluous code. 
| ![image](https://user-images.githubusercontent.com/44685872/126318478-c3b6fafd-6d0a-4e54-8f26-98a6613e2022.png) | ![image](https://user-images.githubusercontent.com/44685872/126318363-60ee900c-7c1d-4bba-b075-f53526f85b74.png)  |

Help centre header alignment fix

---

app/client/components/liveChat/liveChat.tsx

As a consequence of the following work:
https://trello.com/c/D5K0PO1h/2446-live-agent-create-dedicated-site
The embed url needs updating slightly 🔗 
`https://guardiansurveys.secure.force.com/liveagent` and `https://dev1-guardiansurveys.cs88.force.com/liveagent` are the new urls.
The other changes are linting corrections that override a previous forced push

[RB] - update to liveagent embed url

---

app/client/components/helpCentre/HelpTopicBox.tsx
app/client/components/helpCentre/helpCentreConfig.ts

This rewrites all the links to legacy help pages from the Help Centre landing page so that they point at new pages in the Help Centre.
Eventually, this page will be published in the same way as the article and topic pages but at the moment it has to be built manually.
I've tested the links in Code.

Link to new Help Centre articles and topics

---

app/server/routes/core.ts

This is to give me access to the [Google Search Console](https://search.google.com/search-console) for manage.theguardian.com.
I'm using the [HTML file upload](https://support.google.com/webmasters/answer/9008080) method.  This appears to be the only way to get access to the search console for a subdomain where the root is authenticated.
Tested access to the file on Code.

Add Google Search Console verification file

---

app/server/routes/core.ts

A small oversight in the robots.txt file meant that the sitemap couldn't be read.
Google Search Console told me that Google couldn't read the sitemap and [this tool](https://www.google.com/webmasters/tools/robots-testing-tool) told me why.

Give all bots access to sitemap

---

app/server/routes/core.ts

Currently, Google bots are only indexing the serverside-built content of pages because they are blocked from accessing `/static/helpcentre.js`.  This is to give access to static resources so that all pages can be meaningfully indexed.

Allow bots to index pages built on clientside

---

app/server/routes/core.ts

Google still can't quite build clientside-composed pages as it needs access to api paths.
If this doesn't work, I'll give full access to the site.  That was how it was until last week anyway so shouldn't cause any unexpected problems.

Enable bots to access API to load pages

---

app/client/components/help.tsx
app/client/components/identity/IdentityLocations.ts

updates old `www.theguardian.com/help` links to the new `manage.theguardian.com/help-centre` urls.
It does exactly what is says on the tin.

[RB] - update old help centre links to the new urls

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/footer/footerlinks.tsx

The [article from 2016](https://www.theguardian.com/info/2016/jul/27/modern-slavery-and-our-supply-chains?INTCMP=NGW_FOOTER_UK_GU_MODERN_SLAVERY_ACT) which contains a link to an old copy of the modern slavery statement is no longer used on dotcom. This PR replaces that footer link with a link to the pdf to keep parity with [theguardian.com](https://www.theguardian.com). 
Click the link and open a pdf.
We open a pdf.
The pdf location may change in future.

Change modern slavery link to the new pdf

---

app/package.json
app/yarn.lock

Upgrades `url-parser` to v1.5.3 to address a security vulnerability reported by Snyk.

Upgrade url-parser to v1.5.3

---

app/client/components/liveChat/liveChatCssOverrides.ts

Fixes the background colour of secondary button backgrounds for pairs of buttons inside `dialogButtonContainer` container.
- log into the dev salesforce envirmonment
- from the App Launcher menu select LiveChatTestApp
- in the omni channel window set your self as Busy
- run manage locally and visit the help center with the live chat url param: `https://manage.thegulocal.com/help-centre/?liveChat=1` 
- click on the `Start live chat` button
- fill in the pre-chat form
- click on the `Start chatting` button
Before                           |  After

[RB] - secondary buton styling for 'agents offline' section

---

app/.storybook/.babelrc
app/.storybook/main.js
app/.storybook/preview.js
app/client/components/helpCentre/helpCentrePhoneNumbers.stories.tsx
app/package.json
app/webpack.common.js
app/yarn.lock

- Ran [`npx sb init`](https://storybook.js.org/docs/react/get-started/install) in the `app` directory. This installed Storybook and set up some basic boilerplate
- Added a `.babelrc` that ensures Storybook runs the [same Babel presets and plugins](https://github.com/guardian/manage-frontend/blob/edbd98af74a474740c11830fcaa74951d2bb65e4/app/webpack.common.js#L30-L42) that the main app uses. This was mainly to ensure Storybook understands Emotion's CSS prop.
- Added a `HelpCentrePhoneNumbers` story as a demo / proof of concept.
- Told babel preset env to explicitly use v3.16 of core-js. This is in response to [bundle time warnings](https://teamcity.gutools.co.uk/viewLog.html?buildId=681379&buildTypeId=memsub_AccountFrontend_Build&tab=buildLog&_focus=644) and resulting build failures. I'm …

Add storybook

---

app/client/components/helpCentre/helpCentreEmailAndLiveChat.tsx
app/client/components/liveChat/liveChat.tsx
app/client/components/liveChat/liveChatCssOverrides.ts
app/client/components/svgs/loadingCircleIcon.tsx

The salesforce javascript script `esw.min.js` should only be added/loaded when the user has clicked on the `Start live chat` button on the help center landing page. 
The `Start live chat` should show the loading state of live chat while the script loads and the chat window is instantiated.
- visit https://manage.thegulocal.com/help-centre/?liveChat=1
- open up dev tools and the network tab
- confirm that `esw.min.js` isn't in the network tab
- click on Start live chat button
- have another look at the network tab, `esw.min.js` should now be there
- party 🎉

live chat async js script load

---

app/client/components/liveChat/liveChatCssOverrides.ts

The live chat window should have overflow-y set to scroll on smaller breakpoints where the content is taller than the window height.

[RB] - livechat overflow-y scroll for small breakpoints

---

app/client/components/liveChat/liveChatCssOverrides.ts

Consolidate font sizes of start chat and chat ended system messages

[RB] - consolidate font sizes of start chat and chat ended system messages

---

app/client/components/helpCentre/helpCentreNav.tsx
app/client/components/sectionContent.tsx

- Hover state of left hand nav should have a light grey colour
- mobile topic selection nav should be closed on page load and on selection of topic
- mobile topic selection nav should be sticky
- left hand nav should be sticky

[RB] - help centre nav amends

---

app/client/components/liveChat/liveChat.tsx

Remove iframe source param passed through to the initESW function the second/subsequent time a live chat message is established. This resolves a cross origin postMessage error when running in the salesforce dev environment. eg:
```Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://service.force.com’) does not match the recipient window’s origin (‘https://gnmtouchpoint--dev1.my.salesforce.com’).```

consecutive live chats bug fix

---

app/client/components/liveChat/liveChatCssOverrides.ts

Adds custom css styling to the queue position state of live chat.
- log into the dev salesforce envirmonment
- from the App Launcher menu select LiveChatTestApp
- in the omni channel window set your self as Available - chat
- visit https://manage.thegulocal.com/help-centre/?liveChat=1
- click on Start live chat button
- fill in the pre chat form
- click on the 'Start chatting' button
- Before the chat starts you should see something similar to the below image

[RB] - queue position number styles

---

app/client/components/helpCentre/helpCentre.tsx
app/client/components/helpCentre/helpCentreEmailAndLiveChat.tsx
app/client/components/liveChat/liveChatPrivacyNotice.tsx

Adds live chat privacy notice to the bottom of the help center home page along with an anchor link further up the page. Hidden behind url param 'feature flag'
- visit https://manage.thegulocal.com/help-centre/?liveChat=1
- scroll down to the bottom of the page to see the privacy notice

Live chat privacy notice

---

app/client/components/liveChat/liveChatPrivacyNotice.tsx

This is a very minor copy tweak updating references to the data privacy _note_ to data privacy _notice_ instead (as requested by the DPO team via their 9 September email).
Check the copy is displaying as expected.
Here's what the page looks like with the updated copy:

Update 'data privacy note' references to 'data privacy notice'

---

app/client/components/helpCentre/helpCentreArticle.tsx
app/client/components/helpCentre/helpCentreStyles.tsx

Various design review amends to the help centre article pages:
- Width of main column
- Headline: font size and colour
- Subtitle: font size and colour
- Body text: font size and colour
- Spacing between text elements
- Spacing between page component
- Styling of list (indend, bullet point, spacing...)
https://www.figma.com/file/Ykab3YX9tU5PDByPOADrB5/SX---Help-Centre-MVP2?node-id=1461%3A96590
- visit one of the article pages:
- https://manage.thegulocal.com/help-centre/article/finding-articles-from-the-past-in-digital-format
- https://manage.thegulocal.com/help-centre/article/i-need-to-pause-my-delivery

[RB] - help centre article css amends

---

app/client/components/helpCentre/helpCentreSingleTopic.tsx

Design review amends to the help centre see all pages:
- Margin around see all ul list
- padding within list items
https://www.figma.com/file/Ykab3YX9tU5PDByPOADrB5/SX---Help-Centre-MVP2?node-id=1461%3A96590
- visit one of the see all pages:
- https://manage.thegulocal.com/help-centre/topic/delivery

[RB] - design review, spacing around subtitle and within ul list items

---

app/client/components/liveChat/liveChatCssOverrides.ts

Fixes a bug where only 1 button exists at the end of a conversation where previously there were 2 expected. Now uses even and odd slectors to ensure that the button background and text colours are correct.
- log into the dev salesforce envirmonment
- from the App Launcher menu select LiveChatTestApp
- in the omni channel window set your self as Busy
- run manage locally and visit the help center with the live chat url param: `https://manage.thegulocal.com/help-centre/?liveChat=1` 
- click on the `Start live chat` button
- fill in the pre-chat form
- click on the `Start chatting` button
- go back to salesforce and end the chat from there
- go back to manage and you should now see the close chat button with the correct button text colour
Before                           |  After …

[RB] - correct styling/text colour of the end chat button

---

app/client/components/liveChat/liveChatCssOverrides.ts

The agent speech bubbles in the live chat window are dark blue, the copy colour is white, which the anchor links should also be, along with underline text decoration.
- log into the dev salesforce envirmonment
- from the App Launcher menu select LiveChatTestApp
- in the omni channel window set your self as Busy
- run manage locally and visit the help center with the live chat url param: `https://manage.thegulocal.com/help-centre/?liveChat=1` 
- click on the `Start live chat` button
- fill in the pre-chat form
- click on the `Start chatting` button
- go back to salesforce and send a message to the user containing a url
- go back to manage and you should now see a link in the chat message window with the correct text colour and decoration
Before                           |  After …

[RB] - style anchor link colour and text decoration for agent messages

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/components/footer/footerlinks.tsx

The footer used on Manage contains links to 'Dating' and 'Discount codes' - both links are now redundant.
This PR removes these links.
Trello: https://trello.com/c/x9pyP8Fx
URL: https://manage.theguardian.com/

'Dating' and 'Discount codes' removed from Manage footer

---

app/shared/contactUsConfig.ts

This PR removes the "report vulnability" option from the contact us page.
This is needed because infosec prefer they are reported via the established channels.
https://manage.theguardian.com/help-centre/contact-us/tech
https://trello.com/c/UmqQxkMX

remove report vulnerability from contact us page

---

app/client/components/svgs/thumbsUpIcon.tsx

Safari does not support transformation of the base svg tag 😖. It does however support transform of a group (g) tag. This pr wraps the inner contents of the thumbs up icon in a g tag and moves the rotation transform from the parent svg tag into the g tag.
- visit an article page:
- https://manage.thegulocal.com/help-centre/article/i-need-to-pause-my-delivery

[RB] - fix svg transform rotate bug in safari

---

app/client/components/liveChat/liveChat.tsx

conditionally load the dev salesforce live chat sandbox or the prod version dependant on the manage client environment.
Add the `onSettingsCallCompleted` event listener which when loading the prod version of salesforce live chat seems to fire a lot quicker than the `onAvailability` event.

[RB] - load the dev sandbox live chat version if you are anywhere but on prod

---

app/client/components/helpCentre/BackToHelpCentreButton.tsx
app/client/components/helpCentre/helpCentreLandingMoreTopics.tsx
app/client/components/helpCentre/helpCentreMoreTopics.tsx
app/client/components/helpCentre/helpCentreStyles.tsx

Design review amends to the help centre faq/More topics page:
- Margin around 'Back to Help Centre' button
- Height of list items in accordian nav
- positioning of 'show/hide' and chevrons for list items
- borders for accordian
https://www.figma.com/file/Ykab3YX9tU5PDByPOADrB5/SX---Help-Centre-MVP2?node-id=1262%3A29200
- visit the more topics page:
- https://manage.thegulocal.com/help-centre/topic/more-topics

[RB] - Help centre FAQ/More topics page design amends.

---

app/client/components/accountoverview/accountOverview.tsx
app/client/components/accountoverview/contributionUpdateAmountForm.tsx
app/client/components/billing/billing.tsx
app/client/components/cancel/cancellationDateResponse.ts
app/client/components/cancel/caseCreationWrapper.tsx
app/client/components/cancel/caseUpdate.tsx
app/client/components/cancel/stages/executeCancellation.tsx
app/client/components/delivery/records/deliveryRecordsApi.ts
app/client/components/holiday/holidayReview.tsx
app/client/components/identity/idapi/supportReminders.ts
app/client/components/resubscribeThrasher.tsx
app/client/fetch.ts
app/client/productUtils.tsx

`credentials` and `mode` parameters were introduced in several fetch calls to avoid the Safari bug issued in this PR: https://github.com/guardian/manage-frontend/pull/572. This is a wrapper function that injects these parameters so they do not have to be written for every fetch call.
Tested visually through dev tools network tab using Safari 11 and 12 on Browserstack.
_Any suggestions on a better name for the function?_

Fetch wrapper function

---

cfn.yaml

Making 5xx alarm less sensitive to reduce noise and only alert for significant issues.

Upping the threshold for 5xx alarm to reduce noise

---

app/client/components/helpCentre/helpCentreConfig.ts

Remove typo in "Why am I still seeing banners/ads"

---

app/client/components/helpCentre/helpCentreEmailAndLiveChat.tsx

Opening hours for Live Chat are increasing. We believe we can remove opening hours entirely from the Live Chat component in the Help Centr
e.

Removing Live Chat opening hours copy

---

app/client/__tests__/components/dateInput.tsx
app/client/components/dateInput.tsx
app/client/components/datePicker.tsx

Updates the `DateInput` component so that December is displayed as 12 rather than 0. (Other months are not affected and already display correctly.)
As part of the fix the component has been converted from a class component to a functional component, the `defaultDate` and `selectedDate` props have been combined into a single `date` prop, and a basic test suite has been added.
Removing the `selectedDate` prop also fixes a separate bug where if you amend the chosen dates the date inputs will revert to showing the first available date rather than the selected dates.
Date inputs showing a first available date in December:
Selected dates are in December, but month is still shown as 0:
When amending the selected dates the date inputs revert to the first available date:
December correctly shown …

Refactor `DateInput` and fix month display bugs

---

app/client/components/identity/idapi/user.ts
app/client/components/identity/models.ts

- local phone number in the settings form is a number and needs to be converted to string before sending to IDAPI endpoint
Identity API is becoming less tolerant of numbers being passed in place of strings

 local phone number in the settings form is a number

---

app/client/__tests__/components/dateInput.tsx
app/client/__tests__/dates.ts

Currently our date tests pass on CI, but fail when ran locally.
This is due to calling the `toLocaleDateString()` method which uses the system's locale. On CI the locale appears to be `en-US` so this method returns dates with a `mm/dd/yyyy` format. eg. 25 December 2021 is returned as `12/25/2021`. Your local environment is likely to have the locale set to `en-GB` so dates are returned with a `dd/mm/yyyy` format. eg. `25/12/2021`.
This replaces calls to `toLocaleDateString()` with a `localiseDate` method that uses `Intl.DateTimeFormat` with the locale explicitly set to `en-GB` to format dates consistently without relying on the system's locale.
Additionally, instances of the `Date()` constructor being instantiated with year, month and day parameters have been replaced with ISO date strings …

Explicitly set date locale for consistent behaviour in dev and CI

---

app/package.json

The webpack dev server websocket connection has been failing since the webpack version bump. This appeared to be affecting  hot reloading and potentially some chunk loading errors (not noticed this error since implementing this fix).
Looks as though the socket-url param was wrong (missing the /ws path)

[RB] - update client web socket url to include missing /ws path

---

app/client/__tests__/components/payment/currentPaymentDetails.tsx
app/client/__tests__/components/payment/paymentUpdated.tsx
app/client/components/payment/update/paymentUpdated.tsx
app/shared/productResponse.ts

****NOTE: I recommend merging the two-step-flow PR first**
This is the new confirmation page when updating a payment method. Only styles and some refactoring of the JSX has been changed. Currently, the page looks different when the user recovers an expired payment method, and shows the message "We will take the outstanding payment within 24 hours, using your new card details." This is currently being re-thought and re-designed, so I will update this page when we've received reviewed designs.
Click on 'manage payment method' on a subscription in account overview. Use card number '4242 4242 4242 4242' to test successful payments. Stripe has many test numbers to test different error states and also 3D Secure/2 factor authentication: https://stripe.com/docs/testing. For Direct Debit, use …

Payments switching confirmation page

---

app/client/components/callCenterEmailAndNumbers.tsx

Update the UK phone number opening hours in the `callCenterEmailAndNumbers` component.
Allow multiple lines for more specific opening hours.

[RB JT] - amend call centre phone number opening hours

---

app/server/routes/frontendCommon.ts
app/server/routes/mmaFrontend.ts
app/server/stripeSetupIntentConfig.ts

Logging Stripe keys fetched from AWS as we believe they are not being returned properly.

log stripe public keys fetched from AWS

---

app/package.json
app/yarn.lock

This bumps the `@guardian/node-riffraff-artifact` package from `0.2.1` to `0.2.2` in order to update the `y18n` sub-dependency which has a high severity security vulnerability.

Patch version bump to `@guardian/node-riffraff-artifact` package

---

app/client/components/payment/update/card/Recaptcha.tsx

I noticed I was not removing the recaptcha token state upon expiry. This means that if the Recaptcha has expired after two minutes, and the user does not complete it, the generic error screen is shown and they have to refresh the page:
I've checked Sentry and fortunately this has only happened once over the last day it has been deployed. 
Link to the Sentry exception: https://sentry.io/organizations/the-guardian/issues/2875657110/?environment=theguardian.com&project=1208603&query=is%3Aunresolved
Have tested this manually and it correctly shows the 'Recaptcha has not been completed' error message.

Expired Recaptcha bug fix on card form

---

app/client/__tests__/components/payment/paymentUpdated.tsx
app/client/components/payment/update/Summary.tsx
app/client/components/payment/update/card/stripeCardInputForm.tsx
app/client/components/payment/update/dd/directDebitInputForm.tsx
app/client/components/payment/update/paymentUpdated.tsx
app/client/components/payment/update/updatePaymentFlow.tsx

The recovery message has been added back into the confirmation page. This message wasn't included in the initial deploy as UX work was being done on it, but has now been added back in. Previous code showing this message found here: https://github.com/guardian/manage-frontend/blob/15fe3b15c6597575c918cc62ae45f59586bc17f2/app/client/components/payment/update/paymentUpdated.tsx#L56

Recovery message added to payments confirmation screen

---

app/client/__tests__/__snapshots__/main.tsx.snap
app/client/__tests__/main.tsx
app/client/components/footer/footer.tsx

Fakes the current date when testing the `<Main>` component as this renders the `<Footer>` component which displays a copyright message with the current year. This is implicitly tested via a snapshot test so failed as the year rolled over to 2022. Faking the date will prevent this failing next year (and in subsequent years).

Fake date to avoid failure each new year

---

app/server/middleware/identityMiddleware.ts
app/server/routes/core.ts

…since HelpCentre needs to be available when identity is inaccessible 
PLUS don't 500 on endpoints which don't require signin
Co-authored-by: @jamesmockett 
Co-authored-by: @jonflynng 
When deployed in CODE with Identity down, help centre should be accessible, the rest of manage should 500.
Users can access manage during the upcoming identity downtime.

remove `withIdentity` from the healthcheck 

---

app/client/components/payment/update/PaymentFailed.tsx
app/client/components/payment/update/card/stripeCardInputForm.tsx
app/client/components/payment/update/dd/directDebitInputForm.tsx
app/client/components/payment/update/updatePaymentFlow.tsx

Style updates for error screens found here: https://www.figma.com/file/judOZzoY74FjzBdvu98Bvb/MMA-since-2020?node-id=6735%3A274068
I think the easiest way to do this is to run the branch locally and add `throw Error` on the first line of the try block of the executePaymentUpdate function: https://github.com/guardian/manage-frontend/blob/payments-form-style-updates/app/client/components/payment/update/updatePaymentFlow.tsx#L282

payment error screens styling

---

app/client/components/payment/update/CurrentPaymentDetail.tsx
app/client/components/payment/update/card/stripeCardInputForm.tsx
app/client/components/payment/update/dd/directDebitInputForm.tsx
app/client/components/payment/update/dd/directDebitLegal.tsx
app/client/components/payment/update/fieldWrapper.tsx
app/client/components/payment/update/updatePaymentFlow.tsx

UI updates to the payments form found here: https://www.figma.com/file/judOZzoY74FjzBdvu98Bvb/MMA-since-2020?node-id=6569%3A281466. 
Have also added vertical margin between the error messages which wasn't included when first pushing this live:

Payments form style updates

---

.github/workflows/chromatic.yml
app/client/components/dateInput.stories.tsx
app/client/components/footer/footer.stories.tsx
app/client/components/help.stories.tsx
app/client/components/helpCentre/helpCentre.stories.tsx
app/client/components/helpCentre/helpCentreArticle.stories.tsx
app/client/components/helpCentre/helpCentrePhoneNumbers.stories.tsx
app/package.json
app/yarn.lock

Adds Chromatic to enable visual regression testing. Changes are automatically published on push via a GitHub action.
`yarn chromatic` can be used to manually publish changes and start a new build. This relies on the `CHROMATIC_PROJECT_TOKEN` being set. The token can be found in the [`manage-frontend` project in Chromatic](https://www.chromatic.com/manage?appId=61eee3dabb99df003a4090fd&view=configure).
Stories are rendered with a ` 1200px` wide viewport by default, but additional viewport sizes have been added to a handful of stories to test responsive behaviour. The `<Footer>` component, for example, is tested at the `mobile`, `tablet` and `wide` breakpoints.
You can log in to [Chromatic](https://www.chromatic.com/builds?appId=61eee3dabb99df003a4090fd) with your GitHub account and view …

Add Chromatic

---

app/.eslintrc.js
app/client/__tests__/components/accountoverview/contributionUpdateAmount.tsx
app/client/__tests__/components/delivery/records/deliveryRecords/deliveryRecords.tsx
app/client/__tests__/components/delivery/records/deliveryRecords/step1.tsx
app/client/__tests__/components/header.tsx
app/client/__tests__/components/helpCentre/helpCentreContactOptions.tsx
app/client/__tests__/components/payment/stripe.ts
app/package.json
app/yarn.lock

Adds `eslint-plugin-jest` and minor error fixes. 
I've disabled specific linting rules in a couple local files so easier to review/fix in future if desired: 
- app/client/__tests__/components/delivery/records/deliveryRecords/step1.tsx
- app/client/__tests__/components/accountoverview/contributionUpdateAmount.tsx
Turned off two rules to reduce 'warning' noise:
- "@typescript-eslint/no-explicit-any": ["off"]
- "@typescript-eslint/ban-ts-comment": ["off"] - tests only
There are still several warnings about tests that have no assertions (`jest/expect-expect`) in payment components.

Add eslint jest plugin

---

.github/workflows/chromatic.yml
.github/workflows/cypress.yml

The Chromatic and Cypress checks fail on PRs raised by Dependabot. This is due to [the actions not having access to GitHub secrets](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#accessing-secrets) so they can't be run. As Dependabot PRs are raised relatively infrequently, tend not to cause UI regressions, and the checks are still run when merging to `main` we felt that it was safe to exclude Dependabot PRs from these actions for now rather than duplicating the secrets for Dependabot. (We may revisit this at a later date.)

Exclude Dependabot PRs from Chromatic and Cypress actions

---

app/client/components/identity/EmailAndMarketing/OptOutSection.tsx

RELEASING 15/3
We need to hard code the new opt out consent wordings so that we could implement the toggle before updating the Consent model in the API. 
Once the[ model change PR](https://github.com/guardian/identity/pull/2079) is relased we can use that response instead.

Use API Consents response instead of hardcoded

---

app/client/components/liveChat/liveChatCssOverrides.ts

Fix issue on mobile browsers where 100vh used in conjunction with position: fixed calculated the window inner size and the url bar meaning the start live chat button was being pushed below the fold of the screen without the option to scroll down and view/click it :s

livechat start button position

---

app/cypress/integration/parallel-1/updatePaymentDetails.spec.ts
app/cypress/integration/parallel-2/cancelContribution.spec.ts
app/cypress/integration/parallel-3/holidayStops.spec.ts
app/cypress/lib/setLocalBaseUrl.ts
app/cypress/lib/signInAndAcceptCookies.ts
app/cypress/support/index.ts

- Moves authentication and cookie banner set up to separate module to avoid duplication in specs
- Removes unnecessary `setLocalBaseUrl` method (this is already defined in `cypress.json`)
- Moves IAB consent management framework exception handling to global test set up in `index.ts` to avoid duplicating in specs

Clean up Cypress specs

---

app/artifact.json
app/riff-raff.yaml
manage-frontend-static/PROD-deploy.sh
manage-frontend-static/README.md
manage-frontend-static/cfn.yaml

Deploys static assets to a separate S3 bucket so that assets from previous deploys are retained in order to mitigate chunk loading errors following deployment due to previous assets being removed.
See the precedent at https://github.com/guardian/support-frontend/pull/2016 for more info

Deploy static assets to separate S3 bucket

---

app/riff-raff.yaml

Some of the assets have fixed names therefore we need to fetch a fresh copy soon after a deploy. The simplest way around that is to set a short max cache age time.

[JD RB] - change s3 asset max cache age

---

app/client/components/cancel/CancellationReasonReview.tsx

Add optional chaining operator to the router state selected reason check in the cancellation review stage. In order to catch the possibility that the router state itself is null and throwing an error trying to access a property of null

[RB] - add optional chaining operator

---

app/client/experiments/abSwitches.ts
app/client/experiments/abTests.ts
app/client/experiments/tests/example-test.ts
app/package.json
app/yarn.lock

Integrate the Guardian a/b testing system with manage:
https://github.com/guardian/ab-testing
This pr is just the infrastructure around setting up an a/b test in manage. This doesn't create an a/b test.
The wiki has also updated with instructions on how to setup a new test:
https://github.com/guardian/manage-frontend/wiki/A-B-testing

[RB] - add a/b test setup to manage so that tests can be run

---

app/client/components/identity/EmailAndMarketing/NewsletterSection.tsx
app/client/components/identity/idapi/newsletters.ts
app/client/components/identity/models.ts

* Derives the theme dropdowns from the newsletters API response, instead of a hardcoded list
* Adds the Opinion theme to the colour mappings
* The existing hardcoded themes sometimes have 2 issues:
* the theme could have no newsletters in the API response, so the dropdown is displayed but empty
* new themes have been added since the hardcoded list was created. Child newsletters of the new themes are not currently displayed in MMA (e.g the "Opinion" theme)
* Theme => colour mapping is still hardcoded, but defaults to a neutral colour where a mapping does not exist (e.g if there is a new theme without an explicit mapping)
| Before | After |
|--------|-------|
|  <img width="929" alt="Screenshot 2022-06-07 at 11 27 02" src="https://user-images.githubusercontent.com/705427/172358245-a99b9769-3 …

Derive newsletter themes from API response

---

app/webpack.common.js

This adds React Router to the list of packages that are _not_ excluded from babel-loader.
Previously we excluded everything in `node_modules` from babel-loader with the exception of internal `@guardian/*` packages. As React Router uses modern ES6 features it causes a JS error in IE11 and users see a blank page. To prevent this the React Router packages are now transpiled via babel-loader.
Open the application in BrowserStack and check that it now renders in IE11. It would also be worthwhile testing some key journeys in modern browsers to ensure there are no regressions.

Transpile React Router for IE11

---

app/client/components/cancel/CancellationContainer.tsx
app/client/components/cancel/CancellationSwitchEligibilityCheck.tsx
app/client/components/cancel/CancellationSwitchOffer.tsx
app/client/components/cancel/CancellationSwitchReview.tsx

The page title needs to change when on the review page of the cancellation switch journey.
Also passed the current router state through when navigating from the offer page to the review page to avoid an additional unnecessary members data api http request.

[RB] - update cancellation page title on offer review page

---

app/client/components/cancel/CancellationSwitchEligibilityCheck.tsx

https://sentry.io/organizations/the-guardian/issues/?project=1208603&query=is%3Aunresolved+message%3AdontShowOffer&statsPeriod=14d
Router state is null if person directly navigates to the URL so we are checking it here.

Check routerstate not null in cancellation/product movement journey.

---

app/client/components/cancel/CancellationSwitchConfirmed.tsx
app/client/components/cancel/CancellationSwitchEligibilityCheck.tsx
app/client/components/images/GridImage.tsx
app/client/components/images/theGrid.ts

Note: the Apple appstore does not seem to have geolocation implemented so we have to direct users to the correct site respective of their country, e.g.: UK, US, etc. [Support-frontend](https://github.com/guardian/support-frontend/blob/97da18b6d681754bb57eae3e578210b7887426b1/support-frontend/assets/helpers/urls/externalLinks.ts#L97)  take the users country code and match it with the correct appstore site. We can implement this behaviour in a subsequent PR.

Visual components for product-movement journey page 3

---

app/cypress/lib/signInAndAcceptCookies.ts

The cmp banner can be disabled via a cookie. This is convenient for integration testing with Cypress.

Disable cmp via cookie in Cypress tests

---

app/yarn.lock

Minor version bump to the `@guardian/eslint-plugin-source-foundations` package.
This includes a fix that stops the `valid-foundations-import-path` rule being logged to the console when running `yarn lint`. (https://github.com/guardian/source/pull/1465)

Minor version bump to `@guardian/eslint-plugin-source-foundations`

---

app/client/components/cancel/CancellationSwitchEligibilityCheck.tsx

If the eligibility switch api response (called when the user lands on the first page of the cancellation journey) returns a blank array then direct the user to the existing cancellation journey and not the product switch one.

Cancellation journey for people with no products to switch to 

---

app/client/__tests__/components/payment/updatePaymentFlow.test.tsx
app/client/components/payment/update/PaymentDetailUpdate.tsx

It enables Direct Debit payment method update widget to show whenever the currency is GBP and the delivery country is, or is implied to be, United Kingdom.
Ensure https://github.com/guardian/members-data-api/pull/770 has been deployed.
1. Create a recurring contribution or digital subscription using Card or PayPal.
2. Log into manage and check that you can change the payment method to DD.
3. Once you've changed, check that you can change/update the DD details successfully, as well as go on to select card again as an alternative.
Increase in number of payment failure recovery switches to DD.
Delivery address is determining it rather than billing address, which isn't available to manage. This should be very very rare that the currency being GBP does not mean that the billing country is not …

Enable Direct Debit payment method update widget to show in more cases

---

app/client/components/helpCentre/helpCentreConfig.ts

How to identify legitimate emails from the Guardian needs to show up in the more topics section (inside the newsletters section) on the homepage of the help center.

[RB] - show missing helpcenter article in the more topics section on homepage

---

app/client/components/Heading.tsx
app/client/components/cancel/CancellationReasonReview.tsx
app/client/components/cancel/cancellationSummary.tsx
app/client/components/cancel/contributions/contributionsCancellationFlowStart.tsx
app/client/components/cancel/digipack/digipackCancellationFlowStart.tsx
app/client/components/cancel/gw/gwCancellationFlowStart.tsx
app/client/components/cancel/stages/executeCancellation.tsx
app/client/components/cancel/voucher/voucherCancellationFlowStart.tsx
app/client/components/productSwitch/CancellationSwitchConfirmed.tsx
app/client/components/productSwitch/CancellationSwitchOffer.tsx
app/client/components/productSwitch/CancellationSwitchReview.tsx
app/client/components/productSwitch/productSwitchStyles.ts
app/client/styles/typography.ts

We use the same heading style across `manage-frontend`, but the CSS is duplicated in multiple places and implementations vary so there are subtle variations across the site. (Particularly with regards to responsive behaviour.)
This PR introduces a new `<Heading>` component in an attempt to standardise headings across the site and avoid duplication. It's fairly barebones for now so will likely be expanded to add additional options as it is used more widely.
The component includes two props: `level` and `cssOverrides`. `level` can be used to set the desired heading level. (If not specified it defaults to a `<h2>` element.) `cssOverrides` follows the Source convention and allows styling overrides to be applied to the heading element directly.
Headings do not include any external spacing. …

Add `<Heading>` component and update cancellation heading styles

---

app/client/components/helpCentre/helpCentreConfig.ts

Adds The Guardian Apps to the Help Centre navigation. This links to the existing apps topic at `/topic/apps`.

Add The Guardian Apps to Help Centre navigation

---

app/client/__tests__/dates.test.ts
app/server/__tests__/middleware/requestMiddleware.test.ts
app/server/apiProxy.ts
app/server/middleware/identityMiddleware.ts
app/server/middleware/requestMiddleware.ts

Improves the reliability of the test suite by fixing issues in the `dates` and `identityMiddleware` specs. These came to light whilst migrating from TeamCity to GitHub Actions (#856).
We've previously fixed issues with tests involving dates behaving differently in dev and CI in #744, but the `dateRange` test didn't need updating. However, this does fail when run in GitHub Actions due to timezone differences so has been updated to use the existing `localiseDate` function.
The `identityMiddleware` has been generating warnings for a while, but we've never managed to get to the bottom of the issues. The warnings don't cause the test suite to fail when run locally or in TeamCity, but do when run in GitHub Actions. The source of the warnings was tracked down to the `idapiConfig` module which …

Improve test suite reliability

---

app/client/components/delivery/address/deliveryAddressConfirmation.tsx
app/cypress/integration/parallel-4/deliveryAddress.spec.ts

Fixes an issue with updating a subscription's delivery address where the _Manage subscription_ page would continue to show the old address following confirmation of update and clicking the _Return to subscription_ button.
From the _Account overview_ page click through to the _Manage subscription_ page for a subscription with physical deliveries and select _Manage delivery address_. Go through the address update steps and on the confirmation page click _Return to subscription_ to return to the _Manage subscription_ page. The address details shown should match the updated address.

Ensure 'Manage subscription' shows address updates

---

app/client/components/liveChat/liveChat.tsx
app/client/components/liveChat/liveChatCssOverrides.ts

Fix issue where start chatting button is obscured from view when the form validation errors show above the prechat form 
input fields

[RB] - live chat pre chat form css overrides.

---

cdk/lib/__snapshots__/manage-frontend.test.ts.snap
cfn.yaml
server/config.ts
server/log.ts
server/routes/core.ts
server/routes/frontendCommon.ts

Removes environment variables defining application and API domains as these don't need to be part of the CloudFormation config and can be defined directly in the application code. (Fallbacks for dev environment domains are already defined in the code so this also cleans up some duplication.) `NODE_ENV` has also been removed from CloudFormation as this is always set to the same value, and `BUILD` has been removed from the app config as it's unused.

Remove unnecessary environment variables from CloudFormation config

---

cdk/lib/__snapshots__/manage-frontend.test.ts.snap
cfn.yaml

Part one of handing over the wazuh security group param from the cloudformation yaml file over to the cdk process. 
During the process of migrating over to CDK manage will run off of the old cloudformation file as well as the CDK this requires to duplicate the wazuh security group resource inside the cloudformation yaml file in order to prevent us from deleting the resource that the CDK also wants to use.
The first step is to duplicate the security group, and the subsequent step will be to remove the old duplicate.

create secondary wazuh security group and update snapshot

---

cdk/lib/__snapshots__/manage-frontend.test.ts.snap
cfn.yaml

Part 2 of the migration of wazuh security group resource from old cloudformation yaml to CDK.
This step removes the unused security group `WazuhSecurityGroup`, which will then be recreated by CDK.
see part 1 here: #866

remove old wazuh security group resource

---

cdk/lib/__snapshots__/manage-frontend.test.ts.snap
cfn.yaml

Update names and default values of VpcId, PrivateVpcSubnets, PublicVpcSubnets parameters to add the 'PreCDK' suffix in order to avoid name conflicts when dual deploying with cloudformation and guCDK.

cloudformation param name updates

---

cdk/lib/__snapshots__/manage-frontend.test.ts.snap
cfn.yaml

In #869 we moved to loading the VPC parameters from SSM Parameter Store, however we forgot to update the `Type` which tells CloudFormation where to source the value from.
In this change, we set the `Type` to [`AWS::SSM::Parameter::Value`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-ssm-parameter-types) so that it reads from SSM rather than use the raw string value.

fix: Use correct type for CFN Parameters sourced from SSM

---

cypress/integration/parallel-1/updatePaymentDetails.spec.ts

The payment update spec was calling the real `/api/validate/payment/dd?mode=live` endpoint which in turn was calling out to GoCardless. This intercepts the API call and mocks the response in the relevant payment update tests so there is no reliance on real APIs.
It's not entirely clear why this was previously working, so it's possible that it may fail again.

Decouple payment update spec from GoCardless

---

client/components/payment/update/PaymentDetailUpdate.tsx
shared/productResponse.ts

There have been increasing reports of Recurring Contributors, Digital Subscribers and Supporter Members being charged an AU banking fee for their AUD subscriptions.
Upon investigation, this appears to be due to some logic in manage-frontend which is not selecting the AU Stripe Public Key properly, as the account affected has no delivery country to allow Manage-Frontend to make its decision. 
Members Data API [has been enhanced ](https://github.com/guardian/members-data-api/pull/795) to return the Billing Country name.
Create an Australia Recurring Contribution using PayPal.
Log in to MMA
Change method to Card.
Zuora Gateway should say `Stripe PaymentIntents GNM Membership AUS` rather than `Stripe PaymentIntents GNM Membership` which it will do without this test.
Due to protections in …

Fix logic which selects correct Stripe Public Key

---

cdk/bin/cdk.ts
cdk/cdk.json
cdk/lib/__snapshots__/manage-frontend.test.ts.snap
cdk/lib/manage-frontend.test.ts
cdk/lib/manage-frontend.ts
cdk/package.json

Introduce the route53 DNS layer in between fastly and the load balancers. 
This helps us manage the migration to cdk, as part of the dual stack deployment (before we tear down the old stack) we can make routing changes at the DNS (route53) level instead of messing around in fastly.
Added a new deploy-code script in package.json and explicitly set the `App` tag via cdk hence why the snapshot is larger than just the route53 changes.

Introduce route53

---

yarn.lock

Updates the Browserslist `caniuse-lite` database. This is used for queries such as `>0.25%` in our current config and ensures we're using up-to-date browser usage data. (Updating the database also gets rid of constant warnings about it being outdated when running `yarn`.)
Longer term we should remove our custom Browserslist config and replace with [`@guardian/browserslist-config`](https://github.com/guardian/csnx/tree/main/libs/%40guardian/browserslist-config). As the standard config doesn't include support for IE11 we will need to consider our stance on supporting this browser. (As a single page React app IE11 users will be served a blank page without the necessary transpilation steps and polyfills included.)

Update `caniuse-lite` database

---

package.json
webpack.common.js
yarn.lock

Exclude `node_modules` from server bundle. These modules are already available on the server and generate warnings when bundled:
```
WARNING in ./node_modules/express/lib/view.js 81:13-25
Critical dependency: the request of a dependency is an expression
@ ./node_modules/express/lib/application.js 22:11-28
@ ./node_modules/express/lib/express.js 18:12-36
@ ./node_modules/express/index.js 11:0-41
@ ./server/server.ts 4:0-45 11:15-22 35:22-36
1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
```
The [`webpack-node-externals`](https://github.com/liady/webpack-node-externals) package is used to scan `node_modules` to generate a list of modules to exclude from the bundle.

Exclude `node_modules` from server bundle

---

cdk/bin/cdk.ts
cdk/lib/__snapshots__/manage-frontend.test.ts.snap
cdk/lib/manage-frontend.test.ts
cdk/lib/manage-frontend.ts
cfn.yaml
riff-raff.yaml

Define manage-frontend infrastructure in guCDK.
This setup should allow us to dual run the application via the old cfn.yaml file as well the new guCDK setup.
This represents the entirety of step 1 in the following migration guide: https://github.com/guardian/cdk/blob/main/docs/migration-guide-ec2.md

Migrate cfn yaml to cdk

---

riff-raff.yaml

add the asgMigrationInProgress property to riffraff yaml file in order to have multiple ASG's running while we manage the switch from the old stack to guCDK.

add asgMigrationInProgress property

---

cdk/lib/__snapshots__/manage-frontend.test.ts.snap
cdk/lib/manage-frontend.ts

Update the DNS record to point to the new loadbalancer instead of the old one referenced in the old cfn.yaml file.
Part of the guCDK migration work.

DNS update

---

cdk/lib/__snapshots__/manage-frontend.test.ts.snap
cdk/lib/manage-frontend.ts

prod layer currently needs DiscoverApiGatewayLambdas and InvokeApiGateway policy access to lower envs
error message seen on prod:
Sep 28 09:37:52 ip-10-248-134-12 manage-frontend[1886]: error: ERROR loading host and api key for membership-CODE-holiday-stop-api.
Sep 28 09:37:53 ip-10-248-134-12 manage-frontend[1886]: error: ERROR loading host and api key for membership-CODE-cancellation-sf-cases-api.
Sep 28 09:37:53 ip-10-248-134-12 manage-frontend[1886]: error: ERROR loading host and api key for membership-CODE-delivery-records-api.
Sep 28 09:37:53 ip-10-248-134-12 manage-frontend[1886]: error: ERROR loading host and api key for membership-CODE-product-move-api.
Sep 28 09:37:53 ip-10-248-134-12 manage-frontend[1886]: error: ERROR loading host and api key for support-CODE-invoicing-api.
We …

DiscoverApiGatewayLambdas and InvokeApiGateway policy changes

---

README.md

Small update to set up instructions to remove references to `app` folder and remove requirement to use `nvm` for Node.js version management.

Update set up instructions

---

client/components/cancel/stages/executeCancellation.tsx
cypress/integration/parallel-2/cancelSupporterPlus.spec.ts
server/routes/api.ts

Updates the product cancellation flow to use the product movement API if the product being cancelled is Supporter Plus. All other products continue to use the existing cancellation API.
Supporter Plus is not currently available in production so this change should have no impact. We're explicitly checking if the product being cancelled is Supporter Plus when switching API. The existing cancellation API is the default and therefore used for all other products.

Switch cancellation API for Supporter Plus

---

cdk/lib/manage-frontend.ts
server/routes/core.ts

Explain in comments why (currently) PROD has a dependancy on CODE cloudformation policy access to the following
- DiscoverApiGatewayLambdas
- InvokeApiGateway
This is because of the test user support; being able to access code subscriptions on the production environment.
More information can be found in the following wiki pages:
- https://github.com/guardian/manage-frontend/wiki/test-users
- https://github.com/guardian/manage-frontend/wiki/Proxying-API-Gateway-Lambdas
A separate piece of work will be looked into to see if this is necessary and wether this environment dependancy can be broken.

Add env policy comments

---

.eslintrc.js
client/components/accountoverview/contributionUpdateAmountForm.tsx
client/components/delivery/records/deliveryRecordsApi.ts
client/components/holiday/collatedCredits.tsx
client/components/productSwitch/ProductBenefits.tsx
client/services/deliveryAddress.ts
client/services/useFetch.ts
server/apiProxy.ts
server/awsIntegration.ts
server/config.ts
server/fulfilmentDateCalculatorReader.ts
server/middleware/requestMiddleware.ts
server/stripeSetupIntentConfig.ts
shared/featureSwitches.ts
shared/productResponse.ts

This follows on from #878 which introduced `@guardian/eslint-config-typescript`.
Overrides for the following linting rules have been removed and any errors / warnings in the code fixed:
| Rule |
| --- |
|array-type|
|consistent-indexed-object-style|

Lint rules fixes

---

client/components/accountoverview/accountOverviewCancelledCard.tsx
client/components/accountoverview/accountOverviewCard.tsx

Change H2s to H3s to fix hierarchy
The accessibility audit brought up this change to the hierarchy of headings on the Account Overview page.
H2s under the first H2 should now be H3s.

Fix 'Account overview' heading hierarchy

---

cdk/lib/__snapshots__/manage-frontend.test.ts.snap
cdk/lib/manage-frontend.ts

In reference to this pr: https://github.com/guardian/support-frontend/pull/3647
We need to add the `withoutImdsv2 ` property to the GuEc2App class in order to make the instance compatible with the  cloudwatch agent. Without doing this the logs disappear.

[RB] - add withoutImdsv2 to EC2 class to re-enable cloudwatch logs

---

client/components/identity/EmailAndMarketing/ConsentSection.tsx
client/fixtures/consents.ts

Removes "Guardian Holidays" from the list of marketing emails on the /email-prefs page.
The marketing emails for "Guardian Holidays" are being replaced with a new editorial newsletter "Guardian Traveller" see
https://github.com/guardian/identity/pull/2148 for details.
When the replacement is complete, users will use the checkbox in the "your newsletters" section to unsubscribe from "Guardian Traveller"
Open the /email-prefs page in dev - the "Guardian Holidays" checkbox is removed.
Users will be able to unsubscribe using the "Guardian Traveller" checkbox. The "Guardian Holidays" checkbox will not be rendered.
Merging this PR will needs to be merged so the checkbox is removed after the audience migration that will subscribe the "Guardian Holidays" audience to "Guardian Traveller".
We are …

Remove holidays signup

---

client/components/nav/dropdownNav.tsx
client/components/nav/leftSideNav.tsx

We're currently applying `role="tablist"` to the left-hand navigation although it's not actually a tab container and we're not applying any other tab related roles elsewhere.
The currently selected item is visually highlighted. We should use `aria-current` to also highlight the selected item to assistive technology.
The `role="tablist"` attribute no longer applies to the left hand nav.
The current page that is visually highlighted has attribute `aria-current='page'`

Remove tab role from left hand nav

---

cypress/tsconfig.json
package.json
tsconfig.json
yarn.lock

Uses `@guardian/tsconfig` as a base for our TypeScript config and simplifies things by stripping out unnecessary and commented out options.
`outDir` has been removed and `noEmit` added as TS compilation happens via Webpack rather than running `tsc`. We use `tsc` for type checking and this prevents it from generating any output if run without the `--noEmit` flag.
The Cypress TS config was previously based on the app's root config, although some of it is unnecessary so this has been stripped back to a minimal version.
The `noImplicitReturns` and `noUncheckedIndexedAccess` options from `@guardian/tsconfig` have been disabled as the app includes code that violates these checks. As with our linting errors, we should aim to fix these and re-enable the options.

Use `@guardian/tsconfig` and simplify TypeScript config

---

client/__tests__/__snapshots__/main.test.tsx.snap
client/components/main.tsx
client/components/page.tsx

Adds a 'Skip to content' link as the first tabbable navigation item on the page that links to the main content after all the navigation content.
On loading the page the 'Skip to content' link should not be visible.
On tabbing once it should become visible once in focus.
Clicking/pressing enter on the link takes the tabbed focus to the main content of the page - skipping the left nav bar.
-   [x] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [x] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] …

Add 'skip to content' link

---

client/components/accountoverview/accountOverviewCard.tsx
client/components/billing/billing.tsx
client/components/buttons.tsx
cypress/integration/parallel-3/holidayStops.spec.ts

If you have multiple products you'll see multiple buttons labelled Manage subscription and Manage payment method on the Account overview page.
Screenreader users often navigate around a page by getting a list of all of the headings, links or buttons. When presented with multiple buttons with the exact same label out of context they have no way of knowing which product the button refers to.
We should add an accessible name to each of these buttons using aria-label so that screenreader users will hear something like Manage Guardian Weekly subscription instead of just Manage subscription. 
As the manage text is repeated it may make sense to put the product name first to allow users to find the product the want to manage more quickly. eg. Guardian Weekly — manage subscription and Guardian …

Manage buttons accessible names

---

shared/productTypes.tsx

Update supporter plus productTitle to be either 'Monthly + extras' or 'Annually + extras'.

[RB AH] - update supporter plus productTitle

---

client/components/MMAPageSkeleton.tsx
client/components/accountoverview/accountOverviewCard.tsx
client/components/accountoverview/manageProduct.tsx
client/components/cancel/CancellationContainer.tsx
client/components/cancel/CancellationReasonSelection.tsx
client/components/cancel/CancellationSwitchEligibilityCheck.tsx
client/components/cancel/cancellationSummary.tsx
client/components/cancel/stages/executeCancellation.tsx
client/components/delivery/address/deliveryAddressConfirmation.tsx
client/components/delivery/address/deliveryAddressForm.tsx
client/components/delivery/address/formValidation.tsx
client/components/delivery/records/DeliveryRecordsContainer.tsx
client/components/delivery/records/deliveryAddressStep.tsx
client/components/delivery/records/deliveryRecords.tsx
client/components/delivery/records/deliveryRecordsProblemConfirmation.tsx
client/components/delivery/records/deliveryRecordsProblemReview.tsx
client/components/holiday/HolidayStopsContainer.tsx
client/components/holiday/holidaysOverview.tsx
client/components/payment/update/PaymentDetailUpdateContainer.tsx
client/components/productSwitch/CancellationSwitchConfirmed.tsx
client/components/productSwitch/CancellationSwitchReview.tsx
client/services/deliveryAddress.ts
cypress/integration/parallel-2/cancelSupporterPlus.spec.ts
server/fulfilmentDateCalculatorReader.ts
shared/productResponse.ts
shared/productTypes.tsx

Change the title 'Supporter Plus' to 'Monthly/Annual + extras' using the friendly name property of ProductType.
Cancel a supporter plus subscription - witness that the title should say 'Cancel monthly/Annual + extras'.
Before 
After

[AHE] Update supporter plus friendly name property in ProductTypes

---

client/components/cancel/CancellationContainer.tsx
client/components/cancel/CancellationSwitchEligibilityCheck.tsx
client/components/cancel/cancellationSummary.tsx
client/components/cancel/stages/executeCancellation.tsx
cypress/integration/parallel-2/cancelSupporterPlus.spec.ts
shared/productTypes.tsx

Update the copy on the cancellation journey for supporter plus.
- Change headline to say Cancel **INSERT Product Group** for all product journeys
Copy to read: 
- Monthly OR Annual support + extras cancelled 
- This is immediate and you will not be charged again. If you've cancelled within the first 14 days, we'll send you a full refund.
for supporter plus.
When cancelling a supporter plus produc: the new copy should show. When cancelling any other product: the old copy should show except for the headline that should now use the group of the product (e.g. subscription).
Before
After …

Update Cancellation Copy for Supporter Plus

---

client/components/accountoverview/accountOverviewCancelledCard.tsx
client/components/accountoverview/accountOverviewCard.tsx
client/components/accountoverview/contributionUpdateAmount.tsx
client/components/basicProductInfoTable.tsx
client/components/cancel/CancellationReasonSelection.tsx
client/components/cancel/contactUsToCancel.tsx
shared/productTypes.tsx

Previously Subscription ID was hidden for non-subscription products. This is now displayed as Supporter ID for membership and recurring support products.

Allow display of Supporter ID

---

cypress/integration/parallel-2/cancelContribution.spec.ts

The Cypress test 'Cancel contribution' assertion 'attempts cancellation but then updates payment details instead. (reason: A payment issue)' would fail on some runs of the entire suite. It was searching for text that occurs multiple times on the page if the whole page loads. This is seemingly a timing issue since it usually passes if the test is run alone.

Update cypress test that failed sometimes

---

client/components/billing/billing.tsx

Reveals the product info table for contributions on the _Billing_ page. Previously this was shown for all other products, but explicitly hidden for contributions. Now that we're able to show _Supporter ID_ in place of _Subscription ID_ for recurring support products there's no longer any need to hide this information.

Show product info table on Billing page for contributions

---

shared/productTypes.tsx

Recurring Contribution should change to say Monthly/Annual contribution within product tab
Navigate to the account overview page - witness a recurring contribution title says Monthly (or Annual) Contribution.
Before
After
-   [x] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [x] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [x] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

Recurring Contribution should change to say Monthly/Annual contribution

---

shared/productTypes.tsx

`productTitle` has an optional `mainPlan` argument, but contributions and Supporter Plus, which use the plan to generate the title, don't have a fallback if `mainPlan` is empty. This adds a default title for these two products. The only instance of this happening that I'm aware of is in the cancelled product cards on _Account Overview_ due to `CancelledProductDetail` only including a subset of subscription properties. (Crucially, `interval` is not one of these.)

Add default product title

---

client/components/accountoverview/manageProduct.tsx

Updates the 'Would you like to cancel your subscription?' message on the manage product page to use the grouped product type's friendly name as 'subscription' is currently hardcoded and shown for _all_ products.
Contributions and Supporter Plus, for example, will now show 'Would you like to cancel your recurring support?' instead.

Use product friendly name in 'contact us to cancel' message

---

client/__tests__/__snapshots__/main.test.tsx.snap
client/components/footer/footer.tsx

Replaces the normal twin CTAs in the page footer, ie. 'Contribute' and 'Subscribe', with a single CTA. The single CTA is labelled 'Support' and points to the Contributions landing page, as per the requirements for the new product launch.
_Before:_
_After:_
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-vi …

replace dual 'Contribute' and 'Subscribe' CTAs with single 'Support' CTA

---

cdk/lib/__snapshots__/manage-frontend.test.ts.snap
cdk/lib/manage-frontend.ts

We were getting [403 errors in Sentry](https://sentry.io/organizations/the-guardian/issues/3422642449/?project=1208607&query=is%3Aunresolved&referrer=issue-stream) for a specific bucket [`fulfilment-date-calculator-code` and `fulfilment-date-calculator-prod`](https://s3.console.aws.amazon.com/s3/buckets/fulfilment-date-calculator-prod?region=eu-west-1&tab=objects). The generated [policy](https://us-east-1.console.aws.amazon.com/iamv2/home#/roles/details/support-PROD-manage-front-InstanceRoleManagefronte-3I9WNVJB6KFC?section=permissions) had an incorrect bucket path, which had the stage name in uppercase. This PR converts the stage name [to lowercase](https://github.com/guardian/manage-frontend/pull/927/files#diff-02efc8938d4b3eac80fe423090cbf66845e0a3203382bb9e94c569323fd81d76R137).

s3 bucket path fix

---

client/components/accountoverview/emptyAccountOverview.tsx
client/components/footer/footer.tsx
client/components/resubscribeThrasher.tsx
client/components/supportTheGuardianButton.tsx
shared/productTypes.tsx

Updates the `<SupportTheGuardianButton>` component so that it points to the new contribute page by default. The default button text has also been changed from 'Support The Guardian' to 'Support the Guardian' to follow Guardian style. Surrounding copy on pages where this button appears have also been updated accordingly.

Update support button URL and surrounding copy

---

client/components/accountoverview/accountOverview.tsx
client/components/accountoverview/accountOverviewCardV2.tsx
client/components/payment/directDebitDisplay.tsx
client/components/payment/paypalDisplay.tsx
client/components/payment/sepaDisplay.tsx
shared/featureSwitches.ts

Updates the Account Overview product cards to give them a visual refresh and reorganise their content to make space for the product switch button. (These changes are currently hidden behind the `accountOverviewNewLayout` feature flag.)
This is the first of a series of PRs. Product-specific header colours and images, product benefits and support for cancelled and gifted subscriptions will be added in subsequent PRs.

Rebuild Account Overview product cards

---

client/components/accountoverview/accountOverviewCardV2.tsx
client/components/payment/nextPaymentDetails.tsx

Adds Supporter+ benefits section and toggle button.
-   [x] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [x] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [x] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

Supporter+ benefits dropdown

---

client/components/accountoverview/accountOverview.stories.tsx
client/components/accountoverview/accountOverview.tsx
client/components/accountoverview/accountOverviewCardV2.tsx
shared/productResponse.ts

Adds logic to determine when to show 'Change to support and extras' button. The button is shown on a product card if:
- the current product is a Recurring Contribution
- user does not have DigiSub **and** RC
- user is not in payment failure
Storybook stories have been added to test the different scenarios where
- user has DigiSub and RC
- user is in payment failure
- user only has RC
-   [ ] …

Wire up 'Change to support and extras' button to logic to determine whether to show it

---

client/components/mma/MMAPage.tsx
client/components/mma/accountoverview/AccountOverviewCardV2.tsx
client/components/mma/shared/Card.tsx
client/components/mma/shared/Heading.tsx
client/components/mma/switch/SwitchContainer.tsx
client/components/mma/switch/SwitchOptions.tsx
cypress/integration/parallel-2/productSwitch.spec.ts
shared/productTypes.tsx

This PR adds a new route and first page for the product switching journey under `/switch` and the 'Your current support' block of the Options page. 
This is behind the 'Change to monthly + extras' button which is behind the feature flag 'accountOverviewNewLayout'. Alternatively navigate to '/switch' with a contribution product.
Acceptance criteria:
Wording should display 'Monthly' or 'Annual' support
Should display current spend per month / year
Should display correct currency
Should include a message
'You're currently supporting the Guardian with a [insert monthly OR annual] contribution of [insert spend here]. …

Create new Product Switching route and options page

---

.eslintrc.js
client/__tests__/components/accountoverview/contributionUpdateAmount.test.tsx
client/__tests__/components/payment/stripe.test.ts
client/components/helpCentre/HelpCentreArticle.tsx
client/components/mma/cancel/Cancellation.stories.tsx
client/components/mma/cancel/ResubscribeThrasher.tsx
client/components/mma/cancel/contributions/ContributionsCancellationFlowFinancialSaveAttempt.tsx
client/components/mma/cancel/contributions/ContributionsCancellationFlowPaymentIssueSaveAttempt.tsx
client/components/mma/cancel/stages/SavedCancellation.tsx
client/components/mma/cancel/voucher/VoucherCancellationFlowStart.tsx
client/components/mma/identity/GenericErrorMessage.tsx
client/components/mma/paymentUpdate/FieldWrapper.tsx
client/components/mma/paymentUpdate/UpdatePayment.stories.tsx
client/components/shared/nav/DropdownNav.tsx
client/utilities/hooks/useAnalytics.ts
package.json
shared/identity.ts
shared/productResponse.ts
yarn.lock

Fixes the following linting errors and removes overrides to disable these rules from the ESLint config:
`@typescript-eslint/no-unnecessary-type-arguments`
`@typescript-eslint/prefer-includes`
`@typescript-eslint/prefer-ts-expect-error`
`@typescript-eslint/restrict-plus-operands`

More TypeScript linting fixes

---

client/components/mma/accountoverview/AccountOverviewCardV2.tsx
client/components/mma/shared/SupporterPlusBenefits.tsx
client/components/mma/switch/SwitchOptions.stories.tsx
client/components/mma/switch/SwitchOptions.tsx

Adds the 'Change your support' section to the Product Switch Options page.
When attempting to promote switching, we want to highlight to users the benefits of switching and what they can get when switching to Supporter+. Note: there are two different scenarios here and the block should display different content depending on the users payments (below or above threshold)
Navigate to `/switch` with a recurring contribution.
Acceptance criteria:
- H2 should read 'Add extras' if above threshold
- H2 should read 'Change your support' if below threshold
- Change your support subtext should differ depending on Monthly or Annual + extras depending on what the user currently has.
Banner should read Monthly or Annual + extras depending on their current product
List of benefits should be in order as …

Create Change your support section

---

client/__tests__/components/helpCentre/__snapshots__/helpCentreContactOptions.test.tsx.snap
client/components/helpCentre/HelpCentrePage.tsx
client/components/shared/CallCenterEmailAndNumbers.tsx

Updates Help Centre known issues banner and phone number component to remove Christmas opening times and update ransomware copy.

Remove Christmas opening hours from Help Centre

---

client/components/mma/shared/Heading.tsx
client/components/mma/switch/SwitchOptions.tsx

Makes the product switch button sticky on smaller screens so that it is always visible at the bottom.
This uses an Intersection Observer to detect when the button is 'stuck' and not part of the normal document flow in order to apply additional styles. The observable area is reduced by `1px` on the bottom edge so that when the button is 'stuck' to the bottom of the viewport it is not considered to be fully visible. Similarly, the observable area is extended beyond the top of the viewport so that the 'stuck' state is not triggered when the button scrolls off the top of the page.
https://user-images.githubusercontent.com/1166188/208878586-99f0de64-d502-445b-95f7-f8876eeb3965.mov

Sticky product switch button

---

client/components/mma/accountoverview/AccountOverviewCardV2.tsx
client/components/mma/shared/Card.tsx
client/components/mma/switch/SwitchOptions.tsx

Adds rounded corners to cards on small viewports (to better match the design of the mobile app) and removes the default minimum header height applied at the `tablet` breakpoint as this is an exception that is only required on the _Account Overview_ page. (The new `minHeightTablet` prop can be used to opt in to this.)

Card component mobile layout tweaks

---

client/components/mma/accountoverview/ContributionUpdateAmount.tsx
client/components/mma/accountoverview/ContributionUpdateAmountForm.tsx
client/components/mma/billing/Billing.tsx
client/components/mma/cancel/contributions/ContributionsCancellationFlowFinancialSaveAttempt.tsx
client/components/mma/cancel/contributions/ContributionsCancellationFlowPaymentIssueSaveAttempt.tsx
client/components/mma/cancel/contributions/utils.ts
client/components/mma/cancel/productSwitch/CancellationSwitchConfirmed.tsx
client/components/mma/cancel/productSwitch/CancellationSwitchReview.tsx
client/components/mma/cancel/productSwitch/productSwitchApi.ts
client/components/mma/cancel/productSwitch/productSwitchHelpers.ts
client/components/mma/paymentUpdate/PaymentDetailUpdateConfirmation.tsx
client/components/mma/shared/NextPaymentDetails.tsx
client/components/mma/switch/SwitchOptions.tsx
cypress/integration/parallel-2/updateContributionAmount.spec.ts
shared/productResponse.ts
shared/productTypes.tsx

As mentioned in the [previous PR](https://github.com/guardian/manage-frontend/pull/947). This PR removes the old properties.
The best way to review this PR would be to do a diff of this branch and the main branch before my last PR, and assert that the property names have changed accordingly.
I have also added a new Cypress test for the update contribution amount journey:

Refactor zuora properties - remove old properties

---

client/components/mma/switch/SwitchContainer.tsx
client/components/mma/switch/SwitchOptions.tsx

Background: Due to Apple laws we aren't able to express all of the copy we'd like to within the app, therefore we'd like a box to display if users come from the app. The expectation from our side is that users from the app would come directly to this page via a url with a string of text that would therefore expose the box of text.
This PR adds a specific URL for users coming from the app and persists this in context, and also adds additional copy on the switch options page
Navigate to `/switch#from-app` and see the additional copy, without the extra URL specifier it should not be visible. …

Create app only URL and add text to Switch options page

---

.eslintrc.js
client/__tests__/components/payment/updatePaymentFlow.test.tsx
client/components/mma/delivery/address/Select.tsx
client/components/mma/delivery/records/DeliveryAddressStep.tsx
client/components/mma/delivery/records/DeliveryRecordCard.tsx
client/components/mma/delivery/records/DeliveryRecords.tsx
client/components/mma/delivery/records/DeliveryRecordsProblemConfirmation.tsx
client/components/mma/delivery/records/DeliveryRecordsProblemReview.tsx
client/components/mma/identity/models.ts
client/components/mma/identity/useConsentOptions.ts
client/components/mma/paymentUpdate/PaymentDetailUpdate.tsx
client/components/mma/paymentUpdate/card/FlexCardElement.tsx
client/components/mma/shared/AsyncLoader.tsx
client/components/mma/shared/assets/GiftIcon.tsx
client/components/shared/Input.tsx
shared/productTypes.tsx

Removes override for `@typescript-eslint/naming-convention` linting rule and updates MMA code to follow naming conventions. Due to some uncertainty around coupling between enum values and API responses in Identity code, this has not been updated and the rule disabled in a couple of places.

Enable `@typescript-eslint/naming-convention` linting rule and fix errors

---

.eslintrc.js
client/__tests__/components/accountoverview/contributionUpdateAmount.test.tsx
client/components/mma/identity/models.ts
client/components/mma/identity/useConsentOptions.ts
client/components/shared/SectionContent.tsx
client/utilities/gaStub.ts

Removes override for `eslint-comments/require-description` and adds comments where they are missing from `eslint-disable` comments

Enable `eslint-comments/require-description` rule and add comments

---

client/components/mma/MMAPage.tsx
client/components/mma/accountoverview/AccountOverviewCardV2.tsx
client/components/mma/shared/SupporterPlusBenefits.tsx
client/components/mma/switch/SwitchOptions.tsx
client/components/mma/switch/SwitchReview.stories.tsx
client/components/mma/switch/SwitchReview.tsx
client/styles/spacing.ts

Adds the Review Change page and the 'Your New Support Component'
Navigate to `/switch` then click the 'Change to monthly + extras' button. Witness the new page navigated to.

Create Review Change Page - Your New Support Component

---

client/components/mma/switch/SwitchReview.tsx

Add a summary of the user's changes
Navigate to `/switch` then click the 'Change to monthly + extras' button. Witness the new page navigated to.

Add Headline Summary to review page

---

client/__tests__/__snapshots__/main.test.tsx.snap
client/__tests__/styles/grid.test.ts
client/components/mma/Page.tsx
client/components/mma/accountoverview/ManageProduct.tsx
client/components/mma/delivery/address/DeliveryAddressChangeContainer.tsx
client/components/mma/delivery/records/DeliveryRecordsContainer.tsx
client/components/mma/holiday/HolidayStopsContainer.tsx
client/components/mma/paymentUpdate/PaymentDetailUpdateContainer.tsx
client/components/mma/shared/assets/GridRoundel.tsx
client/components/mma/switch/SwitchContainer.tsx
client/components/shared/Header.tsx
client/components/shared/nav/DropdownNav.tsx
client/styles/grid.ts

Removes the breadcrumb trail from the page header and updates page title styles for mobile, adding a new 'compact' style for the product switching flow.
As part of this change the grid layout styles have been refactored and simplified, and IE-specific `-ms` prefixed grid properties removed.

Refactor page grid, update title styles and remove breadcrumbs

---

client/components/mma/identity/identity.ts

We a running a one month trial of a soft opt in default onboarding newsletter in the new registration onboarding flow.
https://github.com/guardian/gateway/pull/2105
Becasue this is a trial, we need to hide the newsletter from appearing in MMA. 
Users can still unsubscribe from the trial newsletter via the email footer, or by hitting unscubscribe ALL in MMA
This will be reverted when trial is over.

AB TEST -  hide the default onboarding trial newsletter

---

client/components/mma/shared/asyncComponents/LoadingComponent.tsx
client/utilities/hooks/useAsyncLoader.ts

Change promiseFromAsync fetch to be a callback instead of a promise
Co-Authored-By: Kent McClymont <111352918+KentGrm@users.noreply.github.com>
Changes useAsyncLoader to use an enum to track state. Also change the fetch to be a callback instead of a promise to stop it firing indefinitely.

Change useAsyncLoader to use an enum to track state

---

client/components/mma/switch/SwitchReview.stories.tsx
client/components/mma/switch/SwitchReview.tsx
client/fixtures/productMove.ts
client/fixtures/switchPreview.ts
cypress/integration/parallel-2/productSwitch.spec.ts

Updates switch review page to add 'Confirm change' and 'Back' buttons, and terms & conditions section. The confirmation button is hooked up to the `product-move` API allowing product switches to be made. The final 'thank you' page hasn't been built yet so you'll be redirected back to the _Account Overview_ following a successful switch. If the switch fails you'll see a placeholder error message, pending the final design.
Clicking 'Confirm change' should switch your recurring contribution to the _monthly / yearly + extras_ product as appropriate. Clicking 'Back' returns you to the initial switch landing page.

Product switch confirmation section and Ts&Cs

---

client/components/mma/MMAPage.tsx
client/components/mma/shared/Heading.tsx
client/components/mma/switch/SwitchComplete.stories.tsx
client/components/mma/switch/SwitchComplete.tsx

Adds the Thank You page to the switch journey with initial thank you messaging for users not referred by the app.
Navigate to `/switch/complete` and witness the new page and component, the styling is different on mobile and desktop views. 
Desktop
Mobile
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visu …

Create Switch Thank You page and non-app messaging

---

client/components/mma/MMAPage.tsx
client/components/mma/switch/SwitchContainer.tsx
cypress/integration/parallel-2/productSwitch.spec.ts
shared/featureSwitches.ts

Adds a feature switch to disable product switching, preventing access to the work in progress pages on production.
Navigation to `/switch` or any of the child pages will not be possible.

Add feature switch for product switching flow

---

client/fixtures/payment.ts

Changes the stripe setup intent used for tests with a more obviously dummy string.

Replace test Stripe setup intent with more obviously dummy data

---

client/components/mma/accountoverview/AccountOverview.tsx
client/components/mma/accountoverview/AccountOverviewCardV2.tsx
client/components/mma/shared/assets/InverseStarIcon.tsx
client/components/mma/switch/SwitchComplete.stories.tsx
client/components/mma/switch/SwitchComplete.tsx
client/components/mma/switch/SwitchContainer.tsx
client/components/mma/switch/SwitchReview.tsx
cypress/integration/parallel-2/productSwitch.spec.ts
shared/productResponse.ts

- store amountPayableToday in routerState
- propagate user info to review pages
Adds the 'What Happens Next' section to the Thank You page, storing the amount payable today from the Review page in routerState. It also gets the user info to display the email from the mdapi response.
On the review page click 'Confirm change' and witness the new component on Thank You page with email and amount to pay today.
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md# …

Create Thank You - What Happens next text

---

client/components/mma/accountoverview/AccountOverview.tsx
client/components/mma/accountoverview/PersonalisedHeader.tsx

Added new file to create the personalised header when a user accesses their account overview:
Depending on the time of day the user will see a different welcome greeting. This is determined by pulling the hour from the user and setting either Good [morning, afternoon, evening]. 
The User's name is pulled from mdapi, if the first name is not present then Reader is set as the default. The year which the user has supported The Guardian is also pulled from the mdapi response which has the product details. The products are ordered by join date and the oldest product year is used.
A new personalised header on the account overview page, including a welcome greeting, the user name and the year they started supporting The Guardian
Head to your Account Overview page and you should see a greeting …

Personalised header on Account Overview

---

client/components/mma/cancel/Cancellation.stories.tsx
client/components/mma/cancel/contributions/ContributionsCancellationReasons.tsx
client/components/mma/cancel/supporterplus/SupporterplusCancellationReasons.tsx
cypress/integration/parallel-2/cancelContribution.spec.ts
shared/productTypes.tsx

When a customer wants to cancel the cancellation reasons are in a fixed order meaning that there could be bias to the options at the top of the list. This change shuffles the cancellation reasons whilst keeping 'another reason' fixed at the bottom.
Checked on storybook and CODE that when trying to cancel the reasons provided are shuffled differently each time, but 'Other Reasons' always remains at the bottom of the list. On Prod when on the cancel recurring contributions page the reasons should be in a random order with another reason at the bottom. Refresh the same page and the reasons should be shuffled with another reason remaining at the bottom of the list.
Before <img width="940" alt="image" src="https://user-images.githubusercontent.com/115992455/214064378-4ae23cf6-05e5-4b01-9c14-23c …

MMA: Randomise Cancellation Reasons

---

cypress/integration/parallel-2/cancelContribution.spec.ts
cypress/integration/parallel-2/cancelSupporterPlus.spec.ts

Updates cancellation tests to reference radio buttons by name rather than index to improve reliability.
Cancellation reasons are now randomised so if the reason radio button is selected by index a different reason will be selected for each test run. Not all tests are explicitly testing specific cancellation reasons, but the ones that are will randomly fail due to an incorrect option being selected. (Some cancellation reasons add additional steps or UI elements, changing the flow through the cancellation process.)
This change has previously been made to _some_ tests, but not all. This PR updates the remaining tests to ensure consistent test runs.
Selecting radio buttons by index:
```js
cy.findAllByRole('radio').eq(2).click();
```
Selecting radio buttons by name:
```js …
```

Improve Cypress cancellation spec reliability

---

.eslintrc.js
client/components/mma/accountoverview/AccountOverview.tsx
client/components/mma/cancel/CancellationReasonSelection.tsx
client/components/mma/cancel/stages/ExecuteCancellation.tsx

Remove `no-unnecessary-type-assertion` eslint rule override and remove unnecessary type assertions.

Enable `no-unnecessary-type-assertion`

---

client/components/mma/shared/Heading.tsx
client/components/mma/switch/SwitchComplete.tsx
client/components/mma/switch/SwitchOptions.tsx
client/components/mma/switch/SwitchReview.tsx
client/components/mma/switch/SwitchStyles.ts
client/styles/spacing.ts

Refactors product switching pages to extract common styles to `SwitchStyles.ts`. This also introduces new icon list styles and applies these to the two 'what happens next' sections, fixing spacing issues identified during the design review.
This also tackles some other small, post design review updates:
- Hides 'Change to [product]' copy on first page when coming via the app
- Removes border from back button on mobile
- Updates style of small print at bottom of first page to match subsequent pages

Product switch refactoring and post design review refinement

---

client/components/mma/MMAPage.tsx
client/components/mma/switch/SwitchContainer.tsx
client/components/mma/switch/SwitchOptions.tsx
client/components/mma/switch/SwitchReview.tsx

Changes the url for from app journeys to be `app/switch` instead of using a hash in the name, because if you get redirected to Identity to sign in it seems to strip out any query parameters and hashes.

Change URL for app journeys to app/switch

---

client/components/mma/switch/SwitchComplete.tsx

Adds a 'thank you' banner specifically for users who began the switching journey in the app. The banner includes a CTA to return users to the app so they can continue reading.
This is primarily for mobile users, although users on tablets may also go through the same switching journey via the app so this includes an interim desktop design which may be refined later.
Start a switching journey from `/app/switch`. The banner will appear at the top of the final page.

Return to app banner

---

client/components/mma/accountoverview/AccountOverview.tsx
client/components/mma/accountoverview/ManageProduct.tsx
client/components/mma/billing/Billing.stories.tsx
client/components/mma/billing/Billing.tsx
client/components/mma/shared/AsyncLoader.tsx
client/components/mma/shared/PaymentFailureAlertIfApplicable.tsx
client/components/mma/shared/asyncComponents/DefaultErrorView.tsx
client/components/mma/shared/asyncComponents/DefaultLoadingView.tsx
client/components/mma/switch/SwitchContainer.tsx
client/components/mma/switch/SwitchReview.tsx
client/components/shared/GenericErrorScreen.tsx
client/fixtures/invoices.ts
cypress/integration/parallel-1/updatePaymentDetails.spec.ts

- refactor default loading view and error screen
Refactors the Billing page to use the useAsyncLoader hook pattern. Also refactors the page to join invoices to product details before the display logic. Adds a loading message to the defaultLoadingView.
Go to billing, the page should load the same as before these changes. …

Refactor Billing page to use useAsyncLoader hook

---

client/components/mma/accountoverview/ContributionUpdateAmountForm.tsx
client/components/mma/cancel/contributions/utils.ts
client/components/mma/switch/SwitchComplete.stories.tsx
client/components/mma/switch/SwitchComplete.tsx
client/components/mma/switch/SwitchOptions.tsx
client/components/mma/switch/SwitchReview.stories.tsx
client/components/mma/switch/SwitchReview.tsx
client/utilities/benefitsThreshold.ts
client/utilities/contributionsAmount.ts
client/utilities/currencyIso.ts

- refactor contributionsAmount since it is similar
- add Storybooks for variations
Adds a config file for Supporter Plus benefit thresholds and uses it in switch pages. Also refactor ContributionsAmountOptions (similar config) to sit in the same folder. Fixes some errors where the pages were not using dynamic monthly/annual copy and adds storybooks with currency and yearly config to catch any regressions.
Go to `/switch` with a contribution using a currency other than GBP and observe a different price point.
-   [ ] …

Add threshold per currency config and use new config in Switch pages

---

client/components/mma/switch/SwitchComplete.tsx
client/components/mma/switch/SwitchContainer.tsx
client/components/mma/switch/SwitchOptions.tsx
client/components/mma/switch/SwitchReview.tsx

Applies latest round of copy changes to the product switching pages. This covers contributions that are above and below the benefit threshold, and switches initiated from the Guardian news app.

Product switch copy updates

---

client/components/mma/switch/SwitchOptions.tsx
client/components/mma/switch/SwitchReview.tsx
client/components/mma/switch/SwitchStyles.ts
cypress/integration/parallel-2/productSwitch.spec.ts

Update generic switch error message and add specific payment failure error message for switches that haven't been started from the _Account Overview_ page (where the existing eligibility check would have prevented a user from switching).

Product switch payment failure and generic error messaging

---

cypress/integration/parallel-2/productSwitch.spec.ts

Updates Cypress spec to reflect latest copy changes. This was missed as the tests are only run when the feature switch is enabled.

Fix product switching Cypress spec

---

client/components/mma/switch/SwitchComplete.stories.tsx
client/components/mma/switch/SwitchComplete.tsx
client/components/mma/switch/SwitchContainer.tsx
client/components/mma/switch/SwitchReview.tsx
client/fixtures/productMove.ts

The next payment date shown to a user was previously calculated on the client side - for accuracy and safety we are now getting this from the product-move-api preview response.
Also removes the refund property from the preview response body - since we are not intending on using that property for now.
Start a switch on `switch` and observe the next payment date should be present on the Review and Thank You pages.
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-vis …

Get nextPaymentDate from preview API response

---

shared/featureSwitches.ts

Enables the Product Switching feature flag.
`/switch` should be accessible on all environments, including production.
We're enabling this to allow beta testing of apps metering so the pages are not linked to from anywhere in MMA. It's possible somebody could stumble upon this URL and go through the switching journey, but this isn't a huge problem if it happens and is a risk we've accepted.

Enable Product Switching feature flag

---

client/components/mma/accountoverview/PersonalisedHeader.tsx
client/components/mma/shared/SupporterPlusBenefits.tsx
client/components/mma/switch/SwitchComplete.tsx
client/components/mma/switch/SwitchOptions.tsx
client/components/mma/switch/SwitchReview.tsx
cypress/integration/parallel-2/productSwitch.spec.ts

Makes the following amendments to copy:
  | Page | Copy | Should be
-- | -- | -- | --
All scenarios | Account Overview | Good Afternoon Reader | Good afternoon, supporter
  |   | Thanks for supporting... | Thank you for funding the Guardian since [month] [year]
  | Change your support / Review change | view benefits > | View extras >
  |   | hide benefits > | Hide extras >
  |   | Dive in and start enjoying your exclusive extras straight away | In just a couple of steps, you'll be able to start enjoying your exclusive extras
  | Thank you page | Remove full stops except for the banner |  
Above Threshold Specific | Change your support / Your current support | Add extras with no extra cost | Add extras
  |   | Your current payment entitles you to | In exchange for your current payment, you …

Make amendments to copy

---

client/components/mma/switch/SwitchReview.tsx

Fix a bug introduced in copy amendments - a boolean was included in an interpolated string because of the `&&` operator.
Visit the `review` page with a RC that is under the threshold - copy should not include the word 'false'.

Fix copy bug with interpolated string that had "false" in the text

---

client/components/shared/nav/NavConfig.tsx
cypress/integration/parallel-6/savedArticles.spec.ts

Add explicit override for testing the feature switch

---

client/components/shared/nav/DropdownNav.tsx

Fix the dropdown nav being cut off at smaller desktop sizes on mma by removing an unnecessary check to see if it was a help centre page or not (since mma and help-centre now use the same header).
Before fix:
After

Fix dropdownNav at desktop smaller sizes

---

client/components/mma/MMAPage.tsx

Adds code splitting for product switch pages so they are dynamically imported as needed and not included in the main bundle. This matches the other sections of the site and ensure users are not downloading code that they do not need. This is especially important at the moment as product switching is only partially rolled out for beta app users, but all visitors to the site are having to download the code for this feature.
|Before|Before (gzip)|After|After (gzip)|
|---|---|---|---|
|818.32KB|243.23 KB|737.6 KB|213.78 KB|
Manually navigate to the product switch page at `/switch` with dev tools open and you will see the product switch bundle being dynamically loaded.

Remove product switch code from main bundle

---

client/components/mma/cancel/CancellationReasonSelection.tsx
cypress/integration/parallel-2/cancelContribution.spec.ts
cypress/integration/parallel-2/cancelGW.spec.ts
cypress/integration/parallel-2/cancelSupporterPlus.spec.ts

As part of the process to cancel a subscription, we make an API call to get a preview of the cancellation date. This is intended to provide the customer with an estimated timeframe for when their subscription will end, but it is only applicable for Guardian Weekly and Voucher products. We do not use this date for any other product in the cancellation process. This PR makes this API call conditionally based on the `startPageOfferEffectiveDateOptions `.
Cypress tests have been amended to check the API is called (or not called) as expected.
Tested in DEV.

Only call the `get-cancellation-date` API endpoint when necessary

---

client/components/mma/cancel/stages/ExecuteCancellation.tsx
cypress/integration/parallel-2/cancelSupporterPlus.spec.ts

Show error message as expected when a cancellation fails. The code was expecting the old MDAPI response type (ProductDetail array) instead of the new object which contains `user` and `products` properties.

Fix Failed Cancellation not displaying error

---

client/components/mma/accountoverview/AccountOverview.stories.tsx
client/components/mma/accountoverview/ContributionUpdateAmountForm.tsx
client/components/mma/accountoverview/InAppPurchaseCard.tsx
client/components/mma/billing/Billing.stories.tsx
client/components/mma/billing/Billing.tsx
client/components/mma/identity/emailAndMarketing/EmailAndMarketing.stories.tsx
client/components/mma/identity/emailAndMarketing/EmailAndMarketing.tsx
client/components/mma/paymentUpdate/Summary.tsx
client/fixtures/inAppPurchase.ts
shared/mpapiResponse.ts
shared/productTypes.ts
shared/softOptInIDs.ts

Adjust the copy and design for IAP product holding on the account overview page and billing page. Get correct Soft Opt Ins for IAPs and refactor to show them on Email and Marketing page.
With an IAP product associated with an account test the following:
Account Overview:
Navigate to `/?withFeature=appSubscriptions` and see the App Subscription product card.
Billing:
Go to Billing page and see the App Subscription box.
Email and Marketing:
Go to Email and Marketing and see the following 3 supporter exclusive consents:
- Your subscription/support
- Supporter newsletter
- Similar Guardian products …

Display IAPs in Account Overview, Billing page and Emails and Marketing consents

---

client/components/mma/accountoverview/AccountOverview.stories.tsx
client/components/mma/accountoverview/AccountOverview.tsx
client/components/mma/accountoverview/AccountOverviewCardV2.tsx
client/components/mma/accountoverview/CancelledProductCard.tsx
client/components/mma/accountoverview/ProductCard.tsx
client/components/mma/accountoverview/ProductCardConfiguration.ts
client/components/mma/cancel/Cancellation.stories.tsx
client/fixtures/cancelledProductDetail.ts
client/fixtures/productDetail.ts
shared/dates.ts

Adds cancellation detail summaries to the existing product cards (to cover products which are within the cancellation period and still accessible) as well as a redesigned cancelled product card that matches the new Account Overview card design.
The product details card has been renamed from `AccountOverviewCardV2` to `ProductCard` to match the naming of the other new product card components and to reflect that it will be the canonical product details card component when this feature is released.
The placeholder banner image code and styles have been removed. A simplified implementation is covered by #1010 which is awaiting final designs.
With the `accountOverviewNewLayout` feature flag enabled, log into an account that has cancelled products. A cancellation detail summary should be shown …

Show cancelled products on new Account Overview layout

---

client/components/mma/accountoverview/ProductCard.tsx
client/components/mma/switch/review/SwitchReview.tsx

Prevents the `product-move` API being called again if the switch 'confirm' button is clicked more than once, and hides the switch button on the _Account Overview_ if the product has a pending cancellation. (This shouldn't happen in practice for a contribution, but we have a fixture that covers this scenario so this is a bit belt and braces.)
With the _Network_ tab in devtools open, click the 'confirm' button on the switch review page multiple times and check that the `product-move` API is only called once.

Prevent multiple calls to `product-move` API

---

client/components/mma/accountoverview/ProductCard.tsx
shared/productTypes.ts

A couple of small tweaks and fixes ahead of enabling the new Account Overview layout: the existing price rise alert component has been replaced as it breaks the layout and now appears inline with the price, and the 'Change to x' button has been updated so that the product name is dynamic rather than hardcoded as 'monthly + extras'.

Inline 'price rise' alert and dynamic product name on switch button

---

client/components/mma/accountoverview/AccountOverview.stories.tsx
cypress/integration/parallel-3/holidayStops.spec.ts
shared/featureSwitches.ts

Enables the new Account Overview layout and allows product switches to be initiated from MMA.
When signed in with an active recurring contribution, but no digital subscription, you should should see a _Change to monthly + extras_ button in the product card. (_annual_ if an annual contribution.)
All other subscription information shown in the old layout should be displayed in the new product cards, and it should be possible to manage each subscription and update payment details as before.
Apart from the addition of the _Change to monthly + extras_ button and a new look and feel, users should experience no change in functionality so we should not expect any additional contact with customer support as a result of this change. We should also monitor Sentry and ensure there are no new errors …

Enable new Account Overview layout and product switching from MMA

---

client/components/mma/identity/identity.ts

Prevents a newsletter with a specific id number being rendered on the /email-prefs page.
This is temporary change - a newsletter with this number needs to be set up in advance but not rendered on MMA until the journalism it refers to is published. At that point, this change can be reverted.
There is an equivalent change in frontend to hide the same newsletter: https://github.com/guardian/frontend/pull/26010
There will not be any visible change on this branch currently as newsletter 6029 is not yet created (that can't happen until this change is merged).
However, you can test that the exclusion works by editing the new line to filter out an existing newsletter, IE:
`.filter((newsletter: ConsentOption) => newsletter.id !== '4222')`
would exclude "Animals Farmed"
Allows us to prevent the MMA …

filter out newsletter 6029

---

client/components/mma/identity/identity.ts

Reverses the change on https://github.com/guardian/manage-frontend/pull/1032. Not to be merged until after the journalism the newsletter related to has been announced.
There will not be any visible change on this branch until newsletter 6029 is created. After that has happened and the newsletter data from identity has updated: 
- on this branch: newsletter 6029 will be visible
- on main:  newsletter 6029 will be hidden
Newsletter 6029 will be visible on MMA shortly after the announcement.
There may be a brief period after the newsletter goes live (ie possible to subscribe) and this PR taking effect (

unhide newsletter 6029

---

client/__tests__/components/helpCentre/__snapshots__/helpCentreContactOptions.test.tsx.snap
client/components/helpCentre/HelpCentrePage.tsx
client/components/shared/CallCenterEmailAndNumbers.tsx

We are now able to reopen some of our services since the ransomware attack and can update the copy in the help centre banner. Some other changes have been requested too to keep our help centre up to date.
1) Banner.
Due to operational challenges caused by the ransomware attack on the Guardian, Customer Service phonelines in the US are currently not available. Live chat, email and UK and Australia phonelines remain unaffected. Click here for more information (to be hyperlinked to https://www.theguardian.com/media/2022/dec/21/guardian-hit-by-serious-it-incident-believed-to-be-ransomware-attack)
2) Phonelines.
Remove "Phonelines for this region are temporarily down" from the Australia phonelines section
3) UK Phone number.
Update UK phone number to  +44 (0) 330 333 6767
Visit `/help-centre/` …

Update copy on help centre for reopened services

---

client/components/shared/nav/DropdownNav.tsx

Updates the dropdown navigation component to use React Router `<Link>` elements so that client-side routing is used. (External links continue to use regular anchor elements.)
The dropdown navigation is the only navigation available on mobile devices so mobile users are unnecessarily seeing full page refreshes as they navigate around the site.

Use React Router for local links in dropdown nav

---

client/components/mma/switch/SwitchContainer.tsx
client/components/mma/switch/options/SwitchOptions.tsx
client/components/mma/switch/review/SwitchReview.tsx
cypress/integration/parallel-2/productSwitch.spec.ts

Removes a check that a user only has one Recurring Contribution during Product Switching. There is a ticket in Conversions team to allow multiple contributions to be checked out - so we should not assume this will be the case downstream.
Also fixes an issue picked up where the RC productDetail selected for switching was not being passed through in routerState (meaning MDAPI was being called on the second step), so we are now passing through the existing state to every page.
Take out multiple RCs (under the threshold amount) and product switch one of them via the account overview - the second switch page should load and not redirect to the Account Overview. 
Cypress tests have been updated to include a check of how many times MDAPI is called, on a full switch journey when coming directly …

Allow multiple Recurring Contributions in Product Switch Journey

---

client/components/mma/accountoverview/AccountOverview.stories.tsx
client/components/mma/accountoverview/AccountOverview.tsx
client/components/mma/accountoverview/InAppPurchaseCard.tsx
client/components/mma/accountoverview/PersonalisedHeader.tsx
client/components/mma/accountoverview/ProductCardConfiguration.ts
client/components/mma/billing/Billing.stories.tsx
client/components/mma/billing/Billing.tsx
client/fixtures/inAppPurchase.ts
shared/mpapiResponse.ts

This PR updates the copy and design of App subscriptions in the Account Overview and Billing page. Puzzle and News apps are distinguished by copy and colour styling.
With a user with an app subscription navigate to `/?withFeature=appSubscriptions` and see the product cards as seen in the images below. Then head to `Billing` and see the app subscriptions listed.
Account Overview
- one cancelled news app sub with fallback app store text
- one apple news app sub
- one android puzzle app sub
Billing
- one news app sub with fallback app store text
- one apple news app sub
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/pe …

Update design of IAP cards on account-overview and billing

---

client/components/mma/accountoverview/AccountOverview.tsx

Merges App subscriptions from a separate category with heading 'Subscriptions' into the same section as other Subscriptions (which come from a different data source).
See [this PR](https://github.com/guardian/manage-frontend/pull/1037)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour …

Merge app subscriptions into other 'Subscriptions' category

---

client/components/mma/dataPrivacy/DataPrivacy.styles.ts
client/components/mma/dataPrivacy/DataPrivacyPage.tsx

Updating the design for the data privacy page

Update Layout for Data Privacy UI

---

client/components/mma/cancel/cancellationSaves/CancellationSaves.stories.tsx
client/components/mma/cancel/cancellationSaves/MembershipSwitch.tsx
client/components/mma/cancel/cancellationSaves/SaveStyles.ts
client/components/mma/cancel/cancellationSaves/ValueOfSupport.tsx

Create the initial design of the Switching Page in new Membership save journey.
Added to storybook, not yet hooked up to any routes.

Membership Saves - Create Switching Page [Initial design]

---

client/components/mma/cancel/cancellationSaves/MembershipCancellationSaves.stories.tsx
client/components/mma/cancel/cancellationSaves/SaveStyles.ts
client/components/mma/cancel/cancellationSaves/SwitchingOptions.tsx
client/components/mma/shared/BenefitsStyles.tsx
client/components/mma/shared/MembershipBenefits.tsx
client/components/mma/shared/RecurringSupporterBenefits.tsx
client/components/mma/shared/SupporterPlusBenefits.tsx

Creates the new switching options pages in the Membership save journey. This is the initial design so it may change and the buttons will need wired in.
Refactored benefits styles to be in one file to prevent repetition
New scenario added to storybook as this is not yet working
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people …

Membership Cancel save offers v1 

---

client/components/mma/cancel/CancellationReasonSelection.tsx
client/components/mma/cancel/cancellationReason.ts
client/components/mma/cancel/cancellationSaves/CancellationSaves.stories.tsx
client/components/mma/cancel/cancellationSaves/MembershipCancellationLanding.tsx
client/components/mma/cancel/cancellationSaves/SaveStyles.ts
client/components/mma/cancel/cancellationSaves/SelectReason.tsx
client/components/mma/cancel/cancellationSaves/ValueOfSupport.tsx

Create Cancellation Reasons page, using the old cancellation reasons for membership. This PR also removes an unused property from the CancellationReason type. 
New item in storybook.

Membership Saves - Cancellation Reasons Page 

---

client/components/mma/shared/RecurringSupporterBenefits.tsx

Cross icons for when benefit are not available and the text that goes along with it has been greyed out as per the design

Icons and text greyed out when benefit is unavailable

---

client/components/mma/MMAPage.tsx
shared/featureSwitches.ts

Turns on the feature switch enabling app subscriptions to be shown in Account Overview, Billing and Email and Marketing pages.
With an App Subscription, go to Account Overview and witness product card under Subscriptions, go to Billing and see app subscription listed and go to Email and Marketing pages and see the relevant product opt-ins. …

Enable showing app subscriptions in MMA

---

client/components/mma/MMAPage.tsx
client/components/mma/cancel/cancellationSaves/CancellationSaves.stories.tsx
client/components/mma/cancel/cancellationSaves/MembershipCancellationLanding.tsx
client/components/mma/cancel/cancellationSaves/MembershipSwitch.tsx
client/components/mma/cancel/cancellationSaves/SaveOptions.tsx
client/components/mma/cancel/cancellationSaves/ValueOfSupport.tsx
cypress/integration/parallel-2/membershipSave.spec.ts
cypress/integration/parallel-2/productSwitch.spec.ts
shared/featureSwitches.ts

Creates routes for membership saves journey (behind a feature flag).  Add Cypress tests visiting the pages on the journey.
Enable the feature flag, then with a membership head to `cancel/membership/landing`

Create membership save routes

---

client/components/mma/cancel/CancellationSwitchEligibilityCheck.tsx
client/components/mma/cancel/cancellationSaves/CancellationSaves.stories.tsx
client/components/mma/cancel/cancellationSaves/MembershipCancellationLanding.tsx
client/fixtures/productDetail.ts
cypress/integration/parallel-2/membershipSave.spec.ts
cypress/integration/parallel-5/membership.spec.ts

Create a check to only direct users to the new membership save journey if they are eligible. 
Criteria:
1. Not in payment failure
2. User has no Recurring Support or other products
(Feature switch on)
With a user with a membership + recurring contribution - go to `cancel/membership` and see the normal journey (i.e. Please select a reason) …

Create Membership save eligibility check

---

client/components/mma/MMAPage.tsx
client/components/mma/cancel/cancellationSaves/CancellationSaves.stories.tsx
client/components/mma/cancel/cancellationSaves/ContinueMembershipConfirmation.tsx

New screen created to display at the end of the journey where a user has chosen to remain with their membership
New item in storybook.

Continue membership confirmation v1 

---

client/components/mma/cancel/cancellationSaves/MembershipSwitch.tsx
client/components/mma/shared/PaymentDetails.tsx
client/components/mma/switch/review/SwitchReview.tsx

Reuse the PaymentDetails component from Product Switch journey in new Cancellation Saves journey

Move PaymentDetails to own component and use in new journey

---

client/components/mma/MMAPage.tsx
client/components/mma/cancel/cancellationSaves/CancellationSaves.stories.tsx
client/components/mma/cancel/cancellationSaves/SwitchThankYou.tsx

New thank you screen which is part of the user journey where a user changes from a membership to a recurring contributor
Added to storybook
Storybook or (on local) switch the feature flag off and head to cancel/membership/switch-thank-you
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-col …

Switch thank you V1

---

client/components/mma/MMAPage.tsx
client/components/mma/cancel/Cancellation.stories.tsx
client/components/mma/cancel/cancellationContributionReminder.tsx
client/components/mma/cancel/cancellationSaves/CancellationSaves.stories.tsx
client/components/mma/cancel/cancellationSaves/MembershipSwitch.tsx
client/components/mma/cancel/cancellationSaves/SaveStyles.ts
client/components/mma/cancel/cancellationSaves/SelectReason.tsx
client/components/mma/cancel/cancellationSaves/SupportReminder.tsx
cypress/integration/parallel-2/cancelContribution.spec.ts
cypress/integration/parallel-2/membershipSave.spec.ts
cypress/integration/parallel-2/productSwitch.spec.ts
cypress/integration/parallel-2/updateContributionAmount.spec.ts
cypress/support/index.ts

Adds a reminder screen and API call post cancellation in the Membership cancellation saves journey. This PR also adds in the API call to send the reason on the previous screen. Also changes the existing reminder component to add a new button.
Testing locally:
Enable feature switch and confirm a cancellation on membership save journey. Click `Set Reminder`. The `api/reminders` call does not seem to work locally at time of writing.
Validation on reasons screen
New screen
After submission
Existing reminder screen
-   [ ] …

Membership Saves - Create Reminder screen

---

client/components/helpCentre/HelpCentrePage.tsx
client/components/shared/Header.tsx
client/components/shared/Main.tsx
client/components/shared/nav/DropdownNav.tsx

This PR fixes a bug where navigation via the dropdown does not work on Help Centre pages. The solution is to use normal links when on a help centre page since they are part of a different react router so the `<Link>` component does not work. The bug was introduced in this PR: https://github.com/guardian/manage-frontend/pull/1033. We will still use `<Link>` for links on non-Help Centre pages since it does not refresh the page.
Navigate to `/help-centre` and use the dropdown navigation, the links should work (and reload the page).
We should be aware that only links within MMA (and not Help Centre pages) can be linked to with the property `local` in the interface `NavItem`, and furthermore that we cannot navigate using React router between MMA and Help Centre.
-   [ ] [Tested with screen …

Fix Navigation on Help Centre

---

.storybook/FooterContextDecorator.tsx
.storybook/preview.tsx
client/__tests__/__snapshots__/main.test.tsx.snap
client/components/mma/Page.tsx
client/components/mma/switch/SwitchContainer.tsx
client/components/shared/Main.tsx
client/components/shared/footer/Footer.stories.tsx
client/components/shared/footer/Footer.tsx
client/components/shared/footer/Footerlinks.tsx
client/components/shared/footer/MinimalFooter.tsx

This PR creates a new minimal footer (similar to the one found on Support site) for use on Product Switching pages. This serves to reduce the risk associated from Apple legal reviews of the app switch journey by removing Support buttons. It is also a less cluttered footer. 
Go to any page on MMA and there should be no changes, go to `switch` and witness the new footer.
Switch page
Desktop
Tablet
Mobile
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#con …

Create Minimal Footer for use on Switch pages

---

client/components/mma/MMAPage.tsx
client/components/mma/cancelReminders/CancelReminders.stories.tsx
client/components/mma/cancelReminders/CancelReminders.tsx

This PR fixes the routing to the cancel-reminders page, and uses the `useParams` hook to get the token passed to the page. The react-router api seems to have changed since this page was built and the route was added - so it's unclear how long this page has been broken. 
Go to `/cancel-reminders/*token here*`, you should see the message "Unsubscribing" then a success or failure screen depending on if the token was valid.
The Storybook stories have been updated to use the param instead of component props.
-   [ ] [Colour …

Fix cancel-reminders page routing

---

client/components/mma/cancel/cancellationSaves/SaveStyles.ts
client/components/mma/cancel/cancellationSaves/ValueOfSupport.tsx

Update the copy and design of the Value of Support (step 2) page in the Membership Cancellation Save journey.
Go to `cancel/membership/details` (or the second step of the journey).

Update copy + design of Value of Support page

---

client/components/mma/cancel/cancellationSaves/MembershipCancellationLanding.tsx

Making changes as per the design copy:
- Removed chat to us button
- Updated wording 

Membership cancellation landing v2 cc

---

client/components/mma/reminders/CreateReminder.tsx

Improve CreateReminder component at mobile

---

client/components/mma/cancel/cancellationSaves/ContinueMembershipConfirmation.tsx
client/components/mma/cancel/cancellationSaves/SaveStyles.ts

Making changes as per the design copy:
Updated wording
Added in the next billing date 
New button style added to align with the design (buttons on the left and stackable on mobile)
Turn on feature switch and navigate to cancel/membership/thank-you with an eligible membership
Storybook …

Membership saves -  continue membership v2 

---

client/components/mma/switch/review/SwitchReview.tsx
cypress/integration/parallel-2/productSwitch.spec.ts
server/routes/api.ts
shared/productSwitchTypes.ts

Adds a new parameter to the `product-move-api` call, depending on what the products being switched are. 
>**Note**
>This should only go in once the change has been made server side, ideally so that it supports both versions.
Complete an RC to S+ product switch at `/switch`.
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-an …

Update product-move-api url to include switch type param

---

client/components/mma/cancel/cancellationSaves/CancellationSaves.stories.tsx
client/components/mma/cancel/cancellationSaves/MembershipCancellationLanding.tsx
client/components/mma/cancel/cancellationSaves/MembershipSwitch.tsx
client/components/mma/cancel/cancellationSaves/SaveStyles.ts
client/components/mma/cancel/cancellationSaves/SelectReason.tsx
client/components/mma/cancel/cancellationSaves/SwitchThankYou.tsx
client/components/mma/cancel/cancellationSaves/ValueOfSupport.tsx
cypress.json
cypress/integration/parallel-2/membershipSave.spec.ts

Updates the copy on the Switch Review page of membership cancellation switch journey. Implements the product move api call on `Confirm` button click
Go to `cancel/membership/switch-offer` and click "Confirm change"

Member Save - Switch Review Page

---

client/utilities/hooks/useAnalytics.ts

Temporarily disabling Google Analytics to see who shouts when no more data appears. This is to help validate our desire not to upgrade the account to GA4.
Visit manage.theguardian.com with full consent and confirm that no GA tag is loaded.

Temporarily disabling Google Analytics

---

client/components/mma/cancel/CancellationContainer.tsx
client/components/mma/cancel/cancellationSaves/CancellationSaves.stories.tsx
client/components/mma/cancel/cancellationSaves/MembershipCancellationLanding.tsx
client/components/mma/cancel/cancellationSaves/MembershipSwitch.tsx
client/components/mma/cancel/cancellationSaves/SaveOptions.tsx
client/components/mma/cancel/cancellationSaves/SaveStyles.ts
client/components/mma/cancel/cancellationSaves/SwitchThankYou.tsx
client/components/mma/cancel/cancellationSaves/ValueOfSupport.tsx
cypress/integration/parallel-2/membershipSave.spec.ts

Update the copy and design of the Confirmation (Flow 2) aka Switch Thank you page.
Complete a product switch from `cancel/membership/landing` - you should see the contribution amount, user email address and billing date on screen.

Membership Save - Switch Confirmation - Update copy and keep user details through journey

---

client/__tests__/components/mma/reminders/reminders.test.ts
client/components/mma/reminders/CreateReminder.tsx
client/components/mma/reminders/reminders.ts

Braze can incorrectly append a new query string to a url that already has a query string, meaning we end up with a second `?` where there should be a `&`.
Braze do not seem likely to fix this any time soon, so we can defend against it here in MMA.

Fix braze reminder query string

---

client/components/helpCentre/liveChat/LiveChat.tsx

Salesforce is releasing a new feature, "Enhanced Domains", in June 2023. This changes a number URL formats across the Salesforce application.
A full outline of impacts to our systems can be viewed [here](https://docs.google.com/document/d/1C_SCvSrwvNLRXRsmrkKnVdf-NLBYVe4afkSHewcnCGA/edit#).
One of the changing URL formats is for Salesforce Sites, which we use to serve the Live Chat widget. According to the [Salesforce documentation](https://help.salesforce.com/s/articleView?id=sf.domain_name_url_format_changes_enable_enhanced.htm&type=5) the link we need to use will change from `SitesSubdomainName.secure.force.com` to `MyDomainName.my.salesforce-sites.com`.
This should ONLY be merged after the Enhanced Domains feature has been enabled in Salesforce. Both tasks should be completed at the …

Use Enhanced Domains version of Live Chat URL in Production

---

client/components/mma/cancel/cancellationSaves/ContinueMembershipConfirmation.tsx
client/components/mma/cancel/cancellationSaves/SaveOptions.tsx
client/components/mma/cancel/cancellationSaves/SaveStyles.ts
client/components/mma/cancel/cancellationSaves/SelectReason.tsx

Updates the designs of the reason selection page of the membership save journey. Also fixes two small issues on previous pages, the price on membership confirmation, `keep my membership` button link
Navigate through the journey to `cancel/membership/reasons`
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03- …

Update designs of Reasons page

---

README.md
cdk/lib/__snapshots__/manage-frontend.test.ts.snap
cdk/lib/manage-frontend.ts
client/__tests__/components/payment/stripe.test.ts
client/utilities/stripe.ts
riff-raff.yaml
server/apiGatewayDiscovery.ts
server/stripeSetupIntentConfig.ts

There has been a lot of confusion over the years about what the different stages or environments (DEV/CODE/PROD) mean and which should be used for what. This PR is part of a piece of work intended to clear that up.
Full details are [in this document](https://docs.google.com/document/d/1wg1kMk7U7ht3AmPpsPUimtz1FkVbu5BWjijjme2598s/edit#) but in summary:
- The DEV environment refers only to a developers local machine and config settings here are things like local domain names eg. manage.thegulocal.com
- The CODE and PROD environments are for systems running in AWS or production and test versions of external systems
- Point all api gateway endpoints to their CODE versions not DEV (these will be deleted eventually)
- Remove permissions for manage to access DEV api gateway
- Rename uat to test …

Use CODE environment in AWS not DEV

---

riff-raff.yaml

#1090 had a malformed riff-raff.yaml file which broke the deploy, this fixes it.

Fix riff-raff.yaml

---

client/components/helpCentre/HelpCentre.stories.tsx
client/components/helpCentre/HelpCentreArticle.stories.tsx
client/components/helpCentre/HelpCentreTopic.stories.tsx
client/components/helpCentre/contactUs/ContactUs.stories.tsx
client/components/mma/accountoverview/AccountOverview.stories.tsx
client/components/mma/billing/Billing.stories.tsx
client/components/mma/cancel/Cancellation.stories.tsx
client/components/mma/dataPrivacy/DataPrivacy.stories.tsx
client/components/mma/identity/emailAndMarketing/EmailAndMarketing.stories.tsx
client/components/mma/identity/publicProfile/PublicProfile.stories.tsx
client/components/mma/identity/settings/Settings.stories.tsx
package.json
yarn.lock

Replaces all uses of `fetch-mock` in storybook stories with `msw` - introduced by me in #923 because MSW was seemingly more easier to use. In the intervening time there has been a mix of `fetch-mock` and `msw` - which causes stories to break when clicking between the two.
If all Chromatic tests are unaffected it should be all good. …

Replace fetch-mock with msw in stories

---

client/components/mma/cancel/cancellationSaves/ConfirmMembershipCancellation.tsx
client/components/mma/cancel/cancellationSaves/ContinueMembershipConfirmation.tsx
client/components/mma/cancel/cancellationSaves/SaveOptions.tsx
client/components/mma/cancel/cancellationSaves/ValueOfSupport.tsx
client/components/mma/shared/ProgressIndicator.stories.tsx
client/components/mma/shared/ProgressIndicatorV2.tsx
client/components/mma/shared/ProgressStepper.tsx

This PR adds a new progress bar component - as seen in new cancellation journey designs - and uses them in the new journey.
Figma:
The component:
On a page:

Create new progress bar component

---

client/components/helpCentre/HelpCentrePage.tsx

This PR adds a banner onto the help centre to make users aware of the holiday stop issue. More details are detailed in this ticket: https://trello.com/c/LOlqxGha/4165-csr-bug-report-case-03536146-holiday-stops-not-being-fulfilled
Check banner is visible on help centre
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-tech …

Help centre banner - holiday stop issue

---

client/components/mma/cancel/cancellationSaves/ConfirmMembershipCancellation.tsx
client/components/mma/cancel/cancellationSaves/SelectReason.tsx

Adds the routerState to the navigation between `cancel` and `reasons` in order to preserve the email address of the user

Cancellation saves - preserve state (for email address) between pages

---

client/components/mma/cancel/cancellationSaves/MembershipSwitch.tsx
client/components/mma/cancel/cancellationSaves/SelectReason.tsx

Adds masking to PII fields which prevents QM from capturing it.
Deploy onto CODE and ask QM to check that all fields on the journey are captured and PII is blocked.

QM masking tags added to PII in cancellation journey

---

client/components/helpCentre/HelpCentrePage.tsx

Removing the help centre banner re a potential holiday stop issue. This has been closed as it is not a wide spread issue.

Removing help centre banner re the holiday stop issue

---

client/components/mma/cancel/cancellationSaves/MembershipCancellationLanding.tsx
client/components/mma/cancel/cancellationSaves/SaveOptions.tsx
client/components/mma/cancel/cancellationSaves/ValueOfSupport.tsx

- Rename step 2 on the Options page to be 'Options' in the progress bar
- Remove image placeholder
- Change eligibility check to ignore recently cancelled products
Remove this
Before: step 2 had wrong label

Small Cancellation Save Fixes

---

client/__tests__/components/callCenterEmailAndNumbers.test.tsx
client/components/mma/cancel/cancellationSaves/CancellationSaves.stories.tsx
client/components/mma/cancel/cancellationSaves/MembershipCancellationLanding.tsx
client/components/shared/CallCenterEmailAndNumbers.tsx
client/components/shared/CallCentreEmailAndNumbers.stories.tsx
client/fixtures/productBuilder/productBuilder.ts
client/fixtures/productBuilder/testProducts.ts

This PR adds an option to the `CallCentreEmailAndNumbers` component to have one region open by default. 
Navigate to `cancel/membership?withFeature=membershipSave` with USD currency and see the US and Canada section open first.

Open Specific Region in Call Centre Contact Component

---

client/components/mma/cancel/cancellationSaves/ConfirmMembershipCancellation.tsx
client/components/mma/cancel/cancellationSaves/ContinueMembershipConfirmation.tsx
client/components/mma/cancel/cancellationSaves/MembershipSwitch.tsx
client/components/mma/cancel/cancellationSaves/ValueOfSupport.tsx

Minor changes after feedback from the E2E testing on the Membership cancellation journey.
**Continue Membership Confirmation** 
- Updated wording to remove _new_ from the price of the Membership. This should cover the scenario where a customer is already paying £7.
- Updated Continue to the Guardian button to be a LinkButton so it actually redirects to the Guardian homepage
**Membership Switch** 
- Updated T &Cs link to direct users to the contributor policy
**Value of Support**
- 'Back to my account' button returns to the Account Overview page
**Confirm Membership Cancellation**
- Cancellation button on hover has an update background as per the figma
Check links,  buttons and wording on CODE or locally when going through the journey 
Confirm cancellation button background on hover 
-   [ …

Membership saves testing changes

---

client/components/mma/cancel/cancellationSaves/MembershipSwitch.tsx
client/components/mma/switch/review/SwitchReview.tsx
client/fixtures/productMove.ts

To support a [change](https://github.com/guardian/support-service-lambdas/pull/2003) on the server side we need to pass a new property in product switching - `checkChargeAmountBeforeUpdate`. 
Take out a Recurring Contribution worth less than 10 GBP and navigate to `/switch` and complete the journey.
This PR needs to be merged before the server side PR.
-   [ ] [The change doesn't use only colour …

Add new property to product-move-api calls

---

client/components/mma/shared/benefits/BenefitsConfiguration.ts
client/components/mma/switch/options/SwitchOptions.tsx

DRR have requested that we don't displayed the supporter newsletter and uninterrupted reading from the Supporter+ benefits. This is because they are already included benefits for RC. This change doesn't impact the benefits being listed on the Account Overview.
Either on Storybook or product switch journey, check that only two benefits are displayed and they are not about the newsletter or uninterrupted ready.
Account Overview is not impacted by this change …

Removal of newsletter and uninterrupted reading from Support+ benefits

---

client/components/mma/cancel/cancellationSaves/MembershipCancellationLanding.tsx
client/fixtures/productBuilder/productBuilder.ts
client/fixtures/productBuilder/testProducts.ts
cypress/integration/parallel-2/membershipSave.spec.ts

The annual membership price rise pricelist has not been confirmed - memberships with a yearly plan should be excluded from the membership saves journey.
Take out a membership with annual rate plan - go to `cancel/membership?withFeature=membershipSave` and see the default journey (choose reason). …

Create eligibility check for annual members

---

shared/featureSwitches.ts

Turns on the feature flag that will redirect eligible users to the new membership saves cancellation flow.
Our OKR !

Turn on membership saves

---

.yarnrc

By default pin dependency to exact version, instead of ^version (following on from #1085). Pinning these is the recommendation and making it the default behaviour means we don't have to ask people on a PR if they haven't done so.

Default to exact package versions

---

client/components/mma/switch/review/SwitchReview.tsx

When an error happens during product switching scroll to the error message.
Acceptance Criteria:
When a switch fails, user is anchored down to see error message
User can scroll up and continue as usual once the error has been viewed (not forced back to anchor point).
https://github.com/guardian/manage-frontend/assets/114918544/06235a8d-bb67-494b-9d6a-bdc2391ca1e3
-   [ ] [The change doesn't use …

Anchor to error message during Product Switching

---

client/components/mma/cancel/cancellationSaves/SelectReason.tsx
cypress/integration/parallel-2/membershipSave.spec.ts
server/routes/api.ts

This is part of the new cancellation saves work, which allows customers to optionally select the reason for cancelling at the end of the journey, after the cancellation is complete.
Previously, customers had to select the cancellation reason before cancelling. When confirming the cancellation, the reason would be sent to the API, which would perform both the reason update and cancellation. Now, these two actions must be done separately.
[see the PR in members-data-api](https://github.com/guardian/members-data-api/pull/1024)

add new endpoint for updating subscription cancellation reason in Zuora

---

cypress/integration/parallel-3/holidayStops.spec.ts

When updating the test product #1100 - accidentally commented out most of the cypress test for holiday stops. This wasn't caught in the diff since it wasn't rendered because the diff was too large (`Large diffs are not rendered by default.`) 🤦 
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use- …

Uncomment tests that should not be commented out

---

client/components/mma/cancel/cancellationSaves/MembershipCancellationLanding.tsx

the server side is NOT using the price passed through from the client
add new 2023 price membership in zuora -> cancel membership and see OLD journey

Add eligibility check for post price risen members

---

client/components/mma/identity/emailAndMarketing/NewsletterSection.tsx
client/components/mma/identity/idapi/newsletters.ts
client/components/mma/identity/models.ts
client/fixtures/newsletters.ts

Newsletters in the MMA page are currently grouped using the theme property. This is different to the grouping logic in the [all Newsletters Page](https://www.theguardian.com/email-newsletters). 
Updates the Newsletters type to include the group property which is [now returned from the identity API](https://github.com/guardian/identity/pull/2420) & uses this to group Newsletters instead of theme. The Colour mapping has been updated too. With the `News in Brief` & `News in Depth` sections using the News colour. 
Verify changes as expected and Subscribe / unsubscribe behaviour as before
Behaviour very similar to previous state. Not expecting any issues. 
Needs a test in code but should be ok
**Before**
**After**
-   [ ] [Tested with screen …

Group newsletters based on Group property

---

client/components/helpCentre/HelpCentrePage.tsx
client/components/mma/MMAPage.tsx
client/utilities/hooks/useScrollToTop.ts

Removed in #1128 - brings back the `useScrollToTop` hook on mma pages
Scroll down a page - then click a reactRouter link (eg in sidenav) and the page should go back to the top (logo at the top visible)

Bring back useScrollToTop

---

client/components/helpCentre/HelpCentrePage.tsx

Adds banner to the help centre re phone lines being down in Aus due to maintenance 

Help centre banner re phone line maintenance in Aus

---

client/components/helpCentre/HelpCentrePage.tsx

Remove help centre banner as it is no longer required

Remove help centre banner as it is no longer required.

---

client/components/mma/delivery/records/DeliveryRecords.stories.tsx

Update the delivery records storybook - use the normal GuardianWeekly productType. The extra const seems unnecessary and made taking screenshots from the storybook confusing. If you click the `Report a problem` button in the story now you see:
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-o …

Update delivery records storybook

---

client/utilities/deliveryAddress.ts
cypress/integration/parallel-4/deliveryAddress.spec.ts
shared/productTypes.ts

Attempting to fix a bug: 
Supporter Plus products are returned when using the filter string `ContentSubscription` ([mdapi reference](https://github.com/guardian/members-data-api/blob/65a424f35ee484f2e30a3e9bbfed4062e1e8c6e8/membership-attribute-service/app/services/AccountDetailsFromZuora.scala#L207)). MMA expects everything returned when using that filter string to belong to the `GROUPED_PRODUCT_TYPE` of `subscriptions`. In the delivery address components there is a lookup to get the specific product type which threw an error since `supporterPlus` is not in `subscriptions`. 
This PR fixes the error by using the `mmaCategory` from `MDAPI` to get the `GROUPED_PRODUCT_TYPE` instead of assuming it is `subscriptions` (the supporterPlus is then filtered out anyway)
Take out a supporter plus - …

Fix deliveryAddress change bug when user has supporterPlus

---

client/__tests__/components/updateAmount/supporterPlusUpdateAmount.test.tsx
client/components/mma/accountoverview/updateAmount/SupporterPlusUpdateAmountForm.tsx
cypress/integration/parallel-1/updateContributionAmount.spec.ts
server/routes/api.ts
shared/featureSwitches.ts

Call the new endpoint in to update the amount of a supporter plus subscription. This is still behind a feature flag.
With a supporter plus sub, go to `/?withFeature=supporterPlusUpdateAmount` and click `Manage Recurring Support'. Change the amount, click confirm. 
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technolo …

Call new update supporter plus amount endpoint

---

client/components/mma/switch/review/SwitchReview.stories.tsx
client/components/mma/switch/review/SwitchReview.tsx
client/fixtures/productBuilder/testProducts.ts

Updates the disclaimer Ts and Cs in Product Switching (as we have also done on Support frontend). This copy is dynamic for annual vs monthly.
Take out a Recurring Contribution. Go to `/switch`, click 'Upgrade' CTA. See new Ts and Cs at bottom of `/switch/review`
Monthly, £
Yearly, NZD
-   [x] [The change doesn't use only colour to convey …

Update Supporter Plus V2 Ts and Cs in Product Switching

---

client/components/mma/holiday/ExistingHolidayStopActions.tsx
client/components/mma/holiday/HolidayConfirmed.tsx
client/components/mma/holiday/HolidayStopApi.ts
client/components/mma/holiday/HolidayStopsContainer.tsx
client/components/mma/holiday/HolidayStopsPage.tsx
client/components/mma/holiday/HolidaysOverview.tsx
client/components/mma/holiday/Modal.tsx
client/components/mma/holiday/SummaryTable.tsx
client/components/mma/shared/asyncComponents/DefaultApiResponseHandler.tsx
cypress/integration/parallel-3/holidayStops.spec.ts

Replace the AsyncLoader pattern with a hooks based approach in the HolidayStopsContainer component
Can still create, amend and delete holiday stops. Take out eg a Guardian Weekly and go to `/suspend/guardianweekly`

Replace GetHolidayStopsAsyncLoader with hooks pattern

---

client/components/helpCentre/HelpCentrePage.tsx

Removes the banner on the help centre regarding US phonelines being down.
Go https://manage.theguardian.com/help-centre - do not see red banner

Remove help centre banner issue

---

client/__tests__/components/helpCentre/__snapshots__/helpCentreContactOptions.test.tsx.snap
client/components/shared/CallCenterEmailAndNumbers.tsx

Remove the message about US phonelines being down under contact options.

Remove 'Phonelines down' message from contact numbers

---

client/components/mma/accountoverview/AccountOverview.stories.tsx

Small harmless change to try kick off a CD deployment - replace deprecated type

update deprecated storybook type

---

client/__tests__/components/updateAmount/supporterPlusUpdateAmount.test.tsx
client/__tests__/supporterPlus.test.tsx
client/components/mma/accountoverview/ManageProduct.stories.tsx
client/components/mma/accountoverview/updateAmount/SupporterPlusUpdateAmountForm.tsx
client/components/mma/accountoverview/updateAmount/UpdateAmount.tsx
client/fixtures/productBuilder/testProducts.ts
client/utilities/supporterPlusPricing.ts
cypress/integration/parallel-1/updateContributionAmount.spec.ts

Updates to copy + design in Supporter Plus Amount Change component. Copy should not reference 'contributions'.
Also updates the suggested amounts for annual subscriptions, the suggested amounts will be 10%, 25% and 50% more than the current amount.
Take out supporter plus -> go to `/recurringsupport` and click "Change amount". 
See new label 'Choose your new amount', lower amount below the threshold and see error message that does not reference 'contribution'
Before
After
Mobile …

Supporter Plus Amount Change Copy Updates

---

client/components/mma/MMAPage.tsx
client/components/mma/MMAPageSkeleton.tsx
client/components/mma/accountoverview/ManageProduct.stories.tsx
client/components/mma/accountoverview/ManageProduct.tsx
client/components/mma/accountoverview/ProductCard.tsx
client/components/mma/delivery/address/DeliveryAddressConfirmation.tsx
cypress/integration/parallel-5/membership.spec.ts
cypress/integration/parallel-5/patron.spec.ts
shared/productTypes.ts

This PR changes the URL that the `Manage product` page exists on - and adds async loading if you go directly to this page through the URL.
The motivation for this change is to have a URL that readers can be linked to which will allow them to change the amount they support. I.e. `/support` in this case. In order to do this the routing for this page has changed from being at the `GROUPED_PRODUCT_TYPE` url to the specific `PRODUCT_TYPE`. For example, previously when managing a supporter plus subscription the URL would be `/recurringSupport`, it will now be `/support`. The same applies to other products, homedelivery, guardianweekly etc. 
Async loading: before, this page only worked when clicked through from another page that passes props. Now, there is logic to try and load the product from …

Create a specific URL for Manage product pages

---

client/components/mma/accountoverview/updateAmount/SupporterPlusUpdateAmountForm.tsx
shared/featureSwitches.ts

Turn the feature switch on for Supporter Plus Update Amount

Turn Supporter Plus Value Change on!

---

shared/productResponse.ts
shared/productTypes.ts

Add a fallback for a situation seen on prod - "Annual" being displayed on a cancelled Monthly sub.
What I saw: 
what the API response had: 
```
"plan": {
        "name": "Supporter Plus",
        "price": 1200,
        "currency": "£",
        "currencyISO": "GBP",
        "billingPeriod": "month"
  },
  "currentPlans": [],
  "futurePlans": [],
````
-   [ ] [The change doesn't use only colour to …

Add fallback for no billingPeriod in currentPlan

---

client/components/mma/MMAPage.tsx
client/components/mma/shared/benefits/BenefitsConfiguration.ts
client/components/mma/upgrade/UpgradeSupport.stories.tsx
client/components/mma/upgrade/UpgradeSupport.tsx
client/components/mma/upgrade/UpgradeSupportAmountForm.tsx
client/components/mma/upgrade/UpgradeSupportContainer.tsx

First iteration of the new screen to support the RC users to increase their contribution amount. 
This will a url accessible only via an email but can be viewed via **/upgrade-support**
Landing on the screen
Selecting an amount (above threshold)
Selecting Choose your amount
Entering in same amount as currently contributing
Entering amount below threshold 
Entering 0 
-   [ ] [The change doesn't …

Upgrade Support - new screen (V1)

---

client/components/mma/upgrade/UpgradeSupportAmountForm.tsx

Fix for type error on main build which was caused by a missing parameter being passed into a function

Build fix 

---

client/components/mma/MMAPage.tsx
client/components/mma/upgrade/UpgradeSupport.stories.tsx
client/components/mma/upgrade/UpgradeSupportThankYou.tsx

New thank you screen for when a user upgrades their contribution amount and **does not** switch to S+. This is still a wip and this PR covers the first iteration of the designs.
This also changes the thank you page urls. When a users switches product they will see the `upgrade-support/switch-thank-you `page but in this case they will see the `upgrade-support/thank-you` page
Locally head to `upgrade-support/thank-you` or check new scenario on storybook …

Thank you no switch V1

---

client/components/mma/shared/SupporterPlusTsAndCs.tsx
client/components/mma/switch/review/SwitchReview.tsx
client/components/mma/upgrade/ConfirmForm.tsx
client/components/mma/upgrade/UpgradeSupport.tsx
client/components/mma/upgrade/UpgradeSupportAmountForm.tsx
client/components/mma/upgrade/UpgradeSupportContainer.tsx
client/utilities/currencyIso.ts

Adds a skeleton for step two of the upgrade support journey. A round up button with logic plus confirm button and `onClick` function.
Also refactors the Supporter + Ts and Cs to be generic across pages
https://trello.com/c/aUIKFe2H/4314-mma-upsell-select-your-support-step-2-rc-not-switching-product-first-designs
Go to `/upgrade-support`, see new component
No UI regressions from refactoring Ts and Cs
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contra …

Select your support step 2 - not switching product v1

---

client/components/mma/accountoverview/updateAmount/SupporterPlusUpdateAmountForm.tsx
client/components/mma/shared/SupporterPlusTsAndCs.tsx
client/components/mma/switch/SwitchContainer.tsx
client/components/mma/switch/review/SwitchReview.tsx
client/components/mma/upgrade/ConfirmForm.tsx
client/components/mma/upgrade/UpgradeSupportAmountForm.tsx
client/utilities/supporterPlusPricing.ts
shared/productSwitchTypes.ts

Adds the switch preview api call before showing step 2, to be able to render the payment amount.
The preview call is called every time the amount changes (with the threshold amount if a lower amount is chosen)
Go to '/upgrade-support`, click 'Continue with xx' - see Loading bar where step 2 (confirm) should be …

Upgrade Support - add preview api call

---

client/components/mma/upgrade/ConfirmForm.tsx
client/components/mma/upgrade/UpgradeSupport.tsx

This PR makes two changes.
1. Roundup to the currency specific threshold (eg if GBP roundup to 10, if USD roundup to 13)
2. Hide round up if threshold is not one of suggested amounts (since we cannot highlight it)
Don't show roundup if amount to round up to is not present
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and- …

Upgrade - RC Roundup

---

client/components/mma/accountoverview/CancelledProductCard.tsx
client/components/mma/accountoverview/ProductCard.tsx
client/components/mma/accountoverview/ProductCardStyles.ts
client/components/mma/accountoverview/SingleContributionCard.tsx
client/components/mma/cancel/cancellationContributionReminder.tsx
client/components/mma/cancel/cancellationSaves/ConfirmMembershipCancellation.tsx
client/components/mma/cancel/cancellationSaves/ContinueMembershipConfirmation.tsx
client/components/mma/cancel/cancellationSaves/MembershipCancellationLanding.tsx
client/components/mma/cancel/cancellationSaves/MembershipSwitch.tsx
client/components/mma/cancel/cancellationSaves/SaveOptions.tsx
client/components/mma/cancel/cancellationSaves/SaveStyles.ts
client/components/mma/cancel/cancellationSaves/SelectReason.tsx
client/components/mma/cancel/cancellationSaves/SwitchThankYou.tsx
client/components/mma/cancel/cancellationSaves/ValueOfSupport.tsx
client/components/mma/switch/SwitchStyles.ts
client/components/mma/switch/complete/SwitchComplete.tsx
client/components/mma/switch/options/SwitchOptions.tsx
client/components/mma/switch/review/SwitchReview.tsx
client/components/mma/upgrade/UpgradeSupportSwitchThankYou.tsx
client/styles/ButtonStyles.ts

Refactoring of the button CSS which is called multiple times in different style files into one generic file called ButtonStyles. This includes:
- moving `buttonCentredCss`
- moving `buttonLayoutCss`
- moving `stackedButtonLayoutCss`
- moving `reverseStackedButtonLayoutCss`
- moving `stackedButtonLeftLayoutCss` 
- moving `buttonContainerCss` 
- moving `buttonMutedCss` 
- moving`wideButtonCss` 
There should be no breaking changes and no UI changes
New generic ButtonStyles file is used when accessing button CSS and any new button css which may be used in multiple places is added here …

Refactor: Button CSS into generic file

---

client/components/mma/upgrade/ConfirmForm.tsx
client/components/mma/upgrade/UpgradeSupport.tsx
client/utilities/productMovePreview.ts
client/utilities/productUtils.ts
cypress/integration/parallel-2/upgradeSupport.spec.ts
shared/productSwitchTypes.ts

Refactors the upgrade journey to only call the `product-move-api` preview once. It uses the refund amount from the response to calculate the amount payable today. This change also puts the api call in the parent component of where it was previously (from `ConfirmForm` into `UpgradeSupport`), meaning it happens when the component first renders not when the `Continue` button is clicked
In effect we are calculating two response variables that are normally determined [in the product-move-api](https://github.com/guardian/support-service-lambdas/blob/main/handlers/product-move-api/src/main/scala/com/gu/productmove/switchtype/RecurringContributionToSupporterPlus.scala) on the client side instead
1. Go to `/upgrade-support`.
2. In network tab see api call to fetch preview info
3. Select an amount …

One product-move-api preview call in upgrade journey

---

client/components/mma/cancel/cancellationSaves/SwitchThankYou.tsx
client/components/mma/shared/Heading.tsx
client/components/mma/switch/complete/SwitchComplete.tsx
client/components/mma/switch/review/SwitchReview.tsx
client/components/mma/upgrade/ConfirmForm.tsx
client/components/mma/upgrade/UpgradeSupport.stories.tsx
client/components/mma/upgrade/UpgradeSupportAmountForm.tsx
client/components/mma/upgrade/UpgradeSupportSwitchThankYou.tsx
client/components/mma/upgrade/UpgradeSupportThankYou.tsx
client/components/shared/productSwitch/SwitchPaymentInfo.tsx
client/fixtures/productMove.ts
client/styles/GenericStyles.ts
cypress/integration/parallel-2/upgradeSupport.spec.ts

Implement final designs ([figma](https://www.figma.com/file/BAqeBncOfn51nXxk9zrFxe/Upsell?node-id=1438%3A29057&mode=dev)) of the second step upgrade support journey - when a user switches to supporter plus.
Refactors the product switch journey to use the same info about next payment dates, for reuse. Also adds a borderless heading style
See storybook or go to `/upgrade-support`, choose an amount above the S+ threshold and click 'Continue with x' …

Upgrade Support - Step 2 (Second iteration)

---

client/components/mma/upgrade/ConfirmForm.tsx
client/components/mma/upgrade/UpgradeSupport.tsx
client/components/mma/upgrade/UpgradeSupportAmountForm.tsx

Implement final designs from [figma](https://www.figma.com/file/BAqeBncOfn51nXxk9zrFxe/Upsell?node-id=1556%3A60600&mode=dev) for the Round Up component
Go to `/upgrade-support`, with a contribution amount (eg £5) that has a suggested amount < the threshold (eg £10) and has the threshold as an option. See the Round Up component, toggle to round up and see the threshold amount become selected.
- …

Upgrade support - round up (final designs)

---

client/components/mma/upgrade/ConfirmForm.tsx
client/components/mma/upgrade/UpgradeSupportAmountForm.tsx
client/utilities/utils.ts

Within upgrade-support journey, adds a function to scroll smoothly to step 2 with id `confirm-change` and set a hash in the URL.
Also added a utility function to wait until an element is in the DOM and then get it (as step 2 will load async) that uses [Mutation Observer](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to observe mutations. Based on [this stackoverflow answer](https://stackoverflow.com/a/61511955)
Manually: go to `/upgrade-support` and click "Continue with"
Automated: not sure
Happy days:
https://github.com/guardian/manage-frontend/assets/114918544/da11bc90-79c6-442d-9cb4-d8bf09032767
Case where second step hasn't loaded yet: 
https://github.com/guardian/manage-frontend/assets/114918544/43f9d895-042b-4799-a95d-e5f16d195a1e
Mobile: …

Upgrade Support: Smooth scroll to confirmation step after clicking 'Continue with...'

---

client/components/mma/accountoverview/ProductCardConfiguration.ts
client/components/mma/shared/benefits/BenefitsConfiguration.ts
server/routes/api.ts
shared/productTypes.ts

[This change to members-data-api](https://github.com/guardian/members-data-api/pull/1036) makes National Delivery subs appear in the `user-attributes/me/mma` endpoint used by manage-frontend. This breaks manage however because National Delivery is not defined as a product so the site doesn't know how to display it.
This PR fixes that issue.

Add National Delivery as a product type

---

manage-frontend-static/README.md

This just adds a bit of context around the assets-static pattern for manage-frontend

add justification for assets-static bucket

---

client/components/mma/upgrade/UpgradeSupportSwitchThankYou.tsx
client/components/mma/upgrade/UpgradeSupportThankYou.tsx

Adding tag on email fields on the upsell thank you pages. Quantum metric (QM) check for the tag on their side and make sure that it is masked when capturing the sessions. We will get confirmation from QM that it has been blocked too before this is live.
Check on the thank you pages that you can see the masking tag like in the snapshots below: …

Upsell: QM block email address on thank you pages

---

client/components/mma/switch/review/SwitchReview.tsx
client/components/mma/upgrade/ConfirmForm.tsx
client/components/mma/upgrade/UpgradeSupportContainer.tsx
client/components/shared/productSwitch/SwitchErrorSummary.tsx
cypress/integration/parallel-2/upgradeSupport.spec.ts

Adds error handling for when an api call fails on a user confirming their change. This should show an error message. Refactors and reuses the switch error messaging from product switching journey.
New Cypress test added for when switching fails
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use- …

Upgrade Support - Add Error Handling for confirmation

---

client/components/mma/shared/benefits/BenefitsConfiguration.ts
client/components/mma/upgrade/ConfirmForm.tsx
client/components/mma/upgrade/UpgradeSupportAmountForm.tsx
client/components/mma/upgrade/UpgradeSupportSwitchThankYou.tsx
client/components/mma/upgrade/UpgradeSupportThankYou.tsx
client/components/shared/productSwitch/SwitchPaymentInfo.tsx

Change the copy after review:
- Update first checkpoint to “More impactful funding of journalism”
- Add full stops to the body copy in the What Happens Next component. Do not add a full stop if the sentence ends with an email.
- Update “all benefits” to “extras”
- RC thank you page: update Your billing date copy. The billing date doesn't change
- Change "increase" to "change" if it's a decrease
RC to RC
Before
After
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03 …

Upgrade Support - Copy Changes

---

client/components/mma/upgrade/UpgradeSupportAmountForm.tsx

Reordered the condition by having a numeric value passed in on the right hand side of the &&. This stops the 0 from showing beneath the box when 0 is entered. 
Documentation for [reference](https://react.dev/learn/conditional-rendering#logical-and-operator-) of why this was happening:
_Pitfall
Don’t put numbers on the left side of &&.
To test the condition, JavaScript converts the left side to a boolean automatically. However, if the left side is 0, then the whole expression gets that value (0), and React will happily render 0 rather than nothing._
Before 
After
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people- …

Stop zero appearing under input box

---

client/components/mma/upgrade/ConfirmForm.tsx
client/components/mma/upgrade/UpgradeSupportContainer.tsx
cypress/integration/parallel-2/upgradeSupport.spec.ts

As with product switching and membership cancellation, we don't want people to press back in the browser and repeat their confirmation step (triggering an api call that will fail). To prevent this behaviour this PR adds a parameter in routerState that gets checked within the container
Go to `/upgrade-support`, confirm change and on thank you page press browser back. Expect to see account overview.
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast …

Upgrade Journey- add mechanism to prevent going back

---

client/components/mma/upgrade/ConfirmForm.tsx
client/components/mma/upgrade/UpgradeSupport.stories.tsx
client/components/mma/upgrade/UpgradeSupportContainer.tsx
client/components/mma/upgrade/UpgradeSupportSwitchThankYou.tsx

Fixes a bug in the Switch Thank You page after upgrading to S+. The page was using the original billing date instead of the new one after switching (which comes from the product move preview response.)
Go to `/upgrade-support` and select above the threshold, see the next payment date 
Confirm and see the **same date** on the thank you page (ignore the wrong charge in the screenshots they're from separate tests)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visu …

Upgrade Support - Use next payment date from preview response after switch

---

client/components/mma/upgrade/ConfirmForm.tsx
client/components/mma/upgrade/UpgradeSupportStyles.ts
client/components/mma/upgrade/UpgradeSupportSwitchThankYou.tsx

Minor tweaks:
- Adding 'all' into sentence about extras on ConfirmForm.tsx
- Changed colour of 'Back to Account Overview' link to match design
- Changes wording in Extras benefits on UpgradeSupportSwitchThankYou.tsx to match design

Small design changes from Rob

---

client/components/mma/shared/benefits/BenefitsCard.tsx
client/components/mma/upgrade/UpgradeSupportAmountForm.tsx

Fixes two issues on the first upgrade-support page:
1.  Icon size should be 20px
2. Prevent scrolling within input box
(from Rob)
1. Visual check
2. Click "other" amount, click within text box, try to scroll (box becomes unfocused)

Upgrade support - value page fixes

---

client/components/mma/accountoverview/SingleContributionCard.tsx

Fix a react warning:
Acquire a single contribution, don't see warning in console

fix: add key in SingleContributionCard

---

server/routes/api.ts
shared/productTypes.ts

Return the `nationaldelivery` product type when looking in config
Handle an error when augmenting MDAPI response so it doesn't return wrong shape of response
Take out national delivery product, view account overview with no error and click `Manage subscription` and go to `/nationaldelivery` …

Enable national delivery product

---

client/components/helpCentre/HelpCentrePage.tsx

Adds a known issue banner onto the Help Center to notify users that phone lines are down in Canada and the USA

Help centre banner: phone lines being unavailable in Canada and the US

---

client/components/mma/accountoverview/CancelledProductCard.tsx
client/components/mma/accountoverview/EmptyAccountOverview.tsx
client/components/mma/accountoverview/PersonalisedHeader.tsx
client/components/mma/accountoverview/ProductCard.tsx
client/components/mma/billing/InvoicesTable.tsx
client/components/mma/delivery/address/DeliveryAddressDisplay.tsx
client/components/mma/delivery/address/Select.tsx
client/components/mma/delivery/records/DeliveryRecordCard.tsx
client/components/mma/delivery/records/DeliveryRecordsProblemConfirmation.tsx
client/components/mma/delivery/records/DeliveryRecordsProblemReview.tsx
client/components/mma/delivery/records/ProductDetailsTable.tsx
client/components/mma/identity/emailAndMarketing/EmailSettingsSection.tsx
client/components/mma/identity/form/FormField.tsx
client/components/mma/identity/publicProfile/ProfileFormSection.tsx
client/components/mma/paymentUpdate/CurrentPaymentDetail.tsx
client/components/mma/paymentUpdate/card/FlexCardElement.tsx
client/components/mma/paymentUpdate/dd/DirectDebitInputForm.tsx
client/components/mma/shared/ProductDescriptionListTable.tsx
client/components/shared/Input.tsx

This adds the QM masking tag `data-qm-masking="blocklist"` to fields within MMA which contain PII. We are doing this so when sessions are captured at QM any PII is masked and therefore not captured by the recorded sessions.
This PR also includes some tidy up to imports by shortening the paths and upgrading any deprecated imports to use the correct ones.
Check screens on Storybook or local/CODE and any areas of PII should have the masked tag visible in the inspector
PII may be exposed and captured on QM, however this will be tested on CODE by QM to ensure that all areas are covered. …

Add QM masking tag throughout MMA (and tiny import tidy up)

---

client/components/mma/holiday/HolidayReview.tsx
client/components/mma/holiday/HolidayStopApi.ts
cypress/e2e/parallel-3/holidayStops.cy.ts

Fix amending an existing holiday stop - this was not checking the correct value and therefore calling the api with a `POST` instead of a `PATCH` request. 
Fix a secondary bug when amending a non-confirmed holiday stop. The wrong dates were being set when this button was clicked, which made the holiday stop to amend appear as an existing suspension. (See image below.) This PR removes the second Amend button.
With a newspaper delivery product, click Manage suspensions, click "Amend", pick dates, click "Confirm", see loading message "Amending...", do not see error.
Before
Bug after pressing "Amend" on review page, the existing suspension should not appear as that is what is being amended
After
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-t …

Fix Holiday Stops Amend

---

cypress/e2e/parallel-3/holidayStops.cy.ts

Update the "can amend an existing holiday stop from overview page" Cypress test to click the "Confirm" button and mock the `PATCH` request. This is a followup from #1225 which fixed the component to actually check the correct variable to choose `PATCH` 
Cypress tests pass in CI
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/peopl …

Check for 'patch' request in amend holiday stops cypress test

---

client/components/mma/delivery/address/DeliveryAddressForm.tsx

We currently don't have the capability to allow users with national deliveries to update their addresses via MMA. This change no longer shows the address form and  displays a new message to call the CSR team if you want to change addresses.
This change also prevents users who may have any other delivery as well as a national delivery product from updating their address.
On MMA with a national delivery product -> click manage subscription -> click manage delivery address you should see the new message displayed asking you to call a CSR to update your address.
On MMA with a home delivery product (as well a national delivery) -> click manage subscription -> click manage delivery address you should see the new message displayed asking you to call a CSR to update your address.
National …

Block address update for national delivery

---

client/components/mma/delivery/address/DeliveryAddressForm.tsx
client/components/mma/delivery/records/DeliveryAddressStep.tsx
client/components/mma/delivery/records/ReadOnlyAddressDisplay.tsx
client/components/mma/shared/CallCentrePrompt.stories.tsx
client/components/mma/shared/CallCentrePrompt.tsx

Block "National Delivery" subscribers from changing their address, we have not built any functionality to allow choosing a new delivery provider so users are directed to call the call centre.
With a National Delivery product
Go to Manage subscription 
-> Click Manage delivery history
-> Report a problem
-> See Step 3
-> See CSR prompt 
National Delivery
Other Print Subscription AND National Delivery
After click:
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-vis …

National Delivery - Block Delivery Issues page from allowing you to change address

---

client/components/mma/delivery/address/DeliveryAddressForm.tsx
client/components/mma/delivery/records/DeliveryAddressStep.tsx
client/fixtures/productBuilder/baseProducts.ts
client/fixtures/productBuilder/testProducts.ts
cypress/e2e/parallel-4/deliveryAddress.cy.ts
cypress/e2e/parallel-4/deliveryRecords.cy.ts

Adds Cypress tests for National Delivery address updates being disabled. A small refactoring of the check to do this is included in the PR.
Cypress tests pass. 

Add Cypress Tests for National Delivery Address Blocking

---

cypress/e2e/parallel-4/deliveryAddress.cy.ts

Follow up to #1234, as suggested by @charleycampbell. This PR adds a Cypress test where a user has multiple delivery products, one is national delivery and therefore they cannot update any of the addresses. 

National Delivery - add test case for multiple delivery addresses, where one is national

---

client/components/mma/paymentUpdate/PaymentDetailUpdateConfirmation.tsx
client/fixtures/productBuilder/productBuilder.ts

Adds a small fix to support quarterly billing periods in update payment component. And to the test product builder. 
Take out quarterly Guardian Weekly. 
Update payment method. 
Witness "quarterly" on screen.
There are a lot of places in the code that assume certain products are either monthly or annual. Digisubs and Guardian Weekly can have quarterly billing periods. How do we ensure we don't make incorrect assumptions?
Before
After
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people …

Fix: Add support for quarterly billing period

---

client/components/mma/cancel/voucher/VoucherCancellationFlowStart.tsx

Removes a message in newspaper voucher cancellation flow about covid-19, and an inaccurate number of holiday stops.
Vouchers are only available in the UK, and self serve cancellation is not available in the UK...so hard to test.
Before
After
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of- …

Remove message about covid-19 and inaccurate holidays

---

client/components/mma/cancel/cancellationSaves/CancellationLanding.tsx
cypress/e2e/parallel-2/membershipSave.cy.ts
shared/productResponse.ts

Redesign the cancellation landing page as per [design](https://www.figma.com/file/sx9jlOcpcK9V0gNgj4GWtW/Cancellation-saves-Q3-2023?type=design&node-id=155-53050&mode=design&t=CGHvl5rUB4H2LkRB-0) (except the accordion which will be done separately)
Membership cancellation flow should still work - Cypress tests pass. …

Redesign Cancellation Landing page

---

client/components/mma/accountoverview/SingleContributionCard.tsx
cypress/e2e/parallel-1/accountOverview.cy.ts
shared/productTypes.ts

This PR changes the public facing bits of MMA to use the term "One-time support" instead of "Single Contribution"
Take out a One-time contribution in the support checkout, visit account overview and see the product card. Should say "One-time support".
Before
After
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technolo …

Rename 'Single Contribution' to 'One-time'

---

client/components/helpCentre/diagnosticInformation/BrowserInformation.tsx
package.json
yarn.lock

Previously, a version of the **guardian/commercial-core** package was being used, which was 8 months old and is no longer maintained. This PR upgrades to use the latest version of **guardian/commercial**, which is the actively maintained package for the commercial code.

Upgrade from guardian/commercial-core to guardian/commercial

---

client/components/mma/cancel/cancellationSaves/digipack/ThankYouOffer.stories.tsx
client/components/mma/cancel/cancellationSaves/digipack/ThankYouOffer.tsx
client/fixtures/productBuilder/testProducts.ts

This PR creates the Thank you + Offer page component ([figma](https://www.figma.com/file/sx9jlOcpcK9V0gNgj4GWtW/DigiSub-Price-Rise-%E2%80%94-cancellation-saves?type=design&node-id=162-1897&mode=design&t=S8EomeJqNPk59B5b-4)) for the new DigiSub cancellation journey.
See the new storybook story. …

Digisub Save: thank you + offer

---

client/components/mma/cancel/cancellationSaves/digipack/ConfirmCancellation.tsx
client/components/mma/cancel/cancellationSaves/digipack/DigiSubSaves.stories.tsx

New screen to confirm that users want to cancel their subscription
Test via storybook as URLs don't yet exist

Digisub confirm cancel V1

---

client/__tests__/components/updateAmount/contributionUpdateAmount.test.tsx
client/__tests__/components/updateAmount/supporterPlusUpdateAmount.test.tsx
client/components/mma/accountoverview/ProductCard.tsx
client/fixtures/productBuilder/baseProducts.ts
shared/productResponse.ts

Building atop https://github.com/guardian/members-data-api/pull/1038, this change responds to Partner and Patron Members with details of their Events benefit, if they are eligible.
1) Manually assign yourself to a Partner or Patron Member in Zuora, selecting Events features
2) Log into MMA and see your Account Details page
3) New Guardian Live - Eventbrite ... section should be there
4) Create an amendment to Update your Product, switching the features to Books
5) Screen should not show the new section - be exactly as it was before.
Before:
After:
And after entering either code on Eventbrite: …

Show Partner and Patron Event benefits on relevant Product Card Section

---

client/components/mma/cancel/CancellationReasonReview.tsx
client/components/mma/cancel/cancellationSaves/membership/ConfirmMembershipCancellation.tsx
client/components/mma/cancel/cancellationSaves/membership/SelectReason.tsx

Add back `gaData` that cancellation-sf-cases api is expecting. 
Error message:
"Bad request: request body couldn't be parsed: List((/gaData,List(JsonValidationError(List(error.path.missing),List()))))"
without this property
Tested locally, without this included the cancellation Review shows "Oops" and network call fails. With it it passes. …

Fix Cancellations: add `gaData` back into body

---

client/components/mma/identity/emailAndMarketing/ConsentSection.tsx
client/fixtures/consents.ts
cypress/e2e/parallel-6/emailAndMarketing.cy.ts
shared/mpapiResponse.ts
shared/productTypes.ts
shared/softOptInIDs.ts

Adds the `similar_guardian_products` consent into the `marketingEmailConsents` list so it always shows up in on the emails and marketing page.
It's also no longer classified as a "product" consent, so we've removed from anywhere which said it was a product consent.
This consent used to be a "product" consent, so would previously only be given if a user has purchased a product. However this consent is being renamed, and repurposed into a new soft opt in for newly registered users also. So it's being moved out from being a "product" consent, and into the "main" marketing consents area. It will continue to use the same ID.
New copy:
**Guardian products and support**
Information on our products and ways to support and enjoy our independent journalism.
Other related work elsewhere:
Firstly …

Add `similar_guardian_products` to `marketingEmailConsents` list

---

client/components/mma/MMAPage.tsx
client/components/mma/accountoverview/AccountOverview.tsx
client/components/mma/paymentUpdate/PaymentDetailUpdate.tsx
client/components/mma/paymentUpdate/PaymentDetailUpdateConfirmation.tsx
client/components/mma/paymentUpdate/PaymentDetailUpdateContainer.tsx
client/components/mma/shared/IsFromAppProps.ts
client/components/mma/shared/PaymentFailureAlertIfApplicable.tsx
client/components/mma/shared/ProblemAlert.tsx
client/fixtures/productBuilder/testProducts.ts
cypress/e2e/parallel-1/updatePaymentDetails.cy.ts

Adds a new route to MMA, `/app`, which sets a prop `isFromApp` to true that is passed to the payment update journey using state. It is only passed through the component that highlights payment failure and its "Update payment method" button.
With a product in payment failure, go to `/app` and click "Update payment failure" in the top "A payment needs your attention" box. See the next screen, update payment details, see confirmation and "return to app" button.
Repeat the journey going to `/` and do not see "return to app" after confirmation.
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physi …

Add a "Return to app" button for payment failure

---

client/components/mma/cancel/membership/MembershipCancellationReasons.tsx

Remove commented out cancellation reason data, and a comment saying it should be restored "after Coronavirus". 
It's been gone for a while, and no one has raised it. We won't increase expectations on CSRs.

Remove commented out data from cancellation reasons

---

client/components/mma/cancel/cancellationSaves/digipack/DigiSubDiscountConfirm.tsx
client/components/mma/cancel/cancellationSaves/digipack/ThankYouOffer.tsx
client/utilities/pricingConfig/digisubDiscountPricing.ts

Adds the discounted and non-discounted prices to the digisub saves journeys, and how many months the discount applies for. Using data stored in a config object.
If the api endpoint can return this information we will use that instead, but it's yet to be built as of this PR.
Digisub saves storybook screens …

Add discount prices and number of months in save screens

---

package.json
yarn.lock

Bump `@types/node` to match the version of node specified in the `.nvmrc` file. We should try to keep these in sync as per [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/p …

Bump types node

---

client/components/helpCentre/HelpCentrePage.tsx

Adding message for Xmas opening times

Add xmas opening times help centre message

---

client/components/mma/cancel/cancellationReason.ts
client/components/mma/cancel/cancellationSaves/digipack/ConfirmDigiSubCancellation.tsx
client/components/mma/cancel/cancellationSaves/digipack/DigiSubDiscountConfirmed.tsx

Two minor changes after testing of the digisub journey: 
- default cancellation reason has been changed to ```mma_cancellation_default``` 
- updated the font on the subheading fro discount confirmation page

digisub tidy ups v1

---

shared/featureSwitches.ts

This puts the digisub saves journey live - starting with the manage product page for digital subscriptions.

Digisub saves - turn on feature switch

---

shared/featureSwitches.ts

Reverts guardian/manage-frontend#1280
Turned on yesterday - seeing error in cloudwatch logs for discount-api, users not seeing discounts
"Caught error in index.ts  AccessDeniedException: User: arn:assumed-role/support-PROD-discount-api-discountapilambdaServiceR-/discount-api-PROD is not authorized to perform: secretsmanager:GetSecretValue on resource: PROD/Zuora-OAuth/SupportServiceLambdas because no identity-based policy allows the secretsmanager:GetSecretValue action"

Revert "Digisub saves - turn on feature switch"

---

package.json
server/__tests__/middleware/identityMiddleware.test.ts
server/__tests__/middleware/okta.test.ts
server/__tests__/middleware/oktaServerSideAuthMiddleware.test.ts
server/__tests__/oauth.test.ts
server/identityLocalState.ts
server/middleware/identityMiddleware.ts
server/middleware/oktaServerSideAuthMiddleware.ts
server/oauth.ts
server/oauthConfig.ts
server/okta.ts
server/routes/api.ts
server/routes/oauth.ts
shared/globals.ts
tsconfig.json
yarn.lock

Co-authored by @pvighi and @raphaelkabo.
As part of the MMA OAuth migration, this PR introduces a new middleware, `withOktaServerSideValidation`, which verifies an Okta OAuth access token against the [Okta API's `/userinfo` endpoint](https://developer.okta.com/docs/reference/api/oidc/#userinfo). This endpoint returns user data if a user with a valid, active session exists for the supplied access token. More importantly, if the access token is not associated with a valid, active session (i.e. if the user has been signed out), the endpoint returns an error code.
The middleware is always invoked after the standard `withIdentity` middleware function. `withIdentity` performs a **local** check on the access token, validating that it hasn't been tampered with, that it isn't expired, and that its …

OAuth migration | Serverside Okta validation middleware

---

server/__tests__/middleware/identityMiddleware.test.ts
server/__tests__/oauth.test.ts
server/middleware/identityMiddleware.ts
server/oauth.ts
server/oauthConfig.ts

In the new flow, we first check if the access and ID tokens are set. If so, we check if the GU_SO cookie was set after the access token's iat claim, which means that the user signed out after they generated these tokens. In this case, we follow the signout behaviour. Otherwise, we handle the subsequent cases (IDAPI cookies are/aren't set). If the GU_SO cookie was set before the iat claim, we can safely ignore it, and continue the flow as above.
For documentation on this, see this PR: https://github.com/guardian/gateway/pull/2530

OAuth migration | Refactor GU_SO handling based on new flow

---

client/utilities/analytics.ts
client/utilities/hooks/useAnalytics.ts
client/utilities/hooks/useScrollToHashElement.ts

Remove some `any`s from the codebase that didn't require much refactoring

Remove `any`s - low hanging fruit

---

client/components/helpCentre/HelpCentrePage.tsx

Adds a banner to the Help Centre about an ongoing incident with the premium app:
`We are currently investigating reports of a technical issue for customers signing into The Guardian live app on Android. We are working to resolve this and apologise for any inconvenience caused.`

Add App Incident banner to Help Centre

---

server/__tests__/middleware/identityMiddleware.test.ts
server/__tests__/oauth.test.ts
server/apiProxy.ts
server/oauth.ts
server/oauthConfig.ts

This changes two things, one resulting from the other.
After we enabled Okta on PROD MMA, we noticed a few browsers were experiencing redirect loops. We worked out that this was happening in the following situation:
- The current Okta session was newer than the `max_age` parameter being sent by MMA.
- Because of this, Okta considered the current session valid, and when a browser landed on MMA, immediately redirected the browser back to MMA, without refreshing or setting any cookies.
- However, for some reason (unknown), the `SC_GU_LA` cookie was missing from the browser context in the affected browsers. I suspect this was a race condition: the `SC_GU_LA` cookie had expired and been deleted before the OAuth session became invalid, despite the fact that both are set to 30 minutes.
- Seeing …

OAuth migration | Remove SC_GU_LA cookie check | Migrate MDAPI calls to use OAuth tokens

---

server/__tests__/middleware/identityMiddleware.test.ts
server/__tests__/oauth.test.ts
server/apiProxy.ts
server/oauth.ts
server/oauthConfig.ts

Reverts guardian/manage-frontend#1294
This broke MMA when using IDAPI cookies, so reverting this change.
The `authorizationOrCookieHeader` function only works in Okta, and does not take into account cases where Okta is disabled! So when Okta was turned off, it broke as it was trying to use non-existant okta tokens.

Revert "OAuth migration | Remove SC_GU_LA cookie check | Migrate MDAPI calls to use OAuth tokens"

---

client/components/helpCentre/HelpCentrePage.tsx

Reverts #1292
The banner can be removed on Monday 22 January.

Remove 21 Jan downtime banner

---

client/fixtures/productBuilder/baseProducts.ts

Here we update the fixture to reflect the data which is returned by MDAPI, changed in guardian/members-data-api#1041. This fixes a (mocked) Cypress test which is currently failing on main.
See also #1291.

Self cancellation of Digi subs is now controlled by MDAPI

---

server/awsIntegration.ts
server/routes/core.ts

Fix the help centre sitemap by asserting the content type that it actually is in S3. Spotted because I was testing turning on  eslint rule `'@typescript-eslint/prefer-nullish-coalescing'`
Go to https://manage.theguardian.com/sitemap.txt, see content instead of `[]` as before this change. 
Should we rather just change the content type of the file in S3 to `text/plain` (which seems to be more accurate?) - or fix whatever is creating that file
Before
After …

Fix help centre sitemap

---

.github/workflows/cypress-e2e.yml

We've previously had this trigger configuration for the E2E testing GitHub Action:
```
on:
pull_request:
branches:
- main
```
This runs the action on activity in a PR pointing at `main`, but _not_ when the PR is merged in.
We're changing it to this:
```
on:
push:
branches:
- main
pull_request:
branches:
- main
```
Which will also run the E2E tests once a commit is merged into `main`, i.e. when a PR is accepted and merged in.

Run E2E tests on push to main

---

client/HelpCentrePage.ts
client/MMAPage.ts

Adds the referrer as a custom tag (`gu:referrer`) to Sentry browser error reports from help centre pages. If not available it'll be set to "none". We're trying to track down the origin of some 404s we're seeing.
I deployed to CODE and forced an error. The referrer showed up in Sentry: …

Add referrer as a tag in Sentry browser errors in the help centre

---

client/components/mma/MMAPage.tsx
client/components/mma/signInError/SignInError.stories.tsx
client/components/mma/signInError/SignInError.tsx
cypress/tests/e2e/authExpiry.cy.ts
server/__tests__/middleware/identityMiddleware.test.ts
server/__tests__/middleware/okta.test.ts
server/__tests__/oauth.test.ts
server/middleware/identityMiddleware.ts
server/oauth.ts
server/oktaConfig.ts
server/routes/oauth.ts
shared/requiresSignin.ts

After deploying https://github.com/guardian/manage-frontend/pull/1294 and enabling Okta on PROD manage-frontend, we discovered an Okta behaviour which was undocumented in the sense that it was _only_ documented in a modal in the UI, three layers down, after you clicked a specific radio button, and the actual documentation completely contradicted it:
One is reminded of a quote from _The Hitchhiker's Guide To The Galaxy_:
> “But the plans were on display…”
“On display? I eventually had to go down to the cellar to find them.”
“That’s the display department.”
“With a flashlight.”
“Ah, well, the lights had probably gone.”
“So had the stairs.”
“But look, you found the notice, didn’t you?”
“Yes,” said Arthur, “yes I did. It was on display in the bottom of a locked filing cabinet stuck in a …

OAuth migration | Force user to sign in if Access token `auth_time` older than 30 minutes

---

server/oauthConfig.ts

MMA needs to be granted the `guardian.members-data-api.update.self.secure` scope to allow users to edit their details in MDAPI.
Okta Terraform PR: https://github.com/guardian/identity-platform/pull/700

OAuth migration | Add `guardian.members-data-api.update.self.secure` scope

---

package.json
yarn.lock

This includes a change to the regulatory framework used by US cookie banners to include the multi-state privacy agreement.  Details can be found  on this [Trello Card](https://trello.com/c/6qAHXGHq).
Using a guest or incognito window, make a selection in the cookie banner and enter MMA. In devtools console window, `window.guCmpHotFix.cmp.version` should match that in the package.json file.  In MMA under the data privacy tab, you should be able to re-open and interact with the the Privacy Manager through the Privacy Settings option in the page and in the footer.
Cookie banner shows and can be interacted with.
Can be rolled back if necessary though, in this case, there may be some ad revenue impact.
No UI changes.
No UI changes.

Bump cmp to 13.8.0 to pick up MSPS changes

---

client/components/helpCentre/HelpCentrePage.tsx

Adding banner to the help centre as phonelines in the US and Canada are experiencing technical issues.
The banner is visible on the help centre in production

Adding banner to help centre as phonelines are down in US and Canada

---

client/components/mma/identity/idapi/user.ts
client/components/mma/identity/identity.ts
client/components/mma/identity/models.ts
client/components/mma/identity/publicProfile/PublicProfile.tsx
cypress/lib/signInOkta.ts
cypress/support/commands.ts
cypress/tests/e2e/e2e.cy.ts
server/routes/idapi.ts

As part of the OAuth migration, we've removed an old bug in IDAPI - being able to set your username more than once, if you happened to know the API endpoint to hit (because setting username just used `POST /user/me`). We've already introduced a new IDAPI endpoint, `POST /user/me/username`, which only allows setting username once and only if it's not been set before. Once OAuth authorization to IDAPI is enabled in MMA, we will also be preventing the username being changed via `POST /user/me`. This PR modifies the MMA frontend to use the new endpoint, and adds an E2E test for username updating.
- https://github.com/guardian/identity/pull/2492, because we need to let IDAPI create test users without a preset username before the E2E tests here pass.

OAuth migration | Use new set username route

---

client/components/mma/identity/emailAndMarketing/NewsletterSection.tsx

Remove masterclass from description in "your newsletters" section
before 
after

remove mention of masterclass in "your newsletters" description

---

client/components/helpCentre/HelpCentrePage.tsx

The issue with phone lines in the US and Canada has been resolved so we can remove the banner.
(Reverts #1310).
Running MMA locally I can no longer see the banner at https://manage.thegulocal.com/help-centre.

Remove help centre banner (US/Canada phone lines)

---

client/components/shared/productSwitch/SwitchErrorSummary.tsx

The contact centre have pointed out that the email address provided in the error shown in the product switching journey is not correct, which will cause some confusion/frustration for customers:
It was also noted that this error indicates there may be an issue with the customer's payment method, but it is in fact returned for a variety of product switch errors (for instance, if the customer subscription is not in a state that allows a switch). This again might confuse customers, but this would be a lot more work to fix.

Correct typo in email provided for product switch errors

---

client/components/helpCentre/HelpCentrePage.tsx

This add a banner message to the help centre as phone lines are unavailable in US, Canada and Australia.
Go to the help centre and check banner is visible.

Adding banner to help centre as phone lines are down

---

client/components/helpCentre/HelpCentrePage.tsx

The issue with the customer service phone lines in the USA, Canada and Australia has been fixed, so the Known Issue banner can be removed from the Help Centre page.
this is the associated PR: https://trello.com/c/6943ZTb5/179-remove-banner-from-help-centre
This has been tested locally and also in CODE. See the screenshot below:
Before
After …

remove known issue message, as call centre phone lines are now working

---

server/routes/api.ts
server/routes/core.ts
server/server.ts
shared/featureSwitches.ts
shared/requiresSignin.ts

Adds a content security policy report header to all requests so that we can audit which endpoints need adding to a future content-security-policy header
as per docs at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only

content security policy audit

---

server/server.ts

At the moment we are trying to report on CSP violations, however there are huge numbers of vialoations being logged for manage.theguardian.com, which should definitely be allowed.  In the first 1000 results we mostly could only find manage.theguardian.com.
this PR adds 'self' as an allowed source which should hopefully reduce the noise.  Also sourcepoint.
After this we can do more PRs to add other domains based on the results from cloudwatch logs.

Add basic CSP to manage-frontend

---

server/apiGatewayDiscovery.ts
server/routes/api.ts

This PR changes manage-frontend so that it uses the [new product-switch api](https://github.com/guardian/support-service-lambdas/pull/2201) for recurring contribution to supporter plus product switches.
There is another type of product switch from membership to recurring contribution, but this is not currently handled by the new api and so will still call the old one.

Use new product-switch-api for recurring contribution to supporter plus

---

server/server.ts

Add more values to the csp report header in order to make the cloudwatch logs less noisy and narrow in on a final csp header

CSP report header allow list additions

---

client/components/mma/accountoverview/AccountOverview.tsx
client/components/mma/accountoverview/ManageProduct.stories.tsx
client/components/mma/accountoverview/ProductCard.tsx
client/components/mma/cancel/CancellationSummary.tsx
client/components/mma/cancel/contributions/ContributionsCancellationFlowStart.tsx
client/components/mma/cancel/supporterplus/SupporterplusCancellationFlowStart.tsx
client/components/mma/shared/benefits/BenefitsToggle.tsx
client/components/mma/switch/SwitchContainer.tsx
client/fixtures/productBuilder/testProducts.ts
cypress/tests/mocked/parallel-1/updateContributionAmount.cy.ts
cypress/tests/mocked/parallel-2/cancelContribution.cy.ts
cypress/tests/mocked/parallel-2/cancelSupporterPlus.cy.ts
cypress/tests/mocked/parallel-2/productSwitch.cy.ts
cypress/tests/mocked/parallel-4/deliveryAddress.cy.ts
shared/productTypes.ts

Copy changes to refelect a switch from `Monthly + extras` and `Annual + extras` to `All-access digital`. Adjacent copy changes `Recurring support` to become `subscription` and visually grouping contributions and all access digital products into the 'subscriptions' sub section on the account overview

'+ extras' product name change

---

server/server.ts

Although we would prefer not to do this, the way that emotion (and probably more generally css in js) works is by changing inline style tags via js. However this will hopefully be a intermediate step towards a better approach perhaps using a hash or a nonce to validate specific inline styles within the csp header.
- https://docs.google.com/document/d/1Vi7m35w46F72z6n4fucsxm6i28xbmn2iMfPGM7zWGz8/edit
- https://docs.google.com/document/d/1qV01OMUMrVPorLLAYj9aT4zTIITw99bAfirRgfc_R3I/edit

add default-style 'unsafe-inline' entry to the csp header

---

server/apiGatewayDiscovery.ts
server/routes/api.ts

Updates manage-frontend to use the new [update-supporter-plus-amount api](https://github.com/guardian/support-service-lambdas/pull/2289) rather than the old product-move-api for supporter plus amount changes.

Use update-supporter-plus-amount api

---

server/server.ts

Change invalid `default-style` to the correct `style-src` https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src
This will allow inline styles for `<style>` and `<link>` tags as well as inline `style` attribute.
This is not a welcome attribute but a necessary one in order to implement a csp header in manage. Hopefully at a later date we can look into using a hash or nonce to validate specific inline sources.

csp header css update

---

script/ci.sh

Up until now the final production build was being run with no lockfile. This meant that the versions of dependencies which end up being used in production can be different from those used during development. 
This PR fixes that issue.
We actually found this because of an issue in the okta library, where a newer version of a dependency broke the library, this PR has more information: https://github.com/guardian/gateway/pull/2775

Make sure that the production build uses the current lockfile

---

server/routes/mpapi.ts

Fix conditional check that would fail if the left hand side of the condition returned a falsey value (the right hand side of the condition would try to access a property of undefined)

fix conditional check

---

client/fixtures/productBuilder/testProducts.ts
client/fixtures/productMove.ts
client/utilities/pricingConfig/suggestedAmounts.ts
client/utilities/pricingConfig/supporterPlusPricing.ts
cypress/tests/mocked/parallel-2/upgradeSupport.cy.ts

Update the supporter plus min amount threshold prices to align with an inbound checkout price rise
https://trello.com/c/yp41n8NB/353-supporter-plus-price-rise-upsell

supporter plus price rise

---

client/components/mma/accountoverview/updateAmount/SupporterPlusUpdateAmountForm.tsx
client/fixtures/productBuilder/testProducts.ts
cypress/tests/mocked/parallel-1/updateContributionAmount.cy.ts

If you have a supporter plus at an old price that is below the new minumum, the update amount form should reflect that in the copy re the new minimum amount you can change it to

copy update for update amount SP form (with old min amount)

---

package.json
yarn.lock

security fix: force `ws` peer dependency to use a patched/fixed version

ws peer dependency fix

---

client/components/mma/shared/ProgressIndicator.stories.tsx
client/components/mma/shared/ProgressIndicator.tsx
client/components/mma/shared/ProgressStepper.stories.tsx

Seperates out the ProgressIndicator (older) and ProgressStepper (new) components into seperate stories. Quick tidy up in order to help with the eventual aim of replacing the ProgressIndicator component entirely.

ProgressIndicator and ProgressStepper seperate stories

---

.github/CODEOWNERS

Remove CODEOWNERS because it requests reviews from everyone in the team automatically as soon as anyone raises a PR.  This is a problem because it's spammy and also it's no longer clear whether PRs are ready for review.

Revert "Add Value as CODEOWNERS"

---

.github/pull_request_template.md
README.md

As discussed in support mob it would be useful to make it easier to see which team owns the repo, this PR adds the info to the PR teplate and the readme.
Readme:

Add owners info to readme/pr template

---

client/__tests__/components/identity/__snapshots__/NewsletterPreference.test.tsx.snap
client/components/mma/identity/MarketingCheckbox.tsx
client/components/mma/identity/MarketingToggle.tsx
client/components/mma/identity/NewsletterPreference.tsx
client/fixtures/consents.ts
cypress/tests/e2e/e2e.cy.ts
cypress/tests/mocked/parallel-6/emailAndMarketing.cy.ts

We used a string label to target a checkbox in our Cypress tests - this has broken because the label changed in the backend.
We now set the `data-cy` HTML attribute to the id of the newsletter/consent for that checkbox. The ID never changes even if the label does, so this will make our tests much more reliable.
Tested by the tests passing!

Fix flaky cypress tests to use `data-cy`

---

client/components/mma/identity/idapi/user.ts

When the user sets their username, on success, the API returns a partial user response object containing only the new username. In the MMA handler, we assume that the user response is always at least complete enough to include the  `user.statusFields` property, which it doesn't in this case - the handler throws as a result. The UX is that the user sees an error message when setting their username even though the call succeeds, and the form field doesn't disappear, meaning they can keep trying to change their username, getting more and more confused each time until they leave the Guardian and never come back.
We make the fetch for the `user.statusFields` property optional.

Fix set username component by not throwing on incomplete user object

---

server/html.ts
server/routes/api.ts
server/routes/helpCentreFrontend.ts
server/routes/mmaFrontend.ts
server/server.ts
shared/featureSwitches.ts

Rework csp report header to work with inline script hashes and `strict-dynamic` to allow those inline scripts to load further scripts
https://auth0.com/blog/deploying-csp-in-spa/
https://web.dev/articles/strict-csp#adopting-a-strict-csp

CSP script hashes report only

---

cdk/yarn.lock

Updates minor versions of braces and ws to mitigate dependabot high vulnerabilities
https://github.com/guardian/manage-frontend/security/dependabot/134
https://github.com/guardian/manage-frontend/security/dependabot/132

braces and ws version bumps

---

client/components/mma/switch/options/SwitchOptions.tsx
cypress/tests/mocked/parallel-2/productSwitch.cy.ts

Stop people with supporter plus subscriptions from using the contribution to supporter plus switch journey
This is just a little clientside nicety. It seems as though we were getting some traffic to the /switch route from users with a supporter plus subscription, which shouldn't be possible unless they have manually gone to this url, instead of letting them attempt a failed switch we can show the user an error message and send them off to the account overview.

restrict switch journey for supporter plus subs

---

client/components/helpCentre/HelpCentrePage.tsx

New help centre banner copy requested by customer operations.
Adds the new help centre banner copy.
In CODE:

Add new help centre banner

---

server/routes/index.ts
server/routes/newspaperArchive.ts
server/server.ts

An authentication endpoint to give users access to newspapers.com archive of the Guardian using their third party authentication endpoint.
Creates a new route at `/newspaperArchive/auth` that redirects to the URL returned by their API.
This relies on a new S3 secret for the auth key, which I've uploaded for DEV, CODE and PROD
We want to test this as a benefit to the Tier 3 product, initially the user experience will be a link within MMA only for those with this product. For the test we won't be checking the product in the endpoint but at the client side logic rendering the link.

Create newspaper archive endpoint

---

yarn.lock

update peer micromatch dependency version to fix snyk vulnerability
https://app.snyk.io/vuln/SNYK-JS-MICROMATCH-6838728

update peer micromatch dependency version to fix snyk vulnerability

---

client/components/mma/cancel/Cancellation.stories.tsx
client/components/mma/cancel/cancellationSaves/supporterplus/SupporterPlusOffer.tsx
client/components/mma/cancel/cancellationSaves/supporterplus/SupporterPlusOfferConfirmed.tsx
client/components/mma/cancel/cancellationSaves/supporterplus/SupporterPlusOfferReview.tsx
client/utilities/discountPreview.ts
cypress/tests/mocked/parallel-2/cancelSupporterPlus.cy.ts

Use the discount api response to return the next payment price (after the cancellation offer period ends). This should handle the case where the returning payment price will be different from the price paid before the offer was taken up, a price rise for example 👍

Use discount api response for cancellation offer payment date

---

client/components/mma/cancel/membership/MembershipCancellationFlowStart.tsx
shared/productResponse.ts

Product tier `Partner` was missing from the `getSpecificProductTypeFromTier` function switch statement which would result in client side errors for `Parnter` products. Instead the switch statement contained `Friend` which is no longer needed. This pr replaces `Friend` with `Partner` in the `getSpecificProductTypeFromTier` switch statement and removes all other references to `Friend` ... we have no more friends! :(

product type fixes

---

package.json
yarn.lock

Force express versions 4.15.4 and 4.17.3 to use version 4.21.0 (now the only version used) instead of version 4.18.2.
This should help with recent peer dependency vulnerabilities with path-to-regexp and body-parser

Consolidate express versions

---

package.json
yarn.lock

Remove unnecessary web socket dependency resolutions (it looks as though specific resolution versioning like this doesn't work and the versions of ws that we use are all vulnerability free anyway)
link to resolution documentation: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

Remove unnecessary web socket dependency resolutions

---

client/__tests__/components/identity/MarketingCheckbox.test.tsx
client/__tests__/components/identity/__snapshots__/DropMenu.test.tsx.snap
client/__tests__/components/identity/__snapshots__/NewsletterPreference.test.tsx.snap
client/components/mma/identity/DropMenu.tsx
client/components/mma/identity/MarketingCheckbox.tsx
client/components/mma/identity/NewsletterPreference.tsx
client/components/mma/shared/Checkbox.stories.tsx
client/components/mma/shared/Checkbox.tsx
cypress/tests/e2e/e2e.cy.ts

Current the "Email & Marketing" page is a bit of a headache to navigate using a screen reader, there are 2 major issues in particular:
- Dropdowns are not marked as interactive, they appear as regular text to screen readers, and they also cannot be toggled using the expected keys "Space" or "Enter"
- Checkboxes cannot be toggled when navigated to with a screen reader, more context on this below.
- Removes hidden `input` in consent checkboxes. I believe these were here to try and make the checkbox more accessible, but they seem to have the opposite effect at the moment as screen readers will focus them preferentially instead of the "real" checkbox, and these hidden checkboxes aren't hooked up properly to accept input.
- Correctly handle onKeyDown events in the Dropdown and Checkboxes, as …

fix(accessibility): Improve accessibility of "Email & Marketing" page.

---

server/routes/newspaperArchive.ts

Currently we have an endpoint that redirects a user to newspapers dot com with a token.
This adds a mechanism to return the user to the image they were viewing. Newspapers.com will construct a url to send them to our endpoint. Eg going to -> https://manage.thegulocal.com/newspaperArchive/auth/?ncom-return-url=https%3A%2F%2Ftheguardian.newspapers.com%2Fimage%2F258351828%2F
redirects the user to this screen
The popup modal shouldn't be there but we do have "Free access" in the top right hand corner and you can view the page once you dismiss the modal.
1. Find out why the popup is showing or if we're not constructing this URL correctly 
2. Add a check for supporter status to this endpoint

Newspaper Archive endpoint - add ncom-return-url support

---

server/routes/newspaperArchive.ts

In #1404 we added a check to supporter entitlements to the newspaper archive auth endpoint
This PR adds some zod parsing to make it more typesafe. I'm using `parse` rather than `safeParse`. Any parsing errors should get picked up by the try catch at the top level of the route

Newspaper archive endpoint: add parsing

---

package.json
yarn.lock

Force update of `http-proxy-middleware` peer dependency ... there was no update available for `webpack-dev-server` at the time of writing which is the core dependency that consumers `http-proxy-middleware`
This update fixes a Denial of service vulnerability in `http-proxy-middleware` reported by dependabot and snyk.

force update of peer dependency http-proxy-middleware

---

server/middleware/identityMiddleware.ts
server/routes/newspaperArchive.ts

We have an authentication endpoint to redirect users to newspapers dot com. This allows us to deliver a new benefit to subscribers of the Digital + Print product. The endpoint includes a feature that allows users to go back to the same page they were looking at, included as a link on a n com sign in modal. At the moment this doesn't work because the query param gets stripped out by our authentication middleware. 
Modal with sign in link:
Example URL:
https://manage.theguardian.com/newspaperArchive/auth?ncom-return-url=https%3A%2F%2Ftheguardian.newspapers.com%2Fimage%2F259880906%2F%3Fmatch%3D1%26terms%3Dking%2527s%2520place
This PR adds an override to the URL sanitisation in order to preserve the `ncom-return-url` query param, and a check that the hostname is indeed newspapers dot com.

Newspaper archive auth - add query params override, validate return URL

---

client/components/mma/cancel/CancellationJourneyFunnel.tsx
shared/globals.ts

Fire a custom Quantum metric event at the start of the cancellation journey.
This is so that we can identify the billing period of the product eg monthly or annual.
The event string sent will look something like this: 
`cancellation start | all-access digital subscription | billing period: month`

fire custom quantum metric event at the start of the cancellation flow

---

client/components/mma/cancel/CancellationReasonReview.tsx

Restricts the user from progressing down the cancellation offer journey if they have an annual support plus product. This is a temporary fix until we release the annual supporter plus offer.
Currently (before this pr) the client side would check whether of not the user has a support plus product (regardless of the billing period) and then proceed to call the discount api to find out if the user is eligable for the offer. The client was reliant on the api to return a falsey response for any billing periods that we don't yet support. It looks as though the api was changed to support annual offers, but the journey on the frontend and possibly the braze campaign haven't yet been set up to support this.
This is a temporary fix on the frontend to stop annual users from proceeding down an …

Restrict supporter plus offers to those with monthly billing periods

---

server/routes/newspaperArchive.ts

We have an endpoint to redirect users from newspapers.com back again with a third party authentication token
This PR adds a cloudwatch metric to track this happening
Possibly add an alarm if this hasn't happened in a while?

Add cloudwatch metric for redirecting from ncom

---

client/__tests__/utils.test.ts
client/utilities/utils.ts

Replace the existing shuffle array sort function with an algorithm that fairly randomises the contents. The new approach is based on the fisher-yates algothrithm (https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle) a nice example of which you can see here: [Fisher–Yates Shuffle](https://bost.ocks.org/mike/shuffle/)
@johnduffell rightly pointed out in a previous pr (https://github.com/guardian/manage-frontend/pull/1415#discussion_r1846461396) that the randomisation of the output array wasn't all that random; 
results from his testing: 
```
Object.entries([...Array(1000000).keys().map(() => [1,2,3,4,5,6,7,8,9,10].sort( () => .5 - Math.random() )[0])].sort().reduce((acc, num) => {const e = {...acc};e[num]=acc[num] + 1; return e;}, …
```

fairer array sorting algorithm

---

client/__tests__/components/updateAmount/contributionUpdateAmount.test.tsx
client/__tests__/components/updateAmount/supporterPlusUpdateAmount.test.tsx
client/components/mma/accountoverview/ProductCard.tsx
client/components/mma/shared/NextPaymentDetails.tsx
client/components/mma/shared/SupporterPlusTsAndCs.tsx
client/components/mma/upgrade/ConfirmForm.tsx
client/components/shared/productSwitch/SwitchPaymentInfo.tsx
client/fixtures/productBuilder/productBuilder.ts
shared/productResponse.ts
shared/productTypes.ts

Restrict the account overview 'Your offer is active' message to monthly customers (until we have a more detailed response from mdapi about the offer status of a product to allow us to distinguish between offer types). 
This should stop annual users from seeing a monthly offer message on the account overview.
A later pr will add the annual offer message in once more work has been done in mdapi to return the info needed to display the message.

account overview offer period restriction

---

client/components/helpCentre/HelpCentrePage.tsx

The banner created in #1423 is no longer needed
Reverts #1423 as the US Phone line incident is resolved.

Remove US Phoneline help centre banner

---

client/components/mma/accountoverview/AccountOverview.tsx
client/components/mma/accountoverview/CanadaStrike.tsx
client/components/mma/shared/ProblemAlert.tsx

Add a message/alert to the top of the account overview page for Canadian customers who have a Guardian Weekly or Tier Three subscription while the Canadian post strike is active informing them that they can suspend their deliveries.

Canada strike message

---

client/components/shared/Main.tsx
client/components/shared/footer/Footer.stories.tsx
client/components/shared/footer/Footer.tsx

Removes the support CTA from the footer in the help centre for the sake of app stores.

hide the support cta's from the help centre footer

---

client/components/mma/dataPrivacy/YourDataSection.tsx

We've had a request to change the marketing analysis consent copy to:
```
What we mean by your account data is information you provide when you register with us:
- First name and last name
- Email address
```
| Before | After |
|--------|--------|
| <img width="742" alt="image" src="https://github.com/user-attachments/assets/e4ab40c7-5a81-41fc-a19c-f61dae32a38f" /> | <img width="710" alt="image" src="https://github.com/user-attachments/assets/8bbc71b7-e41a-4dd3-8a4f-6134a97a9b59" /> |

Update Marketing analysis copy

---

client/components/mma/accountoverview/AccountOverview.stories.tsx
client/components/mma/accountoverview/ManageProduct.tsx
client/components/mma/accountoverview/ProductCard.tsx
client/components/mma/accountoverview/manageProducts/ManageProductV2.tsx
client/fixtures/productBuilder/productBuilder.ts
client/fixtures/productBuilder/testProducts.ts
client/styles/ButtonStyles.ts

Moves the cancellation cta from a link in the manage product page to the specific product card in the account overview. It is now a button instead of a link.
NOTE: This is currently only for products with a billing address in the US.
Account overview before             |  Account overview after

Move cancel btn, US only

---

client/components/helpCentre/HelpCentrePage.tsx

remove xmas 2024 opening times banner from the help centre

---

cdk/lib/__snapshots__/manage-frontend.test.ts.snap
cdk/lib/manage-frontend.ts
cdk/package.json
cdk/yarn.lock

Fix security vulnerability in `cross-spawn` in CDK land.
As part of this pr I have also updated the version of [`CDK`](https://github.com/guardian/cdk) we use by quite a few major versions.

CDK cross-span vuln fix (WIP)

---

client/components/mma/shared/benefits/BenefitsConfiguration.ts

Add's the feast app to the list of benefits for All access digital (supporter plus) and Tier three customers.
The benefits lists show up in the product card in the account overview and manage product pages as well as the product switch journey from contribution to all access digital.

supporterplus and tier three feast app benefit

---

.github/workflows/cypress-e2e.yml

The cypress e2e GitHub action workflow uses the v3 of the `upload-artifact` task which is being [deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/).
This upgrades to v4.

Upgrade to v4 of upload-artifact task in cypress workflow

---

client/components/helpCentre/HelpCentrePage.tsx

There is currently a technical issue with the US contact centre phonelines, meaning they are temporarily unavailable.
Adds a banner to the Help Centre to advise customers of the issue:
`Due to a technical issue, Customer Service phonelines in the USA & Canada are currently not available. Live chat and email are unaffected.`
We'll revert this once the phonelines are available.

Add banner to help centre as US phone lines are currently down

---

cypress/lib/signInOkta.ts

In Gateway we've now changed the way that sign in works, making passcodes the default option in https://github.com/guardian/gateway/pull/3035. So the sign in screen/flow has changed.
Instead to sign in with a password we have to navigate to a separate page to do so, which is what this PR does.

Fix Sign In Tests

---

client/components/mma/upgrade/ConfirmForm.tsx
client/components/mma/upgrade/UpgradeSupport.tsx
client/components/mma/upgrade/UpgradeSupportContainer.tsx
client/utilities/productUtils.ts

I noticed that I couldn't switch product as a test user in PROD, this was because it was trying to hit the PROD endpoint.  It looked like the extra header to flag whether it's a test user subscription wasn't being sent to manage-frontend backend.
This PR adds the extra header for product switches.
There may be other ones that are missing (TODO add logging in another PR)

allow test users to work with product-switch-api

---

server/apiGatewayDiscovery.ts

We noticed the product-switch-api didn't work with test users because the header wasn't being set by the client side.
This change makes the server side log when it notices the missing header, so that we can fix them more easily.
Hopefully the messages will go to sentry so we have a chance of spotting them?  Otherwise we can look in cloudwatch.

log if the test user header isn't set on the server side

---

client/__tests__/components/updateAmount/contributionUpdateAmount.test.tsx
client/__tests__/components/updateAmount/supporterPlusUpdateAmount.test.tsx
client/components/mma/accountoverview/ManageProduct.tsx
client/components/mma/accountoverview/updateAmount/SupporterPlusUpdateAmountForm.tsx
client/components/mma/accountoverview/updateAmount/UpdateAmount.tsx
client/components/mma/cancel/cancellationSaves/membership/MembershipSwitch.tsx
client/components/mma/switch/review/SwitchReview.tsx

following PR https://github.com/guardian/manage-frontend/pull/1450
I found I added it to the Move endpoint but not the Preview endpoint, which is defined in another place in the code.
I also noticed that update-supporter-plus-amount didn't work with test users.
This PR adds it to the other places I could find.
Tested locally and seems OK.

make sure the test user header is on preview as well as move endpoint

---

client/components/helpCentre/HelpCentrePage.tsx

Reverts the change in #1452, removing the banner from the help centre. The phonelines in the US and Canada are working again, for now.

Remove Help Centre banner again

---

server/routes/mpapi.ts

Expicitly returns after an MPAPI endpoint sends a 500 response (if it doesn't have access to idenity details). This stops the subsequent lines of code from running which are dependant on those idientity details being present.
This affected cypress integration tests that were asserting a redirect at the end of the test back to the account overview but not mocking the subsequent MDAPI and MPAPI api calls that would then be made.

Fix Cypress tests

---

client/components/mma/cancel/Cancellation.stories.tsx

The cancellation reasons are rendered in a random order on the client to avoid people from clicking on the first option and throwing off any analysis we might be able to gather from the results. This however resulted in a visual regression change in chromatic every time a pull request was made to manage regardless of whether you had updated the cancellation reasons. 
This pr fixes the ordering of the cancellation reasons in storybook/chromatic so that they don't appear to change order.

chromatic random content render fix

---

client/components/mma/accountoverview/AccountOverview.stories.tsx
client/components/mma/billing/Billing.stories.tsx
client/fixtures/cancelledProductDetail.ts
shared/productResponse.ts
shared/productTypes.ts

'Supporter ID' should become 'Subscription ID' in the account overview, manage product and billing pages
Cancelled ad-lite should have a cancelled prefix sentence before the cancellation date is rendered on the billing page

ad-lite bug fixes

---

client/components/mma/cancel/Cancellation.stories.tsx
client/components/mma/cancel/CancellationJourneyFunnel.tsx
client/components/mma/cancel/CancellationReasonSelection.tsx

I've moved the conditional logic to check to see if we should render the 'contact us to cancel' component out of the 'cancellation reason selection' component as we don't render the reasons to these users/products anyway.
It's been moved over to the 'CancellationJourneyFunnel' component which works as a conduit for various products cancellation journey and which path they should take.
Hopefully this change makes it more obvious that there are products that we need to show the 'contact us to cancel' component to and that this has nothing to do with the reason selection component.

conditional logic refactor (cencellation journey)

---

client/components/mma/accountoverview/AccountOverview.tsx

You have only 1 product and it is cancelled and therefore returned in the `/cancelled` api response on the account overview.
If you have only 1 product and it it cancelled then it should still show up in the account overview if it is returned in the '/cancelled' api response. Before if you didn't also have an active pruduct then it would render the empty account overview component

Show singular cancelled subscription

---

client/components/helpCentre/diagnosticInformation/DiagnosticInformation.tsx
client/components/helpCentre/diagnosticInformation/UserBenefitsInformation.tsx
server/apiProxy.ts
server/routes/api.ts

The diagnostics information page at `/help-centre/diagnostic-information` allows us to retrieve debug information for users who are experiencing issues. Up until now this page has not had any information from the user-benefits API.
This PR adds information from the user-benefits API

Add user-benefits information to the diagnostic information page

---

client/components/helpCentre/diagnosticInformation/CookieInformation.tsx

We don't use three of the ones that were there any more, but there are three new ones which we are interested in.

Update cookie names in diagnostics

---

client/components/mma/identity/idapi/user.ts
client/components/mma/identity/models.ts
client/components/mma/identity/settings/SettingsFormSection.tsx
client/fixtures/user.ts
cypress/tests/mocked/parallel-6/identitySettingsForm.cy.ts

Adds the ability for users to select/manage their state/territory location in the Settings tab when the user has the Location `Australia` or `United States`.
This new field is called `registrationLocationState`.
It only shows when the user has `Australia` or `United States` location selected. When a user changes location away from either of those two, we set the `registrationLocationState` to be blank (`''`) to remove this field from their profile.
<table>
<tr>
<th>Example
<tr>
<td>
https://github.com/user-attachments/assets/70f8e8d0-ac5f-4ffc-addd-349733b2be91
</table>
Guardian readers in Australia and the United States are bound by and impacted by state specific regulations and laws. Without this information we are unable to send state specific service emails, editorial newsletters, or …

Identity | Registration Location State

---

client/components/helpCentre/HelpCentrePage.tsx

The UK Phone line issue with our contact centre is now resolved, so we can remove the banner added this morning.
Reverts #1484, thus removing the banner.

Remove UK Phoneline banner

---

shared/productTypes.ts

When a customer adds holiday stops, we only show the notice period for Paper Voucher and Subscription Card products:
This is not shown for the other delivery products 😞 
Adds in the notice period for the Home Delivery and National Delivery products.
Check if there is a good way to word the Guardian Weekly product which I think is something like "earliest holiday stop date is a week on Saturday"? It's defined [here](https://github.com/guardian/support-service-lambdas/blob/main/handlers/fulfilment-date-calculator/src/main/scala/com/gu/supporter/fulfilment/GuardianWeekly.scala#L41).

Add the holiday stop notice period for newspaper print delivery products

---

cdk/lib/__snapshots__/manage-frontend.test.ts.snap
cdk/lib/manage-frontend.ts

This PR changes the manage-frontend ELB to use a restricted cypher list in order to pass our Tenable/nessus PCI testing. 
Currently it is complaining with this issue: https://www.tenable.com/plugins/nessus/159543
This [AWS doc](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/describe-ssl-policies.html) explains the options available, and the only list that is a subset of the Tenable list is: `ELBSecurityPolicy-TLS13-1-2-Res-2021-06`
[**Trello Card**](https://trello.com)
[none]
Tenable scan passes.
Fastly might not work with reduced cypher suite.

Make ELB to use a restricted cypher list in order to pass Nessus

---

client/components/mma/paymentUpdate/PaymentDetailUpdate.tsx
client/components/mma/paymentUpdate/dd/DirectDebitInputForm.tsx
client/fixtures/productBuilder/testProducts.ts
cypress/tests/mocked/parallel-1/updatePaymentDetails.cy.ts
shared/directDebit.ts
shared/productResponse.ts

Currently, our payment processing system handles Direct Debit payments through a single gateway owned by The Guardian. However, for Sunday The Observer subscriptions, we need to support an alternative payment gateway owned by Tortoise Media when the feature flag tortoiseStripeCheckout is enabled.
This PR:
- Creates a new DirectDebitGatewayOwner enum in a shared location to identify different payment gateways
- Adds an optional gatewayOwner field to the DirectDebitDetails interface
- Updates the PaymentDetailUpdate component to conditionally set the gateway owner to Tortoise Media for Sunday/Observer subscriptions when the feature flag is enabled
- Modifies the Direct Debit input form to pass the gateway owner information during payment method updates
These changes allow us to route Direct …

Direct Debit Gateway Owner Support for Sunday/Observer Subscriptions

---

client/components/mma/accountoverview/updateAmount/UpdateAmount.tsx

The amountUpdateStateChange function in the UpdateAmount component stopped being called after a refactoring on December 9, 2020. During that refactoring, Tom Pretty restructured the page but inadvertently removed the calls to amountUpdateStateChange in the component's two update pathways. This omission has been causing state inconsistencies whenever users update their contribution amounts, as the parent component isn't notified about the changes.
This PR reintroduces the missing amountUpdateStateChange calls in both update flow paths within the UpdateAmount component:
1. Added props.amountUpdateStateChange(updatedAmount) in the update confirmation handler
These changes ensure that when a user confirms an amount update, the parent component is properly notified via the callback prop, …

Fix Subscription Amount Update state change

---

client/components/mma/paymentUpdate/PaymentDetailUpdate.tsx
client/components/mma/paymentUpdate/PaymentDetailUpdateCheckoutSessionReturn.tsx
client/components/mma/paymentUpdate/PaymentDetailUpdateContainer.tsx
client/components/mma/paymentUpdate/card/StripeCheckoutSessionButton.tsx
server/stripeCreateCheckoutSessionHandler.ts
shared/requests/stripe-create-checkout-session.ts

Currently, our payment method update journey has an issue when users have multiple subscriptions of the same product type. When a user with multiple subscriptions attempts to update their payment method:
1. The system cannot determine which specific subscription to update if the user navigates directly to the payment update URL (e.g., https://manage.thegulocal.com/payment/homedelivery/)
2. If there are multiple subscriptions of the same product type, the system redirects to the overview page
3. This creates problems when users are redirected back from external payment platforms (like Stripe Checkout), as the context of which subscription is being updated is lost
This issue was discovered during testing of the Stripe Checkout flow for updating payment methods for Observer subscriptions …

Fix Payment Method Update Journey with Multiple Subscriptions of the Same Product

---

.github/workflows/chromatic.yml
.github/workflows/ci.yml
.github/workflows/cypress-e2e.yml
.github/workflows/cypress-mocked.yml

We noticed that our chromatic action was failing with a 422 error code:
`setup-node@v2` relies on a deprecated version of `@actions/cache`. Upgrading to v4 will hopefully fix this issue.
https://github.com/actions/setup-node/issues/1275#issuecomment-2788204086

update setup-node action version

---

client/components/mma/delivery/records/DeliveryAddressStep.tsx
client/components/mma/delivery/records/DeliveryRecords.stories.tsx
client/components/mma/delivery/records/DeliveryRecords.tsx
client/components/mma/delivery/records/ReadOnlyAddressDisplay.tsx
client/components/mma/shared/InfoSection.tsx
client/fixtures/deliveryRecords.ts
client/fixtures/productBuilder/productBuilder.ts
client/fixtures/productBuilder/testProducts.ts
cypress/tests/mocked/parallel-4/deliveryRecords.cy.ts

Make the delivery instructions input clearer to the user when they are reporting a delivery issue.
This will hopefully reduce the number of issues reported in the future for deliveries that may have been made correctly if delivery instructions were available.

Delivery records instructions refactor

---

client/components/mma/accountoverview/ProductCard.tsx
client/components/mma/cancel/cancellationSaves/membership/MembershipSwitch.tsx
client/components/mma/cancel/cancellationSaves/membership/SaveOptions.tsx
client/components/mma/shared/NextPaymentDetails.tsx
shared/productResponse.ts

Currently, when a user has scheduled a future change to their subscription (such as downgrading from a higher tier membership to Contributor), this information is not displayed in the Account Overview page. Additionally, the system is incorrectly allowing users to navigate to the Membership Switch flow even when they already have a future plan change scheduled.
This PR makes several improvements to how we handle and display future subscription plans:
1. Added a `futureProductTitle` variable in ProductCard that determines if there's a future plan change scheduled
2. Modified the product details section to display the "Next product" information when a future plan change exists
3. Updated the MembershipSwitch component to redirect users to the Overview page if they already have a future plan …

Display future product tier

---

client/__tests__/components/helpCentre/__snapshots__/helpCentreContactOptions.test.tsx.snap
client/components/shared/callCentreData.ts

This updates the copy for contacting our contact centre over the phone from the US and Canada to reflect that the toll free number is applicable to both the US and Canada. This came as a [request from CX](https://trello.com/c/AwdguSBd/118-update-the-descriptions-for-the-us-canada-phone-lines-toll-free-covers-canada-as-well-as-us) following a report from a customer.

Update US and Canada Phone Line copy

---

client/components/mma/cancel/cancellationSaves/CancelAlternativeSwitch.tsx

Update of the background image for the cancellation switch to supporter plus with a discount page
| ![](https://github.com/user-attachments/assets/f361d90e-9367-48ba-8375-3bf9e3de6233)  | ![](https://github.com/user-attachments/assets/256daab8-11c6-4ac6-89b7-e09c0d3c70df)  |

update cancel switch discount background image

---

client/components/mma/cancel/CancellationReasonReview.tsx
cypress/tests/mocked/parallel-2/cancelContribution.cy.ts

Temporarily disable contribution cancellation switch discount offer for people with a billing country outside of the UK ... until we are ready to launch worldwide.
This is a soft validation block on the client and just serves to reduce/stop calls out to the switch api for customers outside of the UK ... the switch api isn't currently setup to handle billing countries outside of the UK yet so the switch discount wouldn't have worked for them anyway.

Only UK billing country contributions should be able to switch with a discount to supporter plus (via cancellation journey)

---

shared/productTypes.ts

Removes any elements from the `softOptInIDs` array in the productTypes file for all Observer products. The consequence of doing this is to remove the supporter email opt ins from the emails and marketting page for people that only have Observer products ... these emails are Guardian related.

remove Observer product softOptInIDs

---

client/components/mma/cancel/CancellationReasonReview.tsx
client/components/mma/cancel/cancellationSaves/saveEligibilityCheck.ts
client/components/mma/cancel/contributions/ContributionsCancellationFlowFinancialSaveAttempt.tsx
cypress/tests/mocked/parallel-2/cancelContribution.cy.ts

If you choose financial reasons like "I can no longer afford to support you" as the reason for cancelling then you are shown a custom page that asks if you would like to reduce your contribution amount before possibly being shown the switch discount offer. This page was missing the billing country validation (switch discount offer currently only applies to people in the UK) which determines whether a call to the switch-api is made or not.

Switch discount financial reasons

---

client/components/helpCentre/contactUs/UploadFileInput.tsx
client/components/helpCentre/contactUs/contactUsForm.stories.tsx
client/components/helpCentre/contactUs/contactUsForm.tsx
cypress/tests/mocked/parallel-3/contactUsForm.cy.ts

The Help Centrer contact form had some usability and validation issues:
- Validation state was one step behind user input
- Autofocus was not applied to the first invalid field, causing confusion
- Error messages could go unnoticed if not scrolled into view
This PR improves the form experience by:
- Implementing autofocus on the first invalid field when the form is submitted
- Refactoring form validation state management to ensure real-time accuracy using useCallback + useEffect
Additional fixes:
- Trims input values before validation
- Reduces validation logic to a single-pass filter over fields
- Ensures setFocus and error state behave correctly across all fields
To test:
- Submit the form without filling anything — first invalid field should autofocus
- As you type into fields, error …

Improves the form validation state management and implements autofocus on failed validation fields

---

client/components/helpCentre/KnownIssues.tsx
client/components/helpCentre/diagnosticInformation/SubscriptionInformation.tsx
client/components/mma/accountoverview/AccountOverview.tsx
client/components/mma/accountoverview/CancelledProductCard.tsx
client/components/mma/accountoverview/ProductCard.tsx
client/components/mma/billing/Billing.tsx
client/components/mma/cancel/CancellationJourneyFunnel.tsx
client/components/mma/cancel/cancellationSaves/CancellationLanding.tsx
client/components/mma/cancel/cancellationSaves/membership/MembershipSwitch.tsx
client/components/mma/cancel/cancellationSaves/membership/SaveOptions.tsx
client/components/mma/cancel/cancellationSaves/saveEligibilityCheck.ts
client/components/mma/delivery/address/DeliveryAddressForm.tsx
client/components/mma/delivery/records/DeliveryAddressStep.tsx
client/components/mma/holiday/HolidayReview.tsx
client/components/mma/identity/emailAndMarketing/EmailAndMarketing.tsx
client/components/mma/paymentUpdate/CurrentPaymentDetail.tsx
client/components/mma/paymentUpdate/PaymentDetailUpdateConfirmation.tsx
client/components/mma/shared/BasicProductInfoTable.tsx
client/components/mma/shared/PaymentFailureAlertIfApplicable.tsx
client/components/mma/switch/options/SwitchOptions.tsx
client/fixtures/cancelledProductDetail.ts
client/fixtures/productBuilder/baseProducts.ts
client/fixtures/productBuilder/productBuilder.ts
client/fixtures/productBuilder/testProducts.ts
client/utilities/deliveryAddress.ts
cypress/tests/mocked/parallel-1/updatePaymentDetails.cy.ts
server/fulfilmentDateCalculatorReader.ts
shared/productResponse.ts
shared/productTypes.ts

PR makes the shift from the previously used `tier` property to the new `mmaProductTier`, as part of the effort to release newspaper+digital benefits.
Changes to use the new property, naming of some functions and everything needed to support that change.

Moves code to the use of new property mmaProductKey

---

client/components/helpCentre/KnownIssues.tsx
client/components/helpCentre/diagnosticInformation/SubscriptionInformation.tsx
client/components/mma/accountoverview/AccountOverview.tsx
client/components/mma/accountoverview/CancelledProductCard.tsx
client/components/mma/accountoverview/ProductCard.tsx
client/components/mma/billing/Billing.tsx
client/components/mma/cancel/CancellationJourneyFunnel.tsx
client/components/mma/cancel/cancellationSaves/CancellationLanding.tsx
client/components/mma/cancel/cancellationSaves/membership/MembershipSwitch.tsx
client/components/mma/cancel/cancellationSaves/membership/SaveOptions.tsx
client/components/mma/cancel/cancellationSaves/saveEligibilityCheck.ts
client/components/mma/delivery/address/DeliveryAddressForm.tsx
client/components/mma/delivery/records/DeliveryAddressStep.tsx
client/components/mma/holiday/HolidayReview.tsx
client/components/mma/identity/emailAndMarketing/EmailAndMarketing.tsx
client/components/mma/paymentUpdate/CurrentPaymentDetail.tsx
client/components/mma/paymentUpdate/PaymentDetailUpdateConfirmation.tsx
client/components/mma/shared/BasicProductInfoTable.tsx
client/components/mma/shared/PaymentFailureAlertIfApplicable.tsx
client/components/mma/switch/options/SwitchOptions.tsx
client/fixtures/cancelledProductDetail.ts
client/fixtures/productBuilder/baseProducts.ts
client/fixtures/productBuilder/productBuilder.ts
client/fixtures/productBuilder/testProducts.ts
client/utilities/deliveryAddress.ts
cypress/tests/mocked/parallel-1/updatePaymentDetails.cy.ts
server/fulfilmentDateCalculatorReader.ts
shared/productResponse.ts
shared/productTypes.ts

Reverts guardian/manage-frontend#1523
Reverting because the above PR doesn't include the new `+ Digital` in the getSpecificProductTypeFromProductKey function, so anyone on paper+ no longer can see their product.

Revert "Moves code to the use of new property mmaProductKey"

---

client/components/mma/accountoverview/ProductCard.tsx
client/components/mma/shared/NextPaymentDetails.tsx
shared/productResponse.ts

Make the offer period copy more generic to handle any length of offer, eg 2 months or 24month.
Change the subscription (MDAPI) 'nextPaymentPrice' property to expect a value and not be null, however this is based on the response from an API and so cannot be guaranteed hence we kept the null coalessing check when rendering the price (with an additional comment)

Offer period copy changes

---

client/components/helpCentre/liveChat/LiveChat.tsx

The [Help Centre](https://manage.theguardian.com/help-centre) hosts our Live Chat implementation, which is powered by Salesforce. This current setup uses a legacy product (Live Agent) to configure Live Chat in Salesforce and Help Centre. Live Agent is being retired on February 14th 2026 and will need to be replaced with the newest configuration (Messaging for In App and Web). Messaging for In App and Web offers more advanced features and lays the groundwork for future use of bots and Agentic AI over the long term.
The following documentation provides an overview of the project as a whole:
[Trello Card](https://trello.com/c/RURR6iCM/65-sf-live-chat-deprecation-update) 
[SPIKE document into migration to Messaging for In App and Web](https://docs.google.com/document/d/1ZFCO9hcL8Ft2xZpt3dOhUPg …

point help centre CODE at the new live Chat testing sandbox

---

client/utilities/hooks/useAnalytics.ts

No traffic has been going to Quantum Metric since July 15.
This reverts the Quantum Metric hash that was changed here https://github.com/guardian/manage-frontend/pull/1531 and caused the issue.
Tested in CODE

Revert QM hash change

---

client/components/mma/accountoverview/InAppPurchaseCard.tsx
client/components/mma/accountoverview/ProductCardConfiguration.ts
shared/mpapiResponse.ts

Users with Feast app subscriptions (productId: `uk.co.guardian.Feast.yearly`) were incorrectly seeing "Live App" subscription status in MMA instead of being properly identified as Feast app subscribers. The frontend was treating all mobile subscriptions uniformly without distinguishing between news app, puzzle app, and Feast app products. This situation is described by this [card](https://trello.com/c/wL1CcDxM/469-filter-out-feast-subscriptions-from-mdapi-when-checking-for-live-app-subs) and its associated [conversation thread](https://chat.google.com/room/AAAAuotUxTg/ei-7b301LDA/ei-7b301LDA?cls=10). The backend change that allows this new implementation to work can be tracked to this [pull request](https://github.com/guardian/members-data-api/pull/1142).
The issue stemmed from the lack …

Add support for Feast app in InAppPurchaseCard

---

client/components/mma/cancel/cancellationSaves/CancelAlternativeSwitchReview.tsx
client/components/mma/cancel/cancellationSaves/saveEligibilityCheck.ts

We need to expand our cancellation journey incentives to the US for Recurring contributor annual users. The offer, switch to All Access Digital (Supporter Plus) is currently only available in the UK and we now have agreement we can make this available in the US.
- Extends the switch discount availability to United States based users
- Updates the corresponding copy in the Switch Review page

Allows United States based users to get the cancellation switch offer

---

client/components/mma/accountoverview/ProductCard.tsx

After an e2e testing for the student page, a reference to recurring payment and cancellation on MMA was spotted. After some research we found out that the "Cancellation Subscription" feature only is displayed for subscriptions with United States as billing country, making it the reason why we missed this to begin with.
Changes the copywriting of this feature when a subscription as no auto-renew and as no next Payment Date.
The original conversation could be read [here](https://chat.google.com/room/AAQAK5a5stM/aE9hJ-FO4dw/aE9hJ-FO4dw?cls=10).
| Before    | After |
| -------- | ------- |
| <img width="898" height="807" alt="Screenshot 2025-09-17 at 15 04 35" src="https://github.com/user-attachments/assets/be7ed23a-be35-41e9-b061-eb0a0f5c3672" /> | <img width="1438" height="1012" …

Change Cancellation Message for one-off payment and renewal status in ProductCard

---

client/components/mma/accountoverview/AccountOverview.tsx

The Cannada Strike banner introduced last week might be causing an issue in MMA, as it's expecting `country` when deliveryAddress is present for a subscription. I've been advised to remove the banner for now.
- Removes the CanadaStrike banner condition for eligibility

Removes canada banner to solve potential bug with country

---

client/components/helpCentre/HelpCentrePage.tsx

Ongoing postal strikes in Canada mean that Guardian Weekly subscribers are currently not receiving their publications.
Adds a banner to the Help Centre with some basic information about the situation:
> [!NOTE]
> We also plan to add a banner to the MMA account overview specifically for Canadian GW subscribers, see #1558  
When the strikes are resolved, we will remove the banner again.

Add Canada Post strike Help Centre banner
